// Generated by `cargo xtask machine-codegen --all`.
#![allow(
    clippy::expect_used,
    clippy::ptr_arg,
    clippy::redundant_clone,
    clippy::redundant_closure,
    clippy::uninlined_format_args,
    dead_code
)]
use crate::compat_generated::flow_run::{Effect, KernelError, Phase, State};
use crate::runtime::{KernelEffect as LegacyEffect, KernelState as LegacyState, KernelValue};
use meerkat_machine_schema::compat::types as compat_types;

#[cfg(feature = "test-oracle")]
fn effect_to_kernel(effect: &Effect) -> LegacyEffect {
    match effect {
        Effect::EmitFlowRunNotice(payload) => LegacyEffect {
            variant: "EmitFlowRunNotice".to_string(),
            fields: std::collections::BTreeMap::from([(
                "run_status".to_string(),
                value_to_kernel_enum_flow_run_status(&payload.run_status),
            )]),
        },
        Effect::EmitStepNotice(payload) => LegacyEffect {
            variant: "EmitStepNotice".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "step_id".to_string(),
                    value_to_kernel_named_step_id(&payload.step_id),
                ),
                (
                    "step_status".to_string(),
                    value_to_kernel_enum_step_run_status(&payload.step_status),
                ),
            ]),
        },
        Effect::AppendFailureLedger(payload) => LegacyEffect {
            variant: "AppendFailureLedger".to_string(),
            fields: std::collections::BTreeMap::from([(
                "step_id".to_string(),
                value_to_kernel_named_step_id(&payload.step_id),
            )]),
        },
        Effect::PersistStepOutput(payload) => LegacyEffect {
            variant: "PersistStepOutput".to_string(),
            fields: std::collections::BTreeMap::from([(
                "step_id".to_string(),
                value_to_kernel_named_step_id(&payload.step_id),
            )]),
        },
        Effect::AdmitStepWork(payload) => LegacyEffect {
            variant: "AdmitStepWork".to_string(),
            fields: std::collections::BTreeMap::from([(
                "step_id".to_string(),
                value_to_kernel_named_step_id(&payload.step_id),
            )]),
        },
        Effect::FlowTerminalized(payload) => LegacyEffect {
            variant: "FlowTerminalized".to_string(),
            fields: std::collections::BTreeMap::from([(
                "run_status".to_string(),
                value_to_kernel_enum_flow_run_status(&payload.run_status),
            )]),
        },
        Effect::EscalateSupervisor(payload) => LegacyEffect {
            variant: "EscalateSupervisor".to_string(),
            fields: std::collections::BTreeMap::from([(
                "step_id".to_string(),
                value_to_kernel_named_step_id(&payload.step_id),
            )]),
        },
        Effect::ProjectTargetSuccess(payload) => LegacyEffect {
            variant: "ProjectTargetSuccess".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "step_id".to_string(),
                    value_to_kernel_named_step_id(&payload.step_id),
                ),
                (
                    "target_id".to_string(),
                    value_to_kernel_named_meerkat_id(&payload.target_id),
                ),
            ]),
        },
        Effect::ProjectTargetFailure(payload) => LegacyEffect {
            variant: "ProjectTargetFailure".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "step_id".to_string(),
                    value_to_kernel_named_step_id(&payload.step_id),
                ),
                (
                    "target_id".to_string(),
                    value_to_kernel_named_meerkat_id(&payload.target_id),
                ),
            ]),
        },
        Effect::ProjectTargetCanceled(payload) => LegacyEffect {
            variant: "ProjectTargetCanceled".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "step_id".to_string(),
                    value_to_kernel_named_step_id(&payload.step_id),
                ),
                (
                    "target_id".to_string(),
                    value_to_kernel_named_meerkat_id(&payload.target_id),
                ),
            ]),
        },
        Effect::GrantNodeSlot(payload) => LegacyEffect {
            variant: "GrantNodeSlot".to_string(),
            fields: std::collections::BTreeMap::from([(
                "frame_id".to_string(),
                value_to_kernel_named_frame_id(&payload.frame_id),
            )]),
        },
        Effect::GrantBodyFrameStart(payload) => LegacyEffect {
            variant: "GrantBodyFrameStart".to_string(),
            fields: std::collections::BTreeMap::from([(
                "loop_instance_id".to_string(),
                value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
            )]),
        },
    }
}

#[cfg(feature = "test-oracle")]
pub fn to_test_oracle_effect(effect: &Effect) -> crate::test_oracle::KernelEffect {
    effect_to_kernel(effect)
}

fn state_to_kernel(state: &State) -> LegacyState {
    LegacyState {
        phase: phase_to_string(&state.phase).to_string(),
        fields: std::collections::BTreeMap::from([
            (
                "tracked_steps".to_string(),
                value_to_kernel_set_named_step_id(&state.tracked_steps),
            ),
            (
                "ordered_steps".to_string(),
                value_to_kernel_seq_named_step_id(&state.ordered_steps),
            ),
            (
                "step_status".to_string(),
                value_to_kernel_map_named_step_id_option_enum_step_run_status(&state.step_status),
            ),
            (
                "output_recorded".to_string(),
                value_to_kernel_map_named_step_id_bool(&state.output_recorded),
            ),
            (
                "step_condition_results".to_string(),
                value_to_kernel_map_named_step_id_option_bool(&state.step_condition_results),
            ),
            (
                "step_has_conditions".to_string(),
                value_to_kernel_map_named_step_id_bool(&state.step_has_conditions),
            ),
            (
                "step_dependencies".to_string(),
                value_to_kernel_map_named_step_id_seq_named_step_id(&state.step_dependencies),
            ),
            (
                "step_dependency_modes".to_string(),
                value_to_kernel_map_named_step_id_enum_dependency_mode(
                    &state.step_dependency_modes,
                ),
            ),
            (
                "step_branches".to_string(),
                value_to_kernel_map_named_step_id_option_named_branch_id(&state.step_branches),
            ),
            (
                "step_collection_policies".to_string(),
                value_to_kernel_map_named_step_id_enum_collection_policy_kind(
                    &state.step_collection_policies,
                ),
            ),
            (
                "step_quorum_thresholds".to_string(),
                value_to_kernel_map_named_step_id_u32(&state.step_quorum_thresholds),
            ),
            (
                "step_target_counts".to_string(),
                value_to_kernel_map_named_step_id_u32(&state.step_target_counts),
            ),
            (
                "step_target_success_counts".to_string(),
                value_to_kernel_map_named_step_id_u32(&state.step_target_success_counts),
            ),
            (
                "step_target_terminal_failure_counts".to_string(),
                value_to_kernel_map_named_step_id_u32(&state.step_target_terminal_failure_counts),
            ),
            (
                "target_retry_counts".to_string(),
                value_to_kernel_map_string_u32(&state.target_retry_counts),
            ),
            (
                "failure_count".to_string(),
                value_to_kernel_u32(&state.failure_count),
            ),
            (
                "consecutive_failure_count".to_string(),
                value_to_kernel_u32(&state.consecutive_failure_count),
            ),
            (
                "escalation_threshold".to_string(),
                value_to_kernel_u32(&state.escalation_threshold),
            ),
            (
                "max_step_retries".to_string(),
                value_to_kernel_u32(&state.max_step_retries),
            ),
            (
                "ready_frames".to_string(),
                value_to_kernel_seq_named_frame_id(&state.ready_frames),
            ),
            (
                "ready_frame_membership".to_string(),
                value_to_kernel_set_named_frame_id(&state.ready_frame_membership),
            ),
            (
                "pending_body_frame_loops".to_string(),
                value_to_kernel_seq_named_loop_instance_id(&state.pending_body_frame_loops),
            ),
            (
                "pending_body_frame_loop_membership".to_string(),
                value_to_kernel_set_named_loop_instance_id(
                    &state.pending_body_frame_loop_membership,
                ),
            ),
            (
                "active_node_count".to_string(),
                value_to_kernel_u32(&state.active_node_count),
            ),
            (
                "active_frame_count".to_string(),
                value_to_kernel_u32(&state.active_frame_count),
            ),
            (
                "max_active_nodes".to_string(),
                value_to_kernel_u32(&state.max_active_nodes),
            ),
            (
                "max_active_frames".to_string(),
                value_to_kernel_u32(&state.max_active_frames),
            ),
            (
                "max_frame_depth".to_string(),
                value_to_kernel_u32(&state.max_frame_depth),
            ),
            (
                "last_granted_frame".to_string(),
                value_to_kernel_named_frame_id(&state.last_granted_frame),
            ),
            (
                "last_granted_loop".to_string(),
                value_to_kernel_named_loop_instance_id(&state.last_granted_loop),
            ),
        ]),
    }
}

fn state_from_kernel(state: LegacyState) -> Result<State, KernelError> {
    let mut fields = state.fields;
    Ok(State {
        phase: phase_from_string(&state.phase)?,
        tracked_steps: value_from_kernel_set_named_step_id(
            take_field(&mut fields, "state", "tracked_steps")?,
            "state field `tracked_steps`",
        )?,
        ordered_steps: value_from_kernel_seq_named_step_id(
            take_field(&mut fields, "state", "ordered_steps")?,
            "state field `ordered_steps`",
        )?,
        step_status: value_from_kernel_map_named_step_id_option_enum_step_run_status(
            take_field(&mut fields, "state", "step_status")?,
            "state field `step_status`",
        )?,
        output_recorded: value_from_kernel_map_named_step_id_bool(
            take_field(&mut fields, "state", "output_recorded")?,
            "state field `output_recorded`",
        )?,
        step_condition_results: value_from_kernel_map_named_step_id_option_bool(
            take_field(&mut fields, "state", "step_condition_results")?,
            "state field `step_condition_results`",
        )?,
        step_has_conditions: value_from_kernel_map_named_step_id_bool(
            take_field(&mut fields, "state", "step_has_conditions")?,
            "state field `step_has_conditions`",
        )?,
        step_dependencies: value_from_kernel_map_named_step_id_seq_named_step_id(
            take_field(&mut fields, "state", "step_dependencies")?,
            "state field `step_dependencies`",
        )?,
        step_dependency_modes: value_from_kernel_map_named_step_id_enum_dependency_mode(
            take_field(&mut fields, "state", "step_dependency_modes")?,
            "state field `step_dependency_modes`",
        )?,
        step_branches: value_from_kernel_map_named_step_id_option_named_branch_id(
            take_field(&mut fields, "state", "step_branches")?,
            "state field `step_branches`",
        )?,
        step_collection_policies: value_from_kernel_map_named_step_id_enum_collection_policy_kind(
            take_field(&mut fields, "state", "step_collection_policies")?,
            "state field `step_collection_policies`",
        )?,
        step_quorum_thresholds: value_from_kernel_map_named_step_id_u32(
            take_field(&mut fields, "state", "step_quorum_thresholds")?,
            "state field `step_quorum_thresholds`",
        )?,
        step_target_counts: value_from_kernel_map_named_step_id_u32(
            take_field(&mut fields, "state", "step_target_counts")?,
            "state field `step_target_counts`",
        )?,
        step_target_success_counts: value_from_kernel_map_named_step_id_u32(
            take_field(&mut fields, "state", "step_target_success_counts")?,
            "state field `step_target_success_counts`",
        )?,
        step_target_terminal_failure_counts: value_from_kernel_map_named_step_id_u32(
            take_field(&mut fields, "state", "step_target_terminal_failure_counts")?,
            "state field `step_target_terminal_failure_counts`",
        )?,
        target_retry_counts: value_from_kernel_map_string_u32(
            take_field(&mut fields, "state", "target_retry_counts")?,
            "state field `target_retry_counts`",
        )?,
        failure_count: value_from_kernel_u32(
            take_field(&mut fields, "state", "failure_count")?,
            "state field `failure_count`",
        )?,
        consecutive_failure_count: value_from_kernel_u32(
            take_field(&mut fields, "state", "consecutive_failure_count")?,
            "state field `consecutive_failure_count`",
        )?,
        escalation_threshold: value_from_kernel_u32(
            take_field(&mut fields, "state", "escalation_threshold")?,
            "state field `escalation_threshold`",
        )?,
        max_step_retries: value_from_kernel_u32(
            take_field(&mut fields, "state", "max_step_retries")?,
            "state field `max_step_retries`",
        )?,
        ready_frames: value_from_kernel_seq_named_frame_id(
            take_field(&mut fields, "state", "ready_frames")?,
            "state field `ready_frames`",
        )?,
        ready_frame_membership: value_from_kernel_set_named_frame_id(
            take_field(&mut fields, "state", "ready_frame_membership")?,
            "state field `ready_frame_membership`",
        )?,
        pending_body_frame_loops: value_from_kernel_seq_named_loop_instance_id(
            take_field(&mut fields, "state", "pending_body_frame_loops")?,
            "state field `pending_body_frame_loops`",
        )?,
        pending_body_frame_loop_membership: value_from_kernel_set_named_loop_instance_id(
            take_field(&mut fields, "state", "pending_body_frame_loop_membership")?,
            "state field `pending_body_frame_loop_membership`",
        )?,
        active_node_count: value_from_kernel_u32(
            take_field(&mut fields, "state", "active_node_count")?,
            "state field `active_node_count`",
        )?,
        active_frame_count: value_from_kernel_u32(
            take_field(&mut fields, "state", "active_frame_count")?,
            "state field `active_frame_count`",
        )?,
        max_active_nodes: value_from_kernel_u32(
            take_field(&mut fields, "state", "max_active_nodes")?,
            "state field `max_active_nodes`",
        )?,
        max_active_frames: value_from_kernel_u32(
            take_field(&mut fields, "state", "max_active_frames")?,
            "state field `max_active_frames`",
        )?,
        max_frame_depth: value_from_kernel_u32(
            take_field(&mut fields, "state", "max_frame_depth")?,
            "state field `max_frame_depth`",
        )?,
        last_granted_frame: value_from_kernel_named_frame_id(
            take_field(&mut fields, "state", "last_granted_frame")?,
            "state field `last_granted_frame`",
        )?,
        last_granted_loop: value_from_kernel_named_loop_instance_id(
            take_field(&mut fields, "state", "last_granted_loop")?,
            "state field `last_granted_loop`",
        )?,
    })
}

#[cfg(feature = "test-oracle")]
pub fn from_test_oracle_state(
    state: crate::test_oracle::KernelState,
) -> Result<State, KernelError> {
    state_from_kernel(state)
}

#[cfg(feature = "test-oracle")]
pub fn to_test_oracle_state(state: &State) -> crate::test_oracle::KernelState {
    state_to_kernel(state)
}

fn phase_to_string(phase: &Phase) -> &'static str {
    match phase {
        Phase::Absent => "Absent",
        Phase::Pending => "Pending",
        Phase::Running => "Running",
        Phase::Completed => "Completed",
        Phase::Failed => "Failed",
        Phase::Canceled => "Canceled",
    }
}

fn phase_from_string(phase: &str) -> Result<Phase, KernelError> {
    match phase {
        "Absent" => Ok(Phase::Absent),
        "Pending" => Ok(Phase::Pending),
        "Running" => Ok(Phase::Running),
        "Completed" => Ok(Phase::Completed),
        "Failed" => Ok(Phase::Failed),
        "Canceled" => Ok(Phase::Canceled),
        other => Err(KernelError::CodegenInvariant {
            detail: format!("unknown phase `{other}`"),
        }),
    }
}

fn take_field(
    fields: &mut std::collections::BTreeMap<String, KernelValue>,
    container: &str,
    field: &str,
) -> Result<KernelValue, KernelError> {
    fields
        .remove(field)
        .ok_or_else(|| KernelError::CodegenInvariant {
            detail: format!("{container} missing field `{field}`"),
        })
}

fn kernel_option_some(value: KernelValue) -> KernelValue {
    KernelValue::Map(std::collections::BTreeMap::from([(
        KernelValue::String("value".to_string()),
        value,
    )]))
}

fn kernel_type_error(context: &str, expected: &str, value: &KernelValue) -> KernelError {
    KernelError::CodegenInvariant {
        detail: format!("{context} expected {expected}, found {value:?}"),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_step_id(value: &compat_types::StepId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_step_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::StepId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::StepId(value)),
        other => Err(kernel_type_error(context, "StepId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_set_named_step_id(
    value: &std::collections::BTreeSet<compat_types::StepId>,
) -> KernelValue {
    KernelValue::Set(
        value
            .iter()
            .map(|item| value_to_kernel_named_step_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_set_named_step_id(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeSet<compat_types::StepId>, KernelError> {
    match value {
        KernelValue::Set(values) => {
            let mut out = std::collections::BTreeSet::new();
            for value in values {
                out.insert(value_from_kernel_named_step_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Set(StepId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_seq_named_step_id(value: &Vec<compat_types::StepId>) -> KernelValue {
    KernelValue::Seq(
        value
            .iter()
            .map(|item| value_to_kernel_named_step_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_seq_named_step_id(
    value: KernelValue,
    context: &str,
) -> Result<Vec<compat_types::StepId>, KernelError> {
    match value {
        KernelValue::Seq(values) => {
            let mut out = Vec::new();
            for value in values {
                out.push(value_from_kernel_named_step_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Seq(StepId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_step_run_status(value: &compat_types::StepRunStatus) -> KernelValue {
    let variant = match value {
        compat_types::StepRunStatus::Dispatched => "Dispatched",
        compat_types::StepRunStatus::Completed => "Completed",
        compat_types::StepRunStatus::Failed => "Failed",
        compat_types::StepRunStatus::Skipped => "Skipped",
        compat_types::StepRunStatus::Canceled => "Canceled",
    };
    KernelValue::NamedVariant {
        enum_name: "StepRunStatus".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_step_run_status(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::StepRunStatus, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "StepRunStatus" => {
            match variant.as_str() {
                "Dispatched" => Ok(compat_types::StepRunStatus::Dispatched),
                "Completed" => Ok(compat_types::StepRunStatus::Completed),
                "Failed" => Ok(compat_types::StepRunStatus::Failed),
                "Skipped" => Ok(compat_types::StepRunStatus::Skipped),
                "Canceled" => Ok(compat_types::StepRunStatus::Canceled),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected StepRunStatus variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "StepRunStatus", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_option_enum_step_run_status(
    value: &Option<compat_types::StepRunStatus>,
) -> KernelValue {
    match value {
        Some(inner) => kernel_option_some(value_to_kernel_enum_step_run_status(inner)),
        None => KernelValue::None,
    }
}

#[allow(dead_code)]
fn value_from_kernel_option_enum_step_run_status(
    value: KernelValue,
    context: &str,
) -> Result<Option<compat_types::StepRunStatus>, KernelError> {
    match value {
        KernelValue::None => Ok(None),
        KernelValue::Map(mut entries) => {
            if let Some(inner) = entries.remove(&KernelValue::String("value".to_string())) {
                Ok(Some(value_from_kernel_enum_step_run_status(
                    inner, context,
                )?))
            } else {
                Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected option value payload"),
                })
            }
        }
        other => Ok(Some(value_from_kernel_enum_step_run_status(
            other, context,
        )?)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_option_enum_step_run_status(
    value: &std::collections::BTreeMap<compat_types::StepId, Option<compat_types::StepRunStatus>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_option_enum_step_run_status(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_option_enum_step_run_status(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::StepId, Option<compat_types::StepRunStatus>>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_option_enum_step_run_status(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(StepId, Option(StepRunStatus))",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_bool(value: &bool) -> KernelValue {
    KernelValue::Bool(*value)
}

#[allow(dead_code)]
fn value_from_kernel_bool(value: KernelValue, context: &str) -> Result<bool, KernelError> {
    match value {
        KernelValue::Bool(value) => Ok(value),
        other => Err(kernel_type_error(context, "bool", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_bool(
    value: &std::collections::BTreeMap<compat_types::StepId, bool>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_bool(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_bool(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<compat_types::StepId, bool>, KernelError> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_bool(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Map(StepId, bool)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_option_bool(value: &Option<bool>) -> KernelValue {
    match value {
        Some(inner) => kernel_option_some(value_to_kernel_bool(inner)),
        None => KernelValue::None,
    }
}

#[allow(dead_code)]
fn value_from_kernel_option_bool(
    value: KernelValue,
    context: &str,
) -> Result<Option<bool>, KernelError> {
    match value {
        KernelValue::None => Ok(None),
        KernelValue::Map(mut entries) => {
            if let Some(inner) = entries.remove(&KernelValue::String("value".to_string())) {
                Ok(Some(value_from_kernel_bool(inner, context)?))
            } else {
                Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected option value payload"),
                })
            }
        }
        other => Ok(Some(value_from_kernel_bool(other, context)?)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_option_bool(
    value: &std::collections::BTreeMap<compat_types::StepId, Option<bool>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_option_bool(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_option_bool(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<compat_types::StepId, Option<bool>>, KernelError> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_option_bool(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(StepId, Option(bool))",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_seq_named_step_id(
    value: &std::collections::BTreeMap<compat_types::StepId, Vec<compat_types::StepId>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_seq_named_step_id(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_seq_named_step_id(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<compat_types::StepId, Vec<compat_types::StepId>>, KernelError>
{
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_seq_named_step_id(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(StepId, Seq(StepId))",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_dependency_mode(value: &compat_types::DependencyMode) -> KernelValue {
    let variant = match value {
        compat_types::DependencyMode::All => "All",
        compat_types::DependencyMode::Any => "Any",
    };
    KernelValue::NamedVariant {
        enum_name: "DependencyMode".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_dependency_mode(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::DependencyMode, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "DependencyMode" => {
            match variant.as_str() {
                "All" => Ok(compat_types::DependencyMode::All),
                "Any" => Ok(compat_types::DependencyMode::Any),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected DependencyMode variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "DependencyMode", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_enum_dependency_mode(
    value: &std::collections::BTreeMap<compat_types::StepId, compat_types::DependencyMode>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_enum_dependency_mode(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_enum_dependency_mode(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::StepId, compat_types::DependencyMode>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_enum_dependency_mode(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(StepId, DependencyMode)",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_branch_id(value: &compat_types::BranchId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::BranchId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::BranchId(value)),
        other => Err(kernel_type_error(context, "BranchId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_option_named_branch_id(value: &Option<compat_types::BranchId>) -> KernelValue {
    match value {
        Some(inner) => kernel_option_some(value_to_kernel_named_branch_id(inner)),
        None => KernelValue::None,
    }
}

#[allow(dead_code)]
fn value_from_kernel_option_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<Option<compat_types::BranchId>, KernelError> {
    match value {
        KernelValue::None => Ok(None),
        KernelValue::Map(mut entries) => {
            if let Some(inner) = entries.remove(&KernelValue::String("value".to_string())) {
                Ok(Some(value_from_kernel_named_branch_id(inner, context)?))
            } else {
                Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected option value payload"),
                })
            }
        }
        other => Ok(Some(value_from_kernel_named_branch_id(other, context)?)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_option_named_branch_id(
    value: &std::collections::BTreeMap<compat_types::StepId, Option<compat_types::BranchId>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_option_named_branch_id(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_option_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::StepId, Option<compat_types::BranchId>>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_option_named_branch_id(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(StepId, Option(BranchId))",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_collection_policy_kind(
    value: &compat_types::CollectionPolicyKind,
) -> KernelValue {
    let variant = match value {
        compat_types::CollectionPolicyKind::All => "All",
        compat_types::CollectionPolicyKind::Any => "Any",
        compat_types::CollectionPolicyKind::Quorum => "Quorum",
    };
    KernelValue::NamedVariant {
        enum_name: "CollectionPolicyKind".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_collection_policy_kind(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::CollectionPolicyKind, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "CollectionPolicyKind" => {
            match variant.as_str() {
                "All" => Ok(compat_types::CollectionPolicyKind::All),
                "Any" => Ok(compat_types::CollectionPolicyKind::Any),
                "Quorum" => Ok(compat_types::CollectionPolicyKind::Quorum),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!(
                        "{context} expected CollectionPolicyKind variant, found `{other}`"
                    ),
                }),
            }
        }
        other => Err(kernel_type_error(context, "CollectionPolicyKind", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_enum_collection_policy_kind(
    value: &std::collections::BTreeMap<compat_types::StepId, compat_types::CollectionPolicyKind>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_enum_collection_policy_kind(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_enum_collection_policy_kind(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::StepId, compat_types::CollectionPolicyKind>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_enum_collection_policy_kind(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(StepId, CollectionPolicyKind)",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_u32(value: &u32) -> KernelValue {
    KernelValue::U64(u64::from(*value))
}

#[allow(dead_code)]
fn value_from_kernel_u32(value: KernelValue, context: &str) -> Result<u32, KernelError> {
    match value {
        KernelValue::U64(value) => {
            u32::try_from(value).map_err(|_| KernelError::CodegenInvariant {
                detail: format!("{context} expected u32-compatible value, found {value}"),
            })
        }
        other => Err(kernel_type_error(context, "u32", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_step_id_u32(
    value: &std::collections::BTreeMap<compat_types::StepId, u32>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_step_id(key),
                    value_to_kernel_u32(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_step_id_u32(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<compat_types::StepId, u32>, KernelError> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_step_id(key, context)?,
                    value_from_kernel_u32(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Map(StepId, u32)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_string(value: &String) -> KernelValue {
    KernelValue::String(value.clone())
}

#[allow(dead_code)]
fn value_from_kernel_string(value: KernelValue, context: &str) -> Result<String, KernelError> {
    match value {
        KernelValue::String(value) => Ok(value),
        other => Err(kernel_type_error(context, "string", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_string_u32(value: &std::collections::BTreeMap<String, u32>) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| (value_to_kernel_string(key), value_to_kernel_u32(value)))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_string_u32(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<String, u32>, KernelError> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_string(key, context)?,
                    value_from_kernel_u32(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Map(string, u32)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_frame_id(value: &compat_types::FrameId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_frame_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FrameId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::FrameId(value)),
        other => Err(kernel_type_error(context, "FrameId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_seq_named_frame_id(value: &Vec<compat_types::FrameId>) -> KernelValue {
    KernelValue::Seq(
        value
            .iter()
            .map(|item| value_to_kernel_named_frame_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_seq_named_frame_id(
    value: KernelValue,
    context: &str,
) -> Result<Vec<compat_types::FrameId>, KernelError> {
    match value {
        KernelValue::Seq(values) => {
            let mut out = Vec::new();
            for value in values {
                out.push(value_from_kernel_named_frame_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Seq(FrameId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_set_named_frame_id(
    value: &std::collections::BTreeSet<compat_types::FrameId>,
) -> KernelValue {
    KernelValue::Set(
        value
            .iter()
            .map(|item| value_to_kernel_named_frame_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_set_named_frame_id(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeSet<compat_types::FrameId>, KernelError> {
    match value {
        KernelValue::Set(values) => {
            let mut out = std::collections::BTreeSet::new();
            for value in values {
                out.insert(value_from_kernel_named_frame_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Set(FrameId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_loop_instance_id(value: &compat_types::LoopInstanceId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_loop_instance_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::LoopInstanceId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::LoopInstanceId(value)),
        other => Err(kernel_type_error(context, "LoopInstanceId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_seq_named_loop_instance_id(
    value: &Vec<compat_types::LoopInstanceId>,
) -> KernelValue {
    KernelValue::Seq(
        value
            .iter()
            .map(|item| value_to_kernel_named_loop_instance_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_seq_named_loop_instance_id(
    value: KernelValue,
    context: &str,
) -> Result<Vec<compat_types::LoopInstanceId>, KernelError> {
    match value {
        KernelValue::Seq(values) => {
            let mut out = Vec::new();
            for value in values {
                out.push(value_from_kernel_named_loop_instance_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Seq(LoopInstanceId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_set_named_loop_instance_id(
    value: &std::collections::BTreeSet<compat_types::LoopInstanceId>,
) -> KernelValue {
    KernelValue::Set(
        value
            .iter()
            .map(|item| value_to_kernel_named_loop_instance_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_set_named_loop_instance_id(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeSet<compat_types::LoopInstanceId>, KernelError> {
    match value {
        KernelValue::Set(values) => {
            let mut out = std::collections::BTreeSet::new();
            for value in values {
                out.insert(value_from_kernel_named_loop_instance_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Set(LoopInstanceId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_meerkat_id(value: &compat_types::MeerkatId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_meerkat_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::MeerkatId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::MeerkatId(value)),
        other => Err(kernel_type_error(context, "MeerkatId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_flow_run_status(value: &compat_types::FlowRunStatus) -> KernelValue {
    let variant = match value {
        compat_types::FlowRunStatus::Absent => "Absent",
        compat_types::FlowRunStatus::Pending => "Pending",
        compat_types::FlowRunStatus::Running => "Running",
        compat_types::FlowRunStatus::Completed => "Completed",
        compat_types::FlowRunStatus::Failed => "Failed",
        compat_types::FlowRunStatus::Canceled => "Canceled",
    };
    KernelValue::NamedVariant {
        enum_name: "FlowRunStatus".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_flow_run_status(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FlowRunStatus, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "FlowRunStatus" => {
            match variant.as_str() {
                "Absent" => Ok(compat_types::FlowRunStatus::Absent),
                "Pending" => Ok(compat_types::FlowRunStatus::Pending),
                "Running" => Ok(compat_types::FlowRunStatus::Running),
                "Completed" => Ok(compat_types::FlowRunStatus::Completed),
                "Failed" => Ok(compat_types::FlowRunStatus::Failed),
                "Canceled" => Ok(compat_types::FlowRunStatus::Canceled),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected FlowRunStatus variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "FlowRunStatus", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_seq_option_enum_step_run_status(
    value: &Vec<Option<compat_types::StepRunStatus>>,
) -> KernelValue {
    KernelValue::Seq(
        value
            .iter()
            .map(|item| value_to_kernel_option_enum_step_run_status(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_seq_option_enum_step_run_status(
    value: KernelValue,
    context: &str,
) -> Result<Vec<Option<compat_types::StepRunStatus>>, KernelError> {
    match value {
        KernelValue::Seq(values) => {
            let mut out = Vec::new();
            for value in values {
                out.push(value_from_kernel_option_enum_step_run_status(
                    value, context,
                )?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Seq(Option(StepRunStatus))",
            &other,
        )),
    }
}
