// Generated by `cargo xtask machine-codegen --all`.
#![allow(
    clippy::expect_used,
    clippy::ptr_arg,
    clippy::redundant_clone,
    clippy::redundant_closure,
    clippy::uninlined_format_args,
    dead_code
)]
use crate::compat_generated::flow_frame::{Effect, KernelError, Phase, State};
use crate::runtime::{KernelEffect as LegacyEffect, KernelState as LegacyState, KernelValue};
use meerkat_machine_schema::compat::types as compat_types;

#[cfg(feature = "test-oracle")]
fn effect_to_kernel(effect: &Effect) -> LegacyEffect {
    match effect {
        Effect::ReadyFrontierChanged(payload) => LegacyEffect {
            variant: "ReadyFrontierChanged".to_string(),
            fields: std::collections::BTreeMap::from([(
                "frame_id".to_string(),
                value_to_kernel_named_frame_id(&payload.frame_id),
            )]),
        },
        Effect::AdmitStepWork(payload) => LegacyEffect {
            variant: "AdmitStepWork".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.node_id),
                ),
            ]),
        },
        Effect::StartLoopNode(payload) => LegacyEffect {
            variant: "StartLoopNode".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.node_id),
                ),
            ]),
        },
        Effect::PersistStepOutput(payload) => LegacyEffect {
            variant: "PersistStepOutput".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.node_id),
                ),
            ]),
        },
        Effect::NodeExecutionReleased(payload) => LegacyEffect {
            variant: "NodeExecutionReleased".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.node_id),
                ),
            ]),
        },
        Effect::RootFrameCompleted(payload) => LegacyEffect {
            variant: "RootFrameCompleted".to_string(),
            fields: std::collections::BTreeMap::from([(
                "frame_id".to_string(),
                value_to_kernel_named_frame_id(&payload.frame_id),
            )]),
        },
        Effect::RootFrameFailed(payload) => LegacyEffect {
            variant: "RootFrameFailed".to_string(),
            fields: std::collections::BTreeMap::from([(
                "frame_id".to_string(),
                value_to_kernel_named_frame_id(&payload.frame_id),
            )]),
        },
        Effect::RootFrameCanceled(payload) => LegacyEffect {
            variant: "RootFrameCanceled".to_string(),
            fields: std::collections::BTreeMap::from([(
                "frame_id".to_string(),
                value_to_kernel_named_frame_id(&payload.frame_id),
            )]),
        },
        Effect::BodyFrameCompleted(payload) => LegacyEffect {
            variant: "BodyFrameCompleted".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "iteration".to_string(),
                    value_to_kernel_u32(&payload.iteration),
                ),
            ]),
        },
        Effect::BodyFrameFailed(payload) => LegacyEffect {
            variant: "BodyFrameFailed".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "iteration".to_string(),
                    value_to_kernel_u32(&payload.iteration),
                ),
            ]),
        },
        Effect::BodyFrameCanceled(payload) => LegacyEffect {
            variant: "BodyFrameCanceled".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.frame_id),
                ),
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "iteration".to_string(),
                    value_to_kernel_u32(&payload.iteration),
                ),
            ]),
        },
    }
}

#[cfg(feature = "test-oracle")]
pub fn to_test_oracle_effect(effect: &Effect) -> crate::test_oracle::KernelEffect {
    effect_to_kernel(effect)
}

fn state_to_kernel(state: &State) -> LegacyState {
    LegacyState {
        phase: phase_to_string(&state.phase).to_string(),
        fields: std::collections::BTreeMap::from([
            (
                "frame_id".to_string(),
                value_to_kernel_named_frame_id(&state.frame_id),
            ),
            (
                "frame_scope".to_string(),
                value_to_kernel_enum_frame_scope(&state.frame_scope),
            ),
            (
                "loop_instance_id".to_string(),
                value_to_kernel_named_loop_instance_id(&state.loop_instance_id),
            ),
            (
                "iteration".to_string(),
                value_to_kernel_u32(&state.iteration),
            ),
            (
                "last_admitted_node".to_string(),
                value_to_kernel_named_flow_node_id(&state.last_admitted_node),
            ),
            (
                "tracked_nodes".to_string(),
                value_to_kernel_set_named_flow_node_id(&state.tracked_nodes),
            ),
            (
                "ordered_nodes".to_string(),
                value_to_kernel_seq_named_flow_node_id(&state.ordered_nodes),
            ),
            (
                "node_kind".to_string(),
                value_to_kernel_map_named_flow_node_id_enum_flow_node_kind(&state.node_kind),
            ),
            (
                "node_dependencies".to_string(),
                value_to_kernel_map_named_flow_node_id_seq_named_flow_node_id(
                    &state.node_dependencies,
                ),
            ),
            (
                "node_dependency_modes".to_string(),
                value_to_kernel_map_named_flow_node_id_enum_dependency_mode(
                    &state.node_dependency_modes,
                ),
            ),
            (
                "node_branches".to_string(),
                value_to_kernel_map_named_flow_node_id_option_named_branch_id(&state.node_branches),
            ),
            (
                "branch_winners".to_string(),
                value_to_kernel_set_option_named_branch_id(&state.branch_winners),
            ),
            (
                "node_status".to_string(),
                value_to_kernel_map_named_flow_node_id_enum_node_run_status(&state.node_status),
            ),
            (
                "ready_queue".to_string(),
                value_to_kernel_seq_named_flow_node_id(&state.ready_queue),
            ),
            (
                "output_recorded".to_string(),
                value_to_kernel_map_named_flow_node_id_bool(&state.output_recorded),
            ),
            (
                "node_condition_results".to_string(),
                value_to_kernel_map_named_flow_node_id_option_bool(&state.node_condition_results),
            ),
        ]),
    }
}

fn state_from_kernel(state: LegacyState) -> Result<State, KernelError> {
    let mut fields = state.fields;
    Ok(State {
        phase: phase_from_string(&state.phase)?,
        frame_id: value_from_kernel_named_frame_id(
            take_field(&mut fields, "state", "frame_id")?,
            "state field `frame_id`",
        )?,
        frame_scope: value_from_kernel_enum_frame_scope(
            take_field(&mut fields, "state", "frame_scope")?,
            "state field `frame_scope`",
        )?,
        loop_instance_id: value_from_kernel_named_loop_instance_id(
            take_field(&mut fields, "state", "loop_instance_id")?,
            "state field `loop_instance_id`",
        )?,
        iteration: value_from_kernel_u32(
            take_field(&mut fields, "state", "iteration")?,
            "state field `iteration`",
        )?,
        last_admitted_node: value_from_kernel_named_flow_node_id(
            take_field(&mut fields, "state", "last_admitted_node")?,
            "state field `last_admitted_node`",
        )?,
        tracked_nodes: value_from_kernel_set_named_flow_node_id(
            take_field(&mut fields, "state", "tracked_nodes")?,
            "state field `tracked_nodes`",
        )?,
        ordered_nodes: value_from_kernel_seq_named_flow_node_id(
            take_field(&mut fields, "state", "ordered_nodes")?,
            "state field `ordered_nodes`",
        )?,
        node_kind: value_from_kernel_map_named_flow_node_id_enum_flow_node_kind(
            take_field(&mut fields, "state", "node_kind")?,
            "state field `node_kind`",
        )?,
        node_dependencies: value_from_kernel_map_named_flow_node_id_seq_named_flow_node_id(
            take_field(&mut fields, "state", "node_dependencies")?,
            "state field `node_dependencies`",
        )?,
        node_dependency_modes: value_from_kernel_map_named_flow_node_id_enum_dependency_mode(
            take_field(&mut fields, "state", "node_dependency_modes")?,
            "state field `node_dependency_modes`",
        )?,
        node_branches: value_from_kernel_map_named_flow_node_id_option_named_branch_id(
            take_field(&mut fields, "state", "node_branches")?,
            "state field `node_branches`",
        )?,
        branch_winners: value_from_kernel_set_option_named_branch_id(
            take_field(&mut fields, "state", "branch_winners")?,
            "state field `branch_winners`",
        )?,
        node_status: value_from_kernel_map_named_flow_node_id_enum_node_run_status(
            take_field(&mut fields, "state", "node_status")?,
            "state field `node_status`",
        )?,
        ready_queue: value_from_kernel_seq_named_flow_node_id(
            take_field(&mut fields, "state", "ready_queue")?,
            "state field `ready_queue`",
        )?,
        output_recorded: value_from_kernel_map_named_flow_node_id_bool(
            take_field(&mut fields, "state", "output_recorded")?,
            "state field `output_recorded`",
        )?,
        node_condition_results: value_from_kernel_map_named_flow_node_id_option_bool(
            take_field(&mut fields, "state", "node_condition_results")?,
            "state field `node_condition_results`",
        )?,
    })
}

#[cfg(feature = "test-oracle")]
pub fn from_test_oracle_state(
    state: crate::test_oracle::KernelState,
) -> Result<State, KernelError> {
    state_from_kernel(state)
}

#[cfg(feature = "test-oracle")]
pub fn to_test_oracle_state(state: &State) -> crate::test_oracle::KernelState {
    state_to_kernel(state)
}

fn phase_to_string(phase: &Phase) -> &'static str {
    match phase {
        Phase::Absent => "Absent",
        Phase::Running => "Running",
        Phase::Completed => "Completed",
        Phase::Failed => "Failed",
        Phase::Canceled => "Canceled",
    }
}

fn phase_from_string(phase: &str) -> Result<Phase, KernelError> {
    match phase {
        "Absent" => Ok(Phase::Absent),
        "Running" => Ok(Phase::Running),
        "Completed" => Ok(Phase::Completed),
        "Failed" => Ok(Phase::Failed),
        "Canceled" => Ok(Phase::Canceled),
        other => Err(KernelError::CodegenInvariant {
            detail: format!("unknown phase `{other}`"),
        }),
    }
}

fn take_field(
    fields: &mut std::collections::BTreeMap<String, KernelValue>,
    container: &str,
    field: &str,
) -> Result<KernelValue, KernelError> {
    fields
        .remove(field)
        .ok_or_else(|| KernelError::CodegenInvariant {
            detail: format!("{container} missing field `{field}`"),
        })
}

fn kernel_option_some(value: KernelValue) -> KernelValue {
    KernelValue::Map(std::collections::BTreeMap::from([(
        KernelValue::String("value".to_string()),
        value,
    )]))
}

fn kernel_type_error(context: &str, expected: &str, value: &KernelValue) -> KernelError {
    KernelError::CodegenInvariant {
        detail: format!("{context} expected {expected}, found {value:?}"),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_frame_id(value: &compat_types::FrameId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_frame_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FrameId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::FrameId(value)),
        other => Err(kernel_type_error(context, "FrameId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_frame_scope(value: &compat_types::FrameScope) -> KernelValue {
    let variant = match value {
        compat_types::FrameScope::Root => "Root",
        compat_types::FrameScope::Body => "Body",
    };
    KernelValue::NamedVariant {
        enum_name: "FrameScope".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_frame_scope(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FrameScope, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "FrameScope" => {
            match variant.as_str() {
                "Root" => Ok(compat_types::FrameScope::Root),
                "Body" => Ok(compat_types::FrameScope::Body),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected FrameScope variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "FrameScope", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_loop_instance_id(value: &compat_types::LoopInstanceId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_loop_instance_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::LoopInstanceId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::LoopInstanceId(value)),
        other => Err(kernel_type_error(context, "LoopInstanceId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_u32(value: &u32) -> KernelValue {
    KernelValue::U64(u64::from(*value))
}

#[allow(dead_code)]
fn value_from_kernel_u32(value: KernelValue, context: &str) -> Result<u32, KernelError> {
    match value {
        KernelValue::U64(value) => {
            u32::try_from(value).map_err(|_| KernelError::CodegenInvariant {
                detail: format!("{context} expected u32-compatible value, found {value}"),
            })
        }
        other => Err(kernel_type_error(context, "u32", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_flow_node_id(value: &compat_types::FlowNodeId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_flow_node_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FlowNodeId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::FlowNodeId(value)),
        other => Err(kernel_type_error(context, "FlowNodeId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_set_named_flow_node_id(
    value: &std::collections::BTreeSet<compat_types::FlowNodeId>,
) -> KernelValue {
    KernelValue::Set(
        value
            .iter()
            .map(|item| value_to_kernel_named_flow_node_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_set_named_flow_node_id(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeSet<compat_types::FlowNodeId>, KernelError> {
    match value {
        KernelValue::Set(values) => {
            let mut out = std::collections::BTreeSet::new();
            for value in values {
                out.insert(value_from_kernel_named_flow_node_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Set(FlowNodeId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_seq_named_flow_node_id(value: &Vec<compat_types::FlowNodeId>) -> KernelValue {
    KernelValue::Seq(
        value
            .iter()
            .map(|item| value_to_kernel_named_flow_node_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_seq_named_flow_node_id(
    value: KernelValue,
    context: &str,
) -> Result<Vec<compat_types::FlowNodeId>, KernelError> {
    match value {
        KernelValue::Seq(values) => {
            let mut out = Vec::new();
            for value in values {
                out.push(value_from_kernel_named_flow_node_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Seq(FlowNodeId)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_flow_node_kind(value: &compat_types::FlowNodeKind) -> KernelValue {
    let variant = match value {
        compat_types::FlowNodeKind::Step => "Step",
        compat_types::FlowNodeKind::Loop => "Loop",
    };
    KernelValue::NamedVariant {
        enum_name: "FlowNodeKind".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_flow_node_kind(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FlowNodeKind, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "FlowNodeKind" => {
            match variant.as_str() {
                "Step" => Ok(compat_types::FlowNodeKind::Step),
                "Loop" => Ok(compat_types::FlowNodeKind::Loop),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected FlowNodeKind variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "FlowNodeKind", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_enum_flow_node_kind(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, compat_types::FlowNodeKind>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_enum_flow_node_kind(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_enum_flow_node_kind(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::FlowNodeId, compat_types::FlowNodeKind>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_enum_flow_node_kind(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(FlowNodeId, FlowNodeKind)",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_seq_named_flow_node_id(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, Vec<compat_types::FlowNodeId>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_seq_named_flow_node_id(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_seq_named_flow_node_id(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::FlowNodeId, Vec<compat_types::FlowNodeId>>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_seq_named_flow_node_id(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(FlowNodeId, Seq(FlowNodeId))",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_dependency_mode(value: &compat_types::DependencyMode) -> KernelValue {
    let variant = match value {
        compat_types::DependencyMode::All => "All",
        compat_types::DependencyMode::Any => "Any",
    };
    KernelValue::NamedVariant {
        enum_name: "DependencyMode".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_dependency_mode(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::DependencyMode, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "DependencyMode" => {
            match variant.as_str() {
                "All" => Ok(compat_types::DependencyMode::All),
                "Any" => Ok(compat_types::DependencyMode::Any),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected DependencyMode variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "DependencyMode", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_enum_dependency_mode(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, compat_types::DependencyMode>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_enum_dependency_mode(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_enum_dependency_mode(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::FlowNodeId, compat_types::DependencyMode>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_enum_dependency_mode(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(FlowNodeId, DependencyMode)",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_branch_id(value: &compat_types::BranchId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::BranchId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::BranchId(value)),
        other => Err(kernel_type_error(context, "BranchId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_option_named_branch_id(value: &Option<compat_types::BranchId>) -> KernelValue {
    match value {
        Some(inner) => kernel_option_some(value_to_kernel_named_branch_id(inner)),
        None => KernelValue::None,
    }
}

#[allow(dead_code)]
fn value_from_kernel_option_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<Option<compat_types::BranchId>, KernelError> {
    match value {
        KernelValue::None => Ok(None),
        KernelValue::Map(mut entries) => {
            if let Some(inner) = entries.remove(&KernelValue::String("value".to_string())) {
                Ok(Some(value_from_kernel_named_branch_id(inner, context)?))
            } else {
                Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected option value payload"),
                })
            }
        }
        other => Ok(Some(value_from_kernel_named_branch_id(other, context)?)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_option_named_branch_id(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, Option<compat_types::BranchId>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_option_named_branch_id(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_option_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::FlowNodeId, Option<compat_types::BranchId>>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_option_named_branch_id(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(FlowNodeId, Option(BranchId))",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_set_option_named_branch_id(
    value: &std::collections::BTreeSet<Option<compat_types::BranchId>>,
) -> KernelValue {
    KernelValue::Set(
        value
            .iter()
            .map(|item| value_to_kernel_option_named_branch_id(item))
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_set_option_named_branch_id(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeSet<Option<compat_types::BranchId>>, KernelError> {
    match value {
        KernelValue::Set(values) => {
            let mut out = std::collections::BTreeSet::new();
            for value in values {
                out.insert(value_from_kernel_option_named_branch_id(value, context)?);
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Set(Option(BranchId))", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_node_run_status(value: &compat_types::NodeRunStatus) -> KernelValue {
    let variant = match value {
        compat_types::NodeRunStatus::Pending => "Pending",
        compat_types::NodeRunStatus::Ready => "Ready",
        compat_types::NodeRunStatus::Running => "Running",
        compat_types::NodeRunStatus::Completed => "Completed",
        compat_types::NodeRunStatus::Failed => "Failed",
        compat_types::NodeRunStatus::Skipped => "Skipped",
        compat_types::NodeRunStatus::Canceled => "Canceled",
    };
    KernelValue::NamedVariant {
        enum_name: "NodeRunStatus".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_node_run_status(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::NodeRunStatus, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "NodeRunStatus" => {
            match variant.as_str() {
                "Pending" => Ok(compat_types::NodeRunStatus::Pending),
                "Ready" => Ok(compat_types::NodeRunStatus::Ready),
                "Running" => Ok(compat_types::NodeRunStatus::Running),
                "Completed" => Ok(compat_types::NodeRunStatus::Completed),
                "Failed" => Ok(compat_types::NodeRunStatus::Failed),
                "Skipped" => Ok(compat_types::NodeRunStatus::Skipped),
                "Canceled" => Ok(compat_types::NodeRunStatus::Canceled),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected NodeRunStatus variant, found `{other}`"),
                }),
            }
        }
        other => Err(kernel_type_error(context, "NodeRunStatus", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_enum_node_run_status(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, compat_types::NodeRunStatus>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_enum_node_run_status(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_enum_node_run_status(
    value: KernelValue,
    context: &str,
) -> Result<
    std::collections::BTreeMap<compat_types::FlowNodeId, compat_types::NodeRunStatus>,
    KernelError,
> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_enum_node_run_status(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(FlowNodeId, NodeRunStatus)",
            &other,
        )),
    }
}

#[allow(dead_code)]
fn value_to_kernel_bool(value: &bool) -> KernelValue {
    KernelValue::Bool(*value)
}

#[allow(dead_code)]
fn value_from_kernel_bool(value: KernelValue, context: &str) -> Result<bool, KernelError> {
    match value {
        KernelValue::Bool(value) => Ok(value),
        other => Err(kernel_type_error(context, "bool", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_bool(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, bool>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_bool(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_bool(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<compat_types::FlowNodeId, bool>, KernelError> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_bool(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(context, "Map(FlowNodeId, bool)", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_option_bool(value: &Option<bool>) -> KernelValue {
    match value {
        Some(inner) => kernel_option_some(value_to_kernel_bool(inner)),
        None => KernelValue::None,
    }
}

#[allow(dead_code)]
fn value_from_kernel_option_bool(
    value: KernelValue,
    context: &str,
) -> Result<Option<bool>, KernelError> {
    match value {
        KernelValue::None => Ok(None),
        KernelValue::Map(mut entries) => {
            if let Some(inner) = entries.remove(&KernelValue::String("value".to_string())) {
                Ok(Some(value_from_kernel_bool(inner, context)?))
            } else {
                Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected option value payload"),
                })
            }
        }
        other => Ok(Some(value_from_kernel_bool(other, context)?)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_map_named_flow_node_id_option_bool(
    value: &std::collections::BTreeMap<compat_types::FlowNodeId, Option<bool>>,
) -> KernelValue {
    KernelValue::Map(
        value
            .iter()
            .map(|(key, value)| {
                (
                    value_to_kernel_named_flow_node_id(key),
                    value_to_kernel_option_bool(value),
                )
            })
            .collect(),
    )
}

#[allow(dead_code)]
fn value_from_kernel_map_named_flow_node_id_option_bool(
    value: KernelValue,
    context: &str,
) -> Result<std::collections::BTreeMap<compat_types::FlowNodeId, Option<bool>>, KernelError> {
    match value {
        KernelValue::Map(values) => {
            let mut out = std::collections::BTreeMap::new();
            for (key, value) in values {
                out.insert(
                    value_from_kernel_named_flow_node_id(key, context)?,
                    value_from_kernel_option_bool(value, context)?,
                );
            }
            Ok(out)
        }
        other => Err(kernel_type_error(
            context,
            "Map(FlowNodeId, Option(bool))",
            &other,
        )),
    }
}
