// Generated by `cargo xtask machine-codegen --all`.
#![allow(
    clippy::expect_used,
    clippy::ptr_arg,
    clippy::redundant_clone,
    clippy::redundant_closure,
    clippy::uninlined_format_args,
    dead_code
)]
use crate::compat_generated::loop_iteration::{Effect, KernelError, Phase, State};
use crate::runtime::{KernelEffect as LegacyEffect, KernelState as LegacyState, KernelValue};
use meerkat_machine_schema::compat::types as compat_types;

#[cfg(feature = "test-oracle")]
fn effect_to_kernel(effect: &Effect) -> LegacyEffect {
    match effect {
        Effect::RequestBodyFrameStart(payload) => LegacyEffect {
            variant: "RequestBodyFrameStart".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                ("depth".to_string(), value_to_kernel_u32(&payload.depth)),
            ]),
        },
        Effect::EvaluateUntilCondition(payload) => LegacyEffect {
            variant: "EvaluateUntilCondition".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "iteration".to_string(),
                    value_to_kernel_u32(&payload.iteration),
                ),
                (
                    "parent_frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.parent_frame_id),
                ),
                (
                    "parent_node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.parent_node_id),
                ),
                (
                    "loop_id".to_string(),
                    value_to_kernel_named_loop_id(&payload.loop_id),
                ),
            ]),
        },
        Effect::LoopCompleted(payload) => LegacyEffect {
            variant: "LoopCompleted".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "parent_frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.parent_frame_id),
                ),
                (
                    "parent_node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.parent_node_id),
                ),
            ]),
        },
        Effect::LoopExhausted(payload) => LegacyEffect {
            variant: "LoopExhausted".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "parent_frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.parent_frame_id),
                ),
                (
                    "parent_node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.parent_node_id),
                ),
            ]),
        },
        Effect::LoopFailed(payload) => LegacyEffect {
            variant: "LoopFailed".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "parent_frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.parent_frame_id),
                ),
                (
                    "parent_node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.parent_node_id),
                ),
            ]),
        },
        Effect::LoopCanceled(payload) => LegacyEffect {
            variant: "LoopCanceled".to_string(),
            fields: std::collections::BTreeMap::from([
                (
                    "loop_instance_id".to_string(),
                    value_to_kernel_named_loop_instance_id(&payload.loop_instance_id),
                ),
                (
                    "parent_frame_id".to_string(),
                    value_to_kernel_named_frame_id(&payload.parent_frame_id),
                ),
                (
                    "parent_node_id".to_string(),
                    value_to_kernel_named_flow_node_id(&payload.parent_node_id),
                ),
            ]),
        },
    }
}

#[cfg(feature = "test-oracle")]
pub fn to_test_oracle_effect(effect: &Effect) -> crate::test_oracle::KernelEffect {
    effect_to_kernel(effect)
}

fn state_to_kernel(state: &State) -> LegacyState {
    LegacyState {
        phase: phase_to_string(&state.phase).to_string(),
        fields: std::collections::BTreeMap::from([
            (
                "loop_instance_id".to_string(),
                value_to_kernel_named_loop_instance_id(&state.loop_instance_id),
            ),
            (
                "parent_frame_id".to_string(),
                value_to_kernel_named_frame_id(&state.parent_frame_id),
            ),
            (
                "parent_node_id".to_string(),
                value_to_kernel_named_flow_node_id(&state.parent_node_id),
            ),
            (
                "loop_id".to_string(),
                value_to_kernel_named_loop_id(&state.loop_id),
            ),
            ("depth".to_string(), value_to_kernel_u32(&state.depth)),
            (
                "stage".to_string(),
                value_to_kernel_enum_loop_iteration_stage(&state.stage),
            ),
            (
                "current_iteration".to_string(),
                value_to_kernel_u32(&state.current_iteration),
            ),
            (
                "last_completed_iteration".to_string(),
                value_to_kernel_u32(&state.last_completed_iteration),
            ),
            (
                "max_iterations".to_string(),
                value_to_kernel_u32(&state.max_iterations),
            ),
            (
                "active_body_frame_id".to_string(),
                value_to_kernel_option_named_frame_id(&state.active_body_frame_id),
            ),
        ]),
    }
}

fn state_from_kernel(state: LegacyState) -> Result<State, KernelError> {
    let mut fields = state.fields;
    Ok(State {
        phase: phase_from_string(&state.phase)?,
        loop_instance_id: value_from_kernel_named_loop_instance_id(
            take_field(&mut fields, "state", "loop_instance_id")?,
            "state field `loop_instance_id`",
        )?,
        parent_frame_id: value_from_kernel_named_frame_id(
            take_field(&mut fields, "state", "parent_frame_id")?,
            "state field `parent_frame_id`",
        )?,
        parent_node_id: value_from_kernel_named_flow_node_id(
            take_field(&mut fields, "state", "parent_node_id")?,
            "state field `parent_node_id`",
        )?,
        loop_id: value_from_kernel_named_loop_id(
            take_field(&mut fields, "state", "loop_id")?,
            "state field `loop_id`",
        )?,
        depth: value_from_kernel_u32(
            take_field(&mut fields, "state", "depth")?,
            "state field `depth`",
        )?,
        stage: value_from_kernel_enum_loop_iteration_stage(
            take_field(&mut fields, "state", "stage")?,
            "state field `stage`",
        )?,
        current_iteration: value_from_kernel_u32(
            take_field(&mut fields, "state", "current_iteration")?,
            "state field `current_iteration`",
        )?,
        last_completed_iteration: value_from_kernel_u32(
            take_field(&mut fields, "state", "last_completed_iteration")?,
            "state field `last_completed_iteration`",
        )?,
        max_iterations: value_from_kernel_u32(
            take_field(&mut fields, "state", "max_iterations")?,
            "state field `max_iterations`",
        )?,
        active_body_frame_id: value_from_kernel_option_named_frame_id(
            take_field(&mut fields, "state", "active_body_frame_id")?,
            "state field `active_body_frame_id`",
        )?,
    })
}

#[cfg(feature = "test-oracle")]
pub fn from_test_oracle_state(
    state: crate::test_oracle::KernelState,
) -> Result<State, KernelError> {
    state_from_kernel(state)
}

#[cfg(feature = "test-oracle")]
pub fn to_test_oracle_state(state: &State) -> crate::test_oracle::KernelState {
    state_to_kernel(state)
}

fn phase_to_string(phase: &Phase) -> &'static str {
    match phase {
        Phase::Absent => "Absent",
        Phase::Running => "Running",
        Phase::Completed => "Completed",
        Phase::Exhausted => "Exhausted",
        Phase::Failed => "Failed",
        Phase::Canceled => "Canceled",
    }
}

fn phase_from_string(phase: &str) -> Result<Phase, KernelError> {
    match phase {
        "Absent" => Ok(Phase::Absent),
        "Running" => Ok(Phase::Running),
        "Completed" => Ok(Phase::Completed),
        "Exhausted" => Ok(Phase::Exhausted),
        "Failed" => Ok(Phase::Failed),
        "Canceled" => Ok(Phase::Canceled),
        other => Err(KernelError::CodegenInvariant {
            detail: format!("unknown phase `{other}`"),
        }),
    }
}

fn take_field(
    fields: &mut std::collections::BTreeMap<String, KernelValue>,
    container: &str,
    field: &str,
) -> Result<KernelValue, KernelError> {
    fields
        .remove(field)
        .ok_or_else(|| KernelError::CodegenInvariant {
            detail: format!("{container} missing field `{field}`"),
        })
}

fn kernel_option_some(value: KernelValue) -> KernelValue {
    KernelValue::Map(std::collections::BTreeMap::from([(
        KernelValue::String("value".to_string()),
        value,
    )]))
}

fn kernel_type_error(context: &str, expected: &str, value: &KernelValue) -> KernelError {
    KernelError::CodegenInvariant {
        detail: format!("{context} expected {expected}, found {value:?}"),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_loop_instance_id(value: &compat_types::LoopInstanceId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_loop_instance_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::LoopInstanceId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::LoopInstanceId(value)),
        other => Err(kernel_type_error(context, "LoopInstanceId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_frame_id(value: &compat_types::FrameId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_frame_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FrameId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::FrameId(value)),
        other => Err(kernel_type_error(context, "FrameId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_flow_node_id(value: &compat_types::FlowNodeId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_flow_node_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::FlowNodeId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::FlowNodeId(value)),
        other => Err(kernel_type_error(context, "FlowNodeId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_named_loop_id(value: &compat_types::LoopId) -> KernelValue {
    KernelValue::String(value.to_string())
}

#[allow(dead_code)]
fn value_from_kernel_named_loop_id(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::LoopId, KernelError> {
    match value {
        KernelValue::String(value) => Ok(compat_types::LoopId(value)),
        other => Err(kernel_type_error(context, "LoopId", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_u32(value: &u32) -> KernelValue {
    KernelValue::U64(u64::from(*value))
}

#[allow(dead_code)]
fn value_from_kernel_u32(value: KernelValue, context: &str) -> Result<u32, KernelError> {
    match value {
        KernelValue::U64(value) => {
            u32::try_from(value).map_err(|_| KernelError::CodegenInvariant {
                detail: format!("{context} expected u32-compatible value, found {value}"),
            })
        }
        other => Err(kernel_type_error(context, "u32", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_enum_loop_iteration_stage(
    value: &compat_types::LoopIterationStage,
) -> KernelValue {
    let variant = match value {
        compat_types::LoopIterationStage::AwaitingBodyFrame => "AwaitingBodyFrame",
        compat_types::LoopIterationStage::BodyFrameActive => "BodyFrameActive",
        compat_types::LoopIterationStage::AwaitingUntil => "AwaitingUntil",
    };
    KernelValue::NamedVariant {
        enum_name: "LoopIterationStage".to_string(),
        variant: variant.to_string(),
    }
}

#[allow(dead_code)]
fn value_from_kernel_enum_loop_iteration_stage(
    value: KernelValue,
    context: &str,
) -> Result<compat_types::LoopIterationStage, KernelError> {
    match value {
        KernelValue::NamedVariant { enum_name, variant } if enum_name == "LoopIterationStage" => {
            match variant.as_str() {
                "AwaitingBodyFrame" => Ok(compat_types::LoopIterationStage::AwaitingBodyFrame),
                "BodyFrameActive" => Ok(compat_types::LoopIterationStage::BodyFrameActive),
                "AwaitingUntil" => Ok(compat_types::LoopIterationStage::AwaitingUntil),
                other => Err(KernelError::CodegenInvariant {
                    detail: format!(
                        "{context} expected LoopIterationStage variant, found `{other}`"
                    ),
                }),
            }
        }
        other => Err(kernel_type_error(context, "LoopIterationStage", &other)),
    }
}

#[allow(dead_code)]
fn value_to_kernel_option_named_frame_id(value: &Option<compat_types::FrameId>) -> KernelValue {
    match value {
        Some(inner) => kernel_option_some(value_to_kernel_named_frame_id(inner)),
        None => KernelValue::None,
    }
}

#[allow(dead_code)]
fn value_from_kernel_option_named_frame_id(
    value: KernelValue,
    context: &str,
) -> Result<Option<compat_types::FrameId>, KernelError> {
    match value {
        KernelValue::None => Ok(None),
        KernelValue::Map(mut entries) => {
            if let Some(inner) = entries.remove(&KernelValue::String("value".to_string())) {
                Ok(Some(value_from_kernel_named_frame_id(inner, context)?))
            } else {
                Err(KernelError::CodegenInvariant {
                    detail: format!("{context} expected option value payload"),
                })
            }
        }
        other => Ok(Some(value_from_kernel_named_frame_id(other, context)?)),
    }
}
