"""Meerkat Python SDK — communicate with the Meerkat agent runtime.

Quick start::

    import asyncio
    from meerkat import MeerkatClient, TextDelta

    async def main():
        async with MeerkatClient() as client:
            session = await client.create_session("Hello, Meerkat!")
            print(session.text)

            async with session.stream("Tell me a joke") as events:
                async for event in events:
                    match event:
                        case TextDelta(delta=chunk):
                            print(chunk, end="", flush=True)
                print()

    asyncio.run(main())
"""

# Core client and session
from .client import MeerkatClient
from .mob import (
    MemberDeliveryReceipt,
    MemberRespawnReceipt,
    Mob,
    MobHelperResult,
    MobKickoffMemberSnapshot,
    MobMemberSnapshot,
    MobPeerConnectivitySnapshot,
    MobRespawnResult,
    MobSpawnSpec,
    MobUnreachablePeer,
)
from .realtime import (
    RealtimeChannel,
    RealtimeConnection,
    RealtimeChannelTarget,
    RealtimeMobMemberTarget,
    RealtimeSessionTarget,
)
from .session import DeferredSession, Session
from .streaming import EventStream, EventSubscription

# Domain types (clean, Wire-free public names)
from .types import (
    BlobImageBlock,
    BlobPayload,
    CatalogModelEntry,
    ContractVersion,
    ConfigEnvelope,
    CONTRACT_VERSION,
    ContentBlock,
    ContentInput,
    DeletedMobProfile,
    ExternalEventOutcome,
    AttributedEvent,
    Capability,
    ModelProfile,
    ModelsCatalogResponse,
    MobEventCursorEntry,
    MobEventsResult,
    MobProfile,
    MobProfileTools,
    EventEnvelope,
    InlineVideoBlock,
    InputListParams,
    InputListResult,
    McpAddParams,
    McpLiveOpResponse,
    McpReloadParams,
    McpRemoveParams,
    RealtimeAudioChunk,
    RealtimeCapabilities,
    RealtimeCapabilitiesParams,
    RealtimeCapabilitiesResult,
    RealtimeChannelClosedFrame,
    RealtimeChannelErrorFrame,
    RealtimeChannelEventFrame,
    RealtimeChannelInputFrame,
    RealtimeChannelOpenFrame,
    RealtimeChannelOpenedFrame,
    RealtimeChannelRole,
    RealtimeChannelState,
    RealtimeChannelStatus,
    RealtimeChannelStatusFrame,
    RealtimeOpenInfo,
    RealtimeOpenRequest,
    RealtimeOutputChunk,
    RealtimeReconnectPolicy,
    RealtimeStatusParams,
    RealtimeStatusResult,
    RealtimeTextChunk,
    RealtimeTextDelta,
    RealtimeTurningMode,
    RealtimeVideoChunk,
    RunResult,
    RuntimeAcceptParams,
    RuntimeAcceptResult,
    RuntimeRealtimeAttachmentStatusResult,
    RuntimeResetParams,
    RuntimeResetResult,
    RuntimeRetireParams,
    RuntimeRetireResult,
    RuntimeStateParams,
    RuntimeStateResult,
    SchemaWarning,
    ScheduleListResult,
    ScheduleOccurrencesResult,
    ScheduleOccurrenceRecord,
    ScheduleRecord,
    ScheduleToolCall,
    ScheduleToolsResult,
    SessionDetails,
    SessionAssistantBlock,
    SessionHistory,
    SessionInfo,
    SessionSummary,
    SessionMessage,
    SessionToolCall,
    SessionToolResult,
    SkillQuarantineDiagnostic,
    SkillRuntimeDiagnostics,
    SkillKey,
    SkillRef,
    SourceHealthSnapshot,
    StoredMobProfile,
    WireInputState,
    Usage,
    InlineImageBlock,
    TextBlock,
)

# Error hierarchy
from .errors import (
    CapabilityUnavailableError,
    MeerkatError,
    SessionNotFoundError,
    SkillNotFoundError,
)

# Typed event hierarchy — every event variant is a frozen dataclass
from .events import (
    BudgetWarning,
    CompactionCompleted,
    CompactionFailed,
    CompactionStarted,
    Event,
    HookCompleted,
    HookDenied,
    HookFailed,
    HookPatchPublished,
    HookRewriteApplied,
    HookStarted,
    InteractionComplete,
    InteractionFailed,
    Retrying,
    RunCompleted,
    RunFailed,
    RunStarted,
    ScopedEvent,
    SkillResolutionFailed,
    SkillsResolved,
    StreamTruncated,
    TextComplete,
    TextDelta,
    ToolConfigChanged,
    ToolConfigChangedPayload,
    ToolCallRequested,
    ToolExecutionCompleted,
    ToolExecutionStarted,
    ToolExecutionTimedOut,
    ToolResultReceived,
    TurnCompleted,
    TurnStarted,
    UnknownEvent,
    parse_event,
)

__all__ = [
    # Client & session
    "MeerkatClient",
    "DeferredSession",
    "Session",
    "Mob",
    "RealtimeChannel",
    "RealtimeConnection",
    "RealtimeChannelTarget",
    "RealtimeSessionTarget",
    "RealtimeMobMemberTarget",
    "MobHelperResult",
    "MobMemberSnapshot",
    "MobKickoffMemberSnapshot",
    "MobRespawnResult",
    "MobSpawnSpec",
    "MemberDeliveryReceipt",
    "MemberRespawnReceipt",
    "MobPeerConnectivitySnapshot",
    "MobUnreachablePeer",
    "EventStream",
    "EventSubscription",
    # Types
    "CONTRACT_VERSION",
    "AttributedEvent",
    "BlobImageBlock",
    "BlobPayload",
    "CatalogModelEntry",
    "ContractVersion",
    "Capability",
    "ConfigEnvelope",
    "ContentBlock",
    "ContentInput",
    "DeletedMobProfile",
    "EventEnvelope",
    "ExternalEventOutcome",
    "InlineVideoBlock",
    "InputListParams",
    "InputListResult",
    "McpAddParams",
    "McpRemoveParams",
    "McpReloadParams",
    "McpLiveOpResponse",
    "RealtimeAudioChunk",
    "RealtimeCapabilities",
    "RealtimeCapabilitiesParams",
    "RealtimeCapabilitiesResult",
    "RealtimeChannelClosedFrame",
    "RealtimeChannelErrorFrame",
    "RealtimeChannelEventFrame",
    "RealtimeChannelInputFrame",
    "RealtimeChannelOpenFrame",
    "RealtimeChannelOpenedFrame",
    "RealtimeChannelRole",
    "RealtimeChannelState",
    "RealtimeChannelStatus",
    "RealtimeChannelStatusFrame",
    "RealtimeOpenInfo",
    "RealtimeOpenRequest",
    "RealtimeOutputChunk",
    "RealtimeReconnectPolicy",
    "RealtimeStatusParams",
    "RealtimeStatusResult",
    "RealtimeTextChunk",
    "RealtimeTextDelta",
    "RealtimeTurningMode",
    "RealtimeVideoChunk",
    "RuntimeAcceptParams",
    "RuntimeAcceptResult",
    "RuntimeRealtimeAttachmentStatusResult",
    "RuntimeResetParams",
    "RuntimeResetResult",
    "RuntimeRetireParams",
    "RuntimeRetireResult",
    "RuntimeStateParams",
    "RuntimeStateResult",
    "RunResult",
    "SchemaWarning",
    "ScheduleListResult",
    "ScheduleOccurrencesResult",
    "ScheduleOccurrenceRecord",
    "ScheduleRecord",
    "ScheduleToolCall",
    "ScheduleToolsResult",
    "SessionDetails",
    "SessionAssistantBlock",
    "SessionHistory",
    "SessionInfo",
    "SessionSummary",
    "SessionMessage",
    "SessionToolCall",
    "SessionToolResult",
    "SkillQuarantineDiagnostic",
    "SkillRuntimeDiagnostics",
    "SkillKey",
    "SkillRef",
    "SourceHealthSnapshot",
    "StoredMobProfile",
    "ModelProfile",
    "ModelsCatalogResponse",
    "MobEventCursorEntry",
    "MobEventsResult",
    "MobProfile",
    "MobProfileTools",
    "WireInputState",
    "Usage",
    "InlineImageBlock",
    "TextBlock",
    # Errors
    "MeerkatError",
    "CapabilityUnavailableError",
    "SessionNotFoundError",
    "SkillNotFoundError",
    # Events (base + all variants)
    "Event",
    "RunStarted",
    "ScopedEvent",
    "RunCompleted",
    "RunFailed",
    "TurnStarted",
    "TextDelta",
    "TextComplete",
    "ToolCallRequested",
    "ToolResultReceived",
    "TurnCompleted",
    "ToolExecutionStarted",
    "ToolExecutionCompleted",
    "ToolExecutionTimedOut",
    "CompactionStarted",
    "CompactionCompleted",
    "CompactionFailed",
    "BudgetWarning",
    "Retrying",
    "HookStarted",
    "HookCompleted",
    "HookFailed",
    "HookDenied",
    "HookRewriteApplied",
    "HookPatchPublished",
    "SkillsResolved",
    "SkillResolutionFailed",
    "InteractionComplete",
    "InteractionFailed",
    "StreamTruncated",
    "ToolConfigChanged",
    "ToolConfigChangedPayload",
    "UnknownEvent",
    "parse_event",
]
