/**
 * Meerkat TypeScript SDK — communicate with the Meerkat agent runtime.
 *
 * @example
 * ```ts
 * import { MeerkatClient } from "@rkat/sdk";
 *
 * const client = new MeerkatClient();
 * await client.connect();
 *
 * const session = await client.createSession("Hello!");
 * console.log(session.text);
 *
 * for await (const event of session.stream("Tell me a joke")) {
 *   if (event.type === "text_delta") {
 *     process.stdout.write(event.delta);
 *   }
 * }
 *
 * await client.close();
 * ```
 */

export { MeerkatClient } from "./client.js";
export type { ConnectOptions } from "./client.js";
export { DeferredSession, Session } from "./session.js";
export type { DeferredTurnOptions } from "./session.js";
export { Mob } from "./mob.js";
export type {
  MobKickoffMemberSnapshot,
  MobKickoffWaitOptions,
  MobReadyMemberSnapshot,
  MobReadyWaitOptions,
} from "./mob.js";
export { EventStream } from "./streaming.js";
export { EventSubscription } from "./subscription.js";
export { RealtimeChannel, RealtimeConnection } from "./realtime.js";
export type {
  RealtimeChannelOptions,
  RealtimeChannelTarget,
  RealtimeSessionTarget,
} from "./realtime.js";

export type {
  AgentEventEnvelope,
  AttributedEvent,
  BlobImageBlock,
  AttributedMobEvent,
  BlobPayload,
  CatalogModel,
  Capability,
  CommsSendReceipt,
  ConfigEnvelope,
  ContractVersion,
  ContentBlock,
  ContentInput,
  CreateScheduleRequest,
  EventEnvelope,
  InlineImageBlock,
  InlineVideoBlock,
  ModelProfile,
  ModelsCatalog,
  MobCreateOptions,
  MobDefinition,
  MobEventsOptions,
  MobEventsResult,
  MobFlowStatus,
  MobLifecycleAction,
  MobMember,
  MobProfile,
  MobProfileBinding,
  MobProfileDeleteResult,
  MobProfileLookupResult,
  MobStatus,
  MobSummary,
  MobTurnStartOptions,
  ModelTier,
  PeerCorrelationId,
  PeerId,
  PeerResponseTerminalOptions,
  ProviderModelCatalog,
  RunResult,
  Schedule,
  ScheduleListOptions,
  ScheduleOccurrencesOptions,
  ScheduleOccurrence,
  ScheduleOccurrencesResult,
  ScheduleToolCallRequest,
  ScheduleToolsResult,
  SchemaWarning,
  SessionAssistantBlock,
  SessionHistory,
  SessionIngressOptions,
  SessionInfo,
  SessionListOptions,
  SessionMessage,
  SessionOptions,
  SessionToolCall,
  SessionToolResult,
  SkillQuarantineDiagnostic,
  SkillRuntimeDiagnostics,
  SkillKey,
  SkillRef,
  SourceHealthSnapshot,
  SpawnManySpec,
  SpawnSpec,
  TurnOptions,
  UpdateSchedulePatch,
  UpdateScheduleRequest,
  Usage,
} from "./types.js";

export {
  MeerkatError,
  CapabilityUnavailableError,
  SessionNotFoundError,
  SkillNotFoundError,
} from "./generated/errors.js";

export type {
  WireAssistantImageRef,
  WireGenerateImageExecutionPlan,
  WireGenerateImageRequest,
  WireImageGenerationToolResult,
  WireImageOperationPhase,
} from "./generated/types.js";

export { CONTRACT_VERSION } from "./generated/types.js";
export type {
  CatalogModelEntry,
  InputListParams,
  InputListResult,
  McpAddParams,
  ModelsCatalogResponse,
  McpRemoveParams,
  McpReloadParams,
  McpLiveOpResponse,
  MobBackendConfigInput,
  MobCreateParams,
  MobCreateResult,
  MobDefinitionInput,
  MobEnsureMemberParams,
  MobEnsureMemberResult,
  MobEventRouterConfigInput,
  MobExternalBackendConfigInput,
  MobFlowNodeInput,
  MobFlowSpecInput,
  MobFlowStepInput,
  MobFrameSpecInput,
  MobLimitsSpecInput,
  MobMcpServerConfigInput,
  MobMemberListEntryWire,
  MobMemberSpecWire,
  MobOrchestratorInput,
  MobProfileBindingInput,
  MobProfileInput,
  MobReconcileParams,
  MobReconcileReportWire,
  MobReconcileResult,
  MobSpawnManyParams,
  MobSpawnManyFailedResult,
  MobSpawnManyResult,
  MobSpawnManyResultEntry,
  MobSpawnManyResultPayload,
  MobSpawnManyResultStatus,
  MobSpawnManySpawnedResult,
  MobSpawnParams,
  MobSpawnPolicyInput,
  MobSpawnReceiptWire,
  MobSpawnSpecParams,
  MobSupervisorSpecInput,
  MobToolConfigInput,
  MobTopologySpecInput,
  MobTurnStartParams,
  MobWiringRulesInput,
  ProviderCatalog,
  RealtimeAudioChunk,
  RealtimeCapabilities,
  RealtimeCapabilitiesParams,
  RealtimeCapabilitiesResult,
  RealtimeChannelClosedFrame,
  RealtimeChannelErrorFrame,
  RealtimeChannelEventFrame,
  RealtimeChannelInputFrame,
  RealtimeChannelOpenFrame,
  RealtimeChannelOpenedFrame,
  RealtimeChannelRole,
  RealtimeChannelState,
  RealtimeChannelStatus,
  RealtimeChannelStatusFrame,
  RealtimeOpenInfo,
  RealtimeOpenRequest,
  RealtimeOutputChunk,
  RealtimeReconnectPolicy,
  RealtimeStatusParams,
  RealtimeStatusResult,
  RealtimeTextChunk,
  RealtimeTextDelta,
  RealtimeTurningMode,
  RealtimeVideoChunk,
  RuntimeAcceptParams,
  RuntimeAcceptResult,
  RuntimeRealtimeAttachmentStatusResult,
  RuntimeResetParams,
  RuntimeResetResult,
  RuntimeRetireParams,
  RuntimeRetireResult,
  RuntimeStateParams,
  RuntimeStateResult,
  WireModelProfile,
  WireModelTier,
  WireSessionInfo,
  WireSessionSummary,
  WireSessionMessage,
  WireToolResultContent,
  WireStopReason,
  WireInputState,
  WireBudgetSplitPolicy,
  WireConnectionRef,
  WireMemberLaunchMode,
  WireMemberRef,
  WireMemberState,
  WireMobBackendKind,
  WireMobMemberStatus,
  WireMobProfile,
  WireMobRuntimeMode,
  WireMobToolConfig,
  WireRuntimeBinding,
  WireToolAccessPolicy,
  WireToolFilter,
} from "./generated/types.js";

export type {
  AgentEvent,
  CoreAgentEvent,
  StreamEvent,
  ScopedAgentEvent,
  StreamScopeFrame,
  RunStartedEvent,
  RunCompletedEvent,
  RunFailedEvent,
  TurnStartedEvent,
  TextDeltaEvent,
  TextCompleteEvent,
  ToolCallRequestedEvent,
  ToolResultReceivedEvent,
  TurnCompletedEvent,
  ToolExecutionStartedEvent,
  ToolExecutionCompletedEvent,
  ToolExecutionTimedOutEvent,
  CompactionStartedEvent,
  CompactionCompletedEvent,
  CompactionFailedEvent,
  BudgetWarningEvent,
  RetryingEvent,
  HookStartedEvent,
  HookCompletedEvent,
  HookFailedEvent,
  HookDeniedEvent,
  HookRewriteAppliedEvent,
  HookPatchPublishedEvent,
  SkillsResolvedEvent,
  SkillResolutionFailedEvent,
  SkillResolutionFailureReason,
  InteractionCompleteEvent,
  InteractionFailedEvent,
  StreamTruncatedEvent,
  ToolConfigChangedEvent,
  ToolConfigChangedPayload,
  ToolConfigChangeOperation,
  ToolConfigChangeStatus,
  BoundaryAppliedToolConfigChangeStatus,
  DeferredCatalogDeltaToolConfigChangeStatus,
  WarningFailedClosedToolConfigChangeStatus,
  ExternalToolDeltaToolConfigChangeStatus,
  ExternalToolDeltaPhase,
  MalformedEvent,
  UnknownEvent,
  AgentErrorClass,
  AgentErrorReason,
  AgentErrorReport,
  StopReason,
  BudgetType,
  HookId,
  HookPoint,
} from "./events.js";

export {
  parseEvent,
  parseCoreEvent,
  isTextDelta,
  isTextComplete,
  isTurnCompleted,
  isToolCallRequested,
  isRunCompleted,
  isRunFailed,
} from "./events.js";
