/**
 * Meerkat TypeScript SDK — communicate with the Meerkat agent runtime.
 *
 * @example
 * ```ts
 * import { MeerkatClient } from "@rkat/sdk";
 *
 * const client = new MeerkatClient();
 * await client.connect();
 *
 * const session = await client.createSession("Hello!");
 * console.log(session.text);
 *
 * for await (const event of session.stream("Tell me a joke")) {
 *   if (event.type === "text_delta") {
 *     process.stdout.write(event.delta);
 *   }
 * }
 *
 * await client.close();
 * ```
 */

export { MeerkatClient } from "./client.js";
export type { ConnectOptions, MobMemberLiveOpenOptions } from "./client.js";
export type { WireMemberProgressSnapshot } from "./generated/types.js";
export { DeferredSession, Session } from "./session.js";
export type { DeferredTurnOptions } from "./session.js";
export { Mob } from "./mob.js";
export type {
  MobHelperResult,
  MobKickoffMemberSnapshot,
  MobKickoffWaitOptions,
  MobMemberSnapshot,
  MobPeerConnectivity,
  MobPeerConnectivitySnapshot,
  MobReadyMemberSnapshot,
  MobReadyWaitOptions,
  MobUnreachablePeer,
} from "./mob.js";
export { LiveChannel } from "./live.js";
export type { LiveChannelOptions } from "./live.js";
export {
  answerLiveWebrtcOffer,
  isLiveWebrtcBootstrap,
  liveWebrtcAudioConstraints,
  liveWebrtcMediaConstraints,
} from "./live_webrtc.js";
export type {
  LiveWebrtcAnswerClient,
  LiveWebrtcAudioConstraintOptions,
  LiveWebrtcOfferDescription,
  LiveWebrtcPeerConnectionLike,
} from "./live_webrtc.js";
export { EventStream } from "./streaming.js";
export { EventSubscription } from "./subscription.js";
export type {
  AgentEventEnvelope,
  AttributedEvent,
  AttributedMobEvent,
  BlobImageBlock,
  BlobPayload,
  BridgeBootstrapToken,
  BridgeCommand,
  BridgeCommandAuthorizeSupervisor,
  BridgeCommandBindHost,
  BridgeCommandBindMember,
  BridgeCommandCancelTrackedMemberInput,
  BridgeCommandCloseMemberLiveChannel,
  BridgeCommandControlMemberLiveChannel,
  BridgeCommandDeclareMemberOutboundTaint,
  BridgeCommandDeliverMemberInput,
  BridgeCommandDestroyMember,
  BridgeCommandHardCancelMember,
  BridgeCommandHostStatus,
  BridgeCommandInstallPeerTrust,
  BridgeCommandInterruptMember,
  BridgeCommandMaterializeMember,
  BridgeCommandMemberLiveChannelStatus,
  BridgeCommandMemberOperatorRequest,
  BridgeCommandObserveMember,
  BridgeCommandOpenMemberLiveChannel,
  BridgeCommandObserveSupervisorRotation,
  BridgeCommandPollMemberEvents,
  BridgeCommandReadMemberHistory,
  BridgeCommandRebindHost,
  BridgeCommandReleaseMember,
  BridgeCommandRemovePeerTrust,
  BridgeCommandRetireMember,
  BridgeCommandRevokeHost,
  BridgeCommandRevokeSupervisor,
  BridgeCommandUnwireMember,
  BridgeCommandWireMember,
  BridgeDeliveryPayload,
  BridgeDeliveryRejectionCause,
  BridgeDeliveryRejectionCauseStaleMemberIncarnation,
  BridgeDeliveryRejectionCauseStaleMemberResidency,
  BridgeEventCursor,
  BridgeEventCursorAt,
  BridgeEventCursorTail,
  BridgeHostCapabilityRequirements,
  BridgeMemberIncarnation,
  BridgeMobPeerOverlayHandoff,
  BridgeOutboundTaintTarget,
  BridgePeerSpec,
  BridgePeerWiringPayload,
  BridgeProtocolVersion,
  BridgeTrackedInputCancelOutcome,
  BridgeTurnDirective,
  BridgeTurnOutcomeAck,
  BridgeTurnOutcomeRecord,
  CatalogModel,
  Capability,
  CommsCommand,
  CommsSendReceipt,
  ConfigEnvelope,
  ContractVersion,
  ContentBlock,
  ContentInput,
  CreateScheduleRequest,
  EventEnvelope,
  HelpExecutionMode,
  HelpOptions,
  HelpRequest,
  InlineImageBlock,
  InlineVideoBlock,
  UriVideoBlock,
  ModelProfile,
  ModelsCatalog,
  LiveOpenTransport,
  OperationId,
  RunId,
  MobCreateOptions,
  MobControlScope,
  MobDefinition,
  MobEventsOptions,
  MobEventsResult,
  MobFlowStatus,
  MobGrantScopesParams,
  MobGrantScopesResult,
  MobGrantRecord,
  MobGrantsResult,
  MobHardCancelParams,
  MobHardCancelResult,
  MobLifecycleAction,
  MobMember,
  MobProfile,
  MobProfileBinding,
  MobProfileDeleteResult,
  MobProfileLookupResult,
  MobRunResult,
  MobRevokeScopesParams,
  MobRevokeScopesResult,
  MobStatus,
  MobSummary,
  MobTurnStartOptions,
  MobWireMembersBatchEdge,
  MobWireMembersBatchEdgeInput,
  MobWireMembersBatchResult,
  ModelTier,
  PeerCorrelationId,
  PeerId,
  PeerResponseTerminalOptions,
  ProviderModelCatalog,
  RunResult,
  Schedule,
  ScheduleListOptions,
  ScheduleOccurrencesOptions,
  ScheduleOccurrence,
  ScheduleOccurrencesResult,
  ScheduleToolCallRequest,
  ScheduleToolsResult,
  SchemaWarning,
  SessionAssistantBlock,
  SessionContentBlock,
  SessionContentInput,
  SessionForkResult,
  SessionHistory,
  SessionIngressOptions,
  SessionInfo,
  SessionListOptions,
  SessionMessage,
  SessionOptions,
  SessionTranscriptRevision,
  SessionTranscriptRevisionEntry,
  SessionTranscriptRevisionList,
  SessionTranscriptRewriteResult,
  SessionToolResult,
  SkillQuarantineDiagnostic,
  SkillRuntimeDiagnostics,
  SkillKey,
  SkillRef,
  SourceHealthSnapshot,
  SpawnManySpec,
  SpawnSpec,
  TranscriptAssistantBlockReplacement,
  TranscriptEditOptions,
  TranscriptEditRunningBehavior,
  TranscriptForkOptions,
  TranscriptMessageReplacement,
  TranscriptReplacement,
  TranscriptRewriteInputMessage,
  TranscriptRewriteMessage,
  TranscriptRewriteOptions,
  TranscriptRewriteReason,
  TranscriptRewriteSelection,
  TranscriptToolResultContentBlockReplacement,
  TranscriptUserContentBlockReplacement,
  TurnOptions,
  UpdateSchedulePatch,
  UpdateScheduleRequest,
  Usage,
  ReadyWorkFilter,
  WorkAttentionBinding,
  WorkEdge,
  WorkEdgeKind,
  WorkEvidenceKind,
  WorkEvidenceRef,
  WorkGraphEvent,
  WorkGraphEventFilter,
  WorkGraphEventKind,
  WorkGraphEventsResponse,
  WorkGraphIdParams,
  WorkGraphItemLookupOptions,
  WorkGraphItemsResponse,
  WorkGraphPriority,
  WorkGraphSnapshot,
  WorkGraphSnapshotFilter,
  WorkGraphStatus,
  WorkItem,
  WorkItemClaim,
  WorkItemExternalRef,
  WorkItemFilter,
  WorkItemOwner,
  WorkItemRef,
  WireControlScope,
  WireFlowFailureDetail,
  WireFlowTurnOutcome,
  WireGrantRecord,
} from "./types.js";

export {
  parseAttentionListResult,
  parseGoalStatusResult,
  parseWorkAttentionBinding,
  parseWorkEdge,
  parseWorkGraphEvent,
  parseWorkGraphEventsResponse,
  parseWorkGraphItemsResponse,
  parseWorkGraphSnapshot,
  parseWorkItem,
} from "./types.js";

export {
  MeerkatError,
  CapabilityUnavailableError,
  SessionNotFoundError,
  SkillNotFoundError,
  ScopeDeniedError,
  HostUnavailableError,
  StaleCursorError,
  StaleFenceError,
  MULTI_HOST_JSON_RPC_ERROR_CODES,
  meerkatErrorFromJsonRpcCode,
  meerkatErrorFromSemanticCode,
} from "./generated/errors.js";
export type {
  MultiHostErrorCode,
  WireHostUnavailableDetail,
  WireScopeDeniedDetail,
  WireStaleCursorDetail,
  WireStaleFenceDetail,
} from "./generated/errors.js";

export type {
  WireAssistantImageRef,
  WireGenerateImageExecutionPlan,
  WireGenerateImageRequest,
  WireImageGenerationToolResult,
  WireImageOperationPhase,
} from "./generated/types.js";

export { CONTRACT_VERSION } from "./generated/types.js";
export type {
  AttentionBindingRequest,
  AttentionBindingResult,
  AttentionDelegatedAuthority,
  AttentionListRequest,
  AttentionListResult,
  AttentionProjectionPolicy,
  CatalogModelEntry,
  GoalAttentionTarget,
  GoalStatusRequest,
  GoalStatusResult,
  McpAddParams,
  McpHttpConfig,
  McpHttpTransport,
  ModelsCatalogResponse,
  McpRemoveParams,
  McpReloadParams,
  McpLiveOpResponse,
  McpServerConfig,
  McpStdioConfig,
  BridgeLiveControlOutcome,
  BridgeLiveControlOutcomeCommitInput,
  BridgeLiveControlOutcomeInterrupt,
  BridgeLiveControlOutcomeRefresh,
  BridgeLiveControlOutcomeTruncate,
  BridgeLiveControlVerb,
  BridgeLiveControlVerbCommitInput,
  BridgeLiveControlVerbInterrupt,
  BridgeLiveControlVerbRefresh,
  BridgeLiveControlVerbTruncate,
  MobBindHostParams,
  MobBindHostResult,
  MobHostStatus,
  MobHostsResult,
  MobMemberHistoryParams,
  MobMemberHistoryResult,
  MobMemberLiveChannelParams,
  MobMemberLiveControlParams,
  MobMemberLiveOpenParams,
  MobMemberLiveStatusParams,
  MobRevokeHostParams,
  MobRevokeHostResult,
  MobRouteInstallsResult,
  MobBackendConfigInput,
  MobCreateParams,
  MobCreateResult,
  MobDefinitionInput,
  MobEnsureMemberParams,
  MobEnsureMemberResult,
  MobEventRouterConfigInput,
  MobExternalBackendConfigInput,
  MobFlowNodeInput,
  MobFlowSpecInput,
  MobFlowStepInput,
  MobFrameSpecInput,
  MobLimitsSpecInput,
  MobMemberListEntryWire,
  MobMemberSpecWire,
  MobOrchestratorInput,
  MobProfileBindingInput,
  MobProfileInput,
  MobReconcileParams,
  MobReconcileReportWire,
  MobReconcileResult,
  MobSpawnManyParams,
  MobSpawnManyFailedResult,
  MobSpawnManyFailureCause,
  MobSpawnManyResult,
  MobSpawnManyResultEntry,
  MobSpawnManyResultPayload,
  MobSpawnManyResultStatus,
  MobSpawnManySpawnedResult,
  MobSpawnParams,
  MobSpawnPolicyInput,
  MobSpawnReceiptWire,
  MobSpawnSpecParams,
  MobRotateSupervisorResult,
  MobSupervisorSpecInput,
  MobToolConfigInput,
  MobTopologySpecInput,
  MobTurnStartParams,
  MobWireMembersBatchEdge as WireMobWireMembersBatchEdge,
  MobWireMembersBatchParams,
  MobWireMembersBatchResult as WireMobWireMembersBatchResult,
  MobWiringRulesInput,
  LiveChannelParams,
  LiveCloseResult,
  LiveCommitInputParams,
  LiveInputChunkWire,
  // R5-10: re-export typed `LiveInputChunkWire` variants so TS consumers
  // can construct typed chunks at the `LiveSendInputParams.chunk` slot
  // without dipping into `./generated/types`.
  LiveInputChunkWireAudio,
  LiveInputChunkWireText,
  LiveInputChunkWireImage,
  LiveInputChunkWireVideoFrame,
  LiveOpenParams,
  LiveOpenResult,
  LiveWebrtcAnswerParams,
  LiveWebrtcAnswerResult,
  LiveSendInputErrorData,
  LiveSendInputParams,
  LiveStatusResult,
  LiveTruncateParams,
  // Public-safe transcript events: the internal byte-bearing
  // `user_content_final` command is intentionally not part of this union.
  RealtimeTranscriptEvent,
  RealtimeTranscriptEventItemObserved,
  RealtimeTranscriptEventItemSkipped,
  RealtimeTranscriptEventUserTranscriptFinal,
  RealtimeTranscriptEventAssistantTextDelta,
  RealtimeTranscriptEventAssistantTranscriptDelta,
  RealtimeTranscriptEventAssistantTranscriptTruncated,
  RealtimeTranscriptEventAssistantTranscriptFinalText,
  RealtimeTranscriptEventAssistantTurnCompleted,
  RealtimeTranscriptEventAssistantTurnInterrupted,
  RealtimeTranscriptRole,
  // CC5/CC6: typed wire mirrors for `LiveOpenResult.capabilities` /
  // `.continuity`. Re-exported from the SDK root so TS consumers can do
  // typed-narrow on `result.continuity.mode` and read capability booleans
  // (`image_in`, `video_in`, etc.) without dipping into `./generated/types`.
  WireLiveChannelCapabilities,
  WireLiveContinuityMode,
  WireLiveContinuityModeFresh,
  WireLiveContinuityModeTranscriptOnly,
  WireLiveContinuityModeDegraded,
  WireLiveContinuityModeProviderNativeResume,
  // FIX-SDK-OBS: typed live-adapter observation discriminated union and
  // its supporting wire mirrors (status / degradation reason / error
  // code). Closes the verifier gap that left the R5-4 audio identity
  // fields and R5-9 `command_rejected` typed variant invisible at the
  // SDK boundary.
  WireLiveAdapterObservation,
  WireLiveAdapterObservationReady,
  WireLiveAdapterObservationUserTranscriptFinal,
  WireLiveAdapterObservationAssistantTextDelta,
  WireLiveAdapterObservationAssistantTranscriptDelta,
  WireLiveAdapterObservationAssistantAudioChunk,
  WireLiveAdapterObservationAssistantTranscriptFinal,
  WireLiveAdapterObservationAssistantTranscriptTruncated,
  WireLiveAdapterObservationRealtimeTranscript,
  WireLiveAdapterObservationUserContentCommitted,
  WireLiveAdapterObservationToolCallRequested,
  WireLiveAdapterObservationTurnInterrupted,
  WireLiveAdapterObservationTurnCompleted,
  WireLiveAdapterObservationStatusChanged,
  WireLiveAdapterObservationError,
  WireLiveAdapterObservationCommandRejected,
  WireLiveAdapterStatus,
  WireLiveAdapterErrorCode,
  WireLiveConfigRejectionReason,
  WireLiveConfigRejectionReasonImageInputNotImplemented,
  WireLiveConfigRejectionReasonImageInputUnsupportedMime,
  WireLiveConfigRejectionReasonImageInputContentMismatch,
  WireLiveConfigRejectionReasonImageInputInvalidBase64,
  WireLiveConfigRejectionReasonImageInputTooLarge,
  WireLiveConfigRejectionReasonImageInputIdempotencyKeyInvalid,
  WireLiveConfigRejectionReasonImageInputIdempotencyConflict,
  WireLiveConfigRejectionReasonImageInputRequiresCommit,
  WireLiveConfigRejectionReasonInputTooLarge,
  WireLiveConfigRejectionReasonInputBackpressured,
  WireLiveConfigRejectionReasonImageInputBackpressured,
  WireLiveConfigRejectionReasonImageInputTransportUnsupported,
  WireLiveConfigRejectionReasonRefreshTranscriptRewriteRequiresReopen,
  WireLiveDegradationReason,
  WireLiveResponseModality,
  WireLiveTransportBootstrap,
  WireLiveTransportBootstrapWebsocket,
  WireLiveTransportBootstrapWebrtc,
  WireLiveTransportBootstrapUnknown,
  // R7-1 (P2): typed `WireAssistantBlock` discriminated union — variants
  // (Transcript, Text, Reasoning, ...) now emit typed inline `data` shapes
  // rather than `Record<string, unknown>`, so SDK consumers can read
  // transcript `text` / `source` and route on `block_type` without parsing
  // raw JSON.
  WireAssistantBlock,
  WireProvider,
  WireTranscriptSource,
  ProviderCatalog,
  RealtimeAudioChunk,
  RealtimeCapabilities,
  RealtimeImageChunk,
  RealtimeInputChunk,
  RealtimeInputKind,
  RealtimeTextChunk,
  RealtimeTurningMode,
  RealtimeVideoChunk,
  RuntimeAcceptResult,
  RuntimeStateResult,
  SupervisorRotationReportWire,
  WorkAttentionMode,
  WorkAttentionStatus,
  WorkAttentionTarget,
  WorkCompletionPolicy,
  WorkOwnerKey,
  WorkOwnerKind,
  WireModelProfile,
  WireModelTier,
  WireSessionInfo,
  WireSessionSummary,
  WireSessionMessage,
  WireToolResultContent,
  WireStopReason,
  WireInputState,
  WireAuthBindingRef,
  WireHistoryRow,
  WireHostBindPhase,
  WireHostBindingDescriptor,
  WireHostBindingDescriptorKind,
  WireHostCapabilityFlags,
  WireHostRef,
  WireMemberHistoryPageBody,
  WireMemberLifecycleCapabilities,
  WireMemberLaunchMode,
  WireMemberRef,
  WireMobBackendKind,
  WireMobMemberStatus,
  WireMobProfile,
  WireMobRuntimeMode,
  WireMobToolConfig,
  WireNonPortableResourceKind,
  WireProjectionProvenance,
  WireReachability,
  WireRouteInstallObligation,
  WireRuntimeBinding,
  WireToolAccessPolicy,
  WireToolFilter,
  WireTrustedPeerIdentity,
  WireTrustedPeerIdentityEd25519PublicKey,
} from "./generated/types.js";

export type {
  AgentEvent,
  CoreAgentEvent,
  StreamEvent,
  ScopedAgentEvent,
  StreamScopeFrame,
  RunStartedEvent,
  RunCompletedEvent,
  ExtractionSucceededEvent,
  ExtractionFailedEvent,
  RunFailedEvent,
  AgentErrorClass,
  AgentErrorReport,
  AgentErrorReason,
  TurnTerminalCauseReason,
  TurnTerminalCauseKind,
  TurnTerminalOutcome,
  UnknownAgentErrorReason,
  TurnStartedEvent,
  TextDeltaEvent,
  TextCompleteEvent,
  ToolCallRequestedEvent,
  ToolResultReceivedEvent,
  TurnCompletedEvent,
  ToolExecutionStartedEvent,
  ToolExecutionCompletedEvent,
  ToolExecutionTimedOutEvent,
  CompactionStartedEvent,
  CompactionCompletedEvent,
  CompactionFailedEvent,
  BudgetWarningEvent,
  RetryingEvent,
  HookStartedEvent,
  HookCompletedEvent,
  HookFailedEvent,
  HookDeniedEvent,
  SkillsResolvedEvent,
  SkillResolutionFailedEvent,
  SkillResolutionFailureReason,
  InteractionCompleteEvent,
  InteractionFailureReason,
  InteractionFailedEvent,
  StreamTruncationReason,
  StreamTruncatedEvent,
  BackgroundJobCompletedEvent,
  BackgroundJobTerminalStatus,
  TranscriptRewriteCommittedEvent,
  ToolConfigChangedEvent,
  ToolConfigChangedPayload,
  ToolConfigChangeOperation,
  ToolConfigChangeStatus,
  BoundaryAppliedToolConfigChangeStatus,
  DeferredCatalogDeltaToolConfigChangeStatus,
  WarningFailedClosedToolConfigChangeStatus,
  ExternalToolDeltaToolConfigChangeStatus,
  ExternalToolDeltaPhase,
  MalformedEvent,
  UnknownEvent,
  StopReason,
  ToolCallArguments,
  BudgetType,
  HookId,
  HookPoint,
} from "./events.js";

export {
  parseEvent,
  parseCoreEvent,
  isTextDelta,
  isTextComplete,
  isTurnCompleted,
  isToolCallRequested,
  isRunCompleted,
  isExtractionSucceeded,
  isExtractionFailed,
  isRunFailed,
} from "./events.js";
