// Generated by `cargo xtask machine-codegen --all`.
#![allow(
    clippy::bool_comparison,
    clippy::clone_on_copy,
    clippy::cloned_instead_of_copied,
    clippy::collapsible_else_if,
    clippy::expect_used,
    clippy::explicit_iter_loop,
    clippy::if_not_else,
    clippy::len_zero,
    clippy::overly_complex_bool_expr,
    clippy::partialeq_to_none,
    clippy::ptr_arg,
    clippy::redundant_clone,
    clippy::redundant_closure,
    clippy::uninlined_format_args,
    dead_code,
    non_camel_case_types,
    non_snake_case,
    unused_imports,
    unused_parens,
    unused_variables
)]
use meerkat_machine_schema::compat::types as compat_types;

mod substrate {
    use super::compat_types::*;
    use serde::{Deserialize, Serialize};
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CompatMachineState {
        pub phase: CompatPhase,
        pub loop_instance_id: LoopInstanceId,
        pub parent_frame_id: FrameId,
        pub parent_node_id: FlowNodeId,
        pub loop_id: LoopId,
        pub depth: u32,
        pub stage: LoopIterationStage,
        pub current_iteration: u32,
        pub last_completed_iteration: u32,
        pub max_iterations: u32,
        pub active_body_frame_id: Option<FrameId>,
    }
    impl Default for CompatMachineState {
        fn default() -> Self {
            Self {
                phase: CompatPhase::Absent,
                loop_instance_id: LoopInstanceId("".into()),
                parent_frame_id: FrameId("".into()),
                parent_node_id: FlowNodeId("".into()),
                loop_id: LoopId("".into()),
                depth: 0,
                stage: LoopIterationStage::AwaitingBodyFrame,
                current_iteration: 0,
                last_completed_iteration: 0,
                max_iterations: 0,
                active_body_frame_id: None,
            }
        }
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde :: Serialize, serde :: Deserialize)]
    pub enum CompatPhase {
        Absent,
        Running,
        Completed,
        Exhausted,
        Failed,
        Canceled,
    }
    impl CompatMachineState {
        pub fn phase(&self) -> CompatPhase {
            self.phase
        }
    }
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub enum CompatInput {
        StartLoop {
            loop_instance_id: LoopInstanceId,
            max_iterations: u32,
            parent_frame_id: FrameId,
            parent_node_id: FlowNodeId,
            loop_id: LoopId,
            depth: u32,
        },
        BodyFrameStarted {
            loop_instance_id: LoopInstanceId,
            frame_id: FrameId,
            iteration: u32,
        },
        BodyFrameCompleted {
            loop_instance_id: LoopInstanceId,
            iteration: u32,
        },
        BodyFrameFailed {
            loop_instance_id: LoopInstanceId,
            iteration: u32,
        },
        BodyFrameCanceled {
            loop_instance_id: LoopInstanceId,
            iteration: u32,
        },
        UntilConditionMet {
            loop_instance_id: LoopInstanceId,
            iteration: u32,
        },
        UntilConditionFailed {
            loop_instance_id: LoopInstanceId,
            iteration: u32,
        },
        CancelLoop {
            loop_instance_id: LoopInstanceId,
        },
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub enum CompatInputKind {
        StartLoop,
        BodyFrameStarted,
        BodyFrameCompleted,
        BodyFrameFailed,
        BodyFrameCanceled,
        UntilConditionMet,
        UntilConditionFailed,
        CancelLoop,
    }
    impl CompatInput {
        pub fn kind(&self) -> CompatInputKind {
            match self {
                Self::StartLoop { .. } => CompatInputKind::StartLoop,
                Self::BodyFrameStarted { .. } => CompatInputKind::BodyFrameStarted,
                Self::BodyFrameCompleted { .. } => CompatInputKind::BodyFrameCompleted,
                Self::BodyFrameFailed { .. } => CompatInputKind::BodyFrameFailed,
                Self::BodyFrameCanceled { .. } => CompatInputKind::BodyFrameCanceled,
                Self::UntilConditionMet { .. } => CompatInputKind::UntilConditionMet,
                Self::UntilConditionFailed { .. } => CompatInputKind::UntilConditionFailed,
                Self::CancelLoop { .. } => CompatInputKind::CancelLoop,
            }
        }
    }
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub enum CompatEffect {
        RequestBodyFrameStart {
            loop_instance_id: LoopInstanceId,
            depth: u32,
        },
        EvaluateUntilCondition {
            loop_instance_id: LoopInstanceId,
            iteration: u32,
            parent_frame_id: FrameId,
            parent_node_id: FlowNodeId,
            loop_id: LoopId,
        },
        LoopCompleted {
            loop_instance_id: LoopInstanceId,
            parent_frame_id: FrameId,
            parent_node_id: FlowNodeId,
        },
        LoopExhausted {
            loop_instance_id: LoopInstanceId,
            parent_frame_id: FrameId,
            parent_node_id: FlowNodeId,
        },
        LoopFailed {
            loop_instance_id: LoopInstanceId,
            parent_frame_id: FrameId,
            parent_node_id: FlowNodeId,
        },
        LoopCanceled {
            loop_instance_id: LoopInstanceId,
            parent_frame_id: FrameId,
            parent_node_id: FlowNodeId,
        },
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub enum CompatEffectKind {
        RequestBodyFrameStart,
        EvaluateUntilCondition,
        LoopCompleted,
        LoopExhausted,
        LoopFailed,
        LoopCanceled,
    }
    impl CompatEffect {
        pub fn kind(&self) -> CompatEffectKind {
            match self {
                Self::RequestBodyFrameStart { .. } => CompatEffectKind::RequestBodyFrameStart,
                Self::EvaluateUntilCondition { .. } => CompatEffectKind::EvaluateUntilCondition,
                Self::LoopCompleted { .. } => CompatEffectKind::LoopCompleted,
                Self::LoopExhausted { .. } => CompatEffectKind::LoopExhausted,
                Self::LoopFailed { .. } => CompatEffectKind::LoopFailed,
                Self::LoopCanceled { .. } => CompatEffectKind::LoopCanceled,
            }
        }
    }
    use CompatPhase as Phase;
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CompatMachineTransition {
        pub from_phase: CompatPhase,
        pub to_phase: CompatPhase,
        pub transition_id: CompatMachineTransitionId,
        pub effects: Vec<CompatEffect>,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub enum CompatMachineTransitionId {
        StartLoop,
        BodyFrameStarted,
        BodyFrameCompleted,
        UntilConditionMet,
        UntilConditionFailed,
        ExhaustedIterations,
        BodyFrameFailed,
        BodyFrameCanceled,
        CancelLoop,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub enum CompatMachineGuardId {
        BodyFrameStartedGuard1,
        BodyFrameStartedGuard2,
        BodyFrameStartedGuard3,
        BodyFrameCompletedGuard1,
        BodyFrameCompletedGuard2,
        BodyFrameCompletedGuard3,
        UntilConditionMetGuard1,
        UntilConditionMetGuard2,
        UntilConditionMetGuard3,
        UntilConditionFailedGuard1,
        UntilConditionFailedGuard2,
        UntilConditionFailedGuard3,
        UntilConditionFailedGuard4,
        ExhaustedIterationsGuard1,
        ExhaustedIterationsGuard2,
        ExhaustedIterationsGuard3,
        ExhaustedIterationsGuard4,
        BodyFrameFailedGuard1,
        BodyFrameFailedGuard2,
        BodyFrameFailedGuard3,
        BodyFrameCanceledGuard1,
        BodyFrameCanceledGuard2,
        BodyFrameCanceledGuard3,
        CancelLoopGuard1,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub enum CompatMachineHelperId {}
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub enum CompatMachineTransitionError {
        #[doc = r" No transition is declared for this `(phase, trigger)` pair at"]
        #[doc = r" all — the trigger variant is semantically out of scope for"]
        #[doc = r" the current phase. Shell callers should treat this as a hard"]
        #[doc = r" error: firing the wrong input for the current phase is a"]
        #[doc = r" programming mistake."]
        NoMatchingTransition { phase: String, trigger: String },
        #[doc = r" A transition is declared for this `(phase, trigger)` pair"]
        #[doc = r" but every candidate transition's guard(s) evaluated false."]
        #[doc = r" Typed signal that the input was *rejected on state*, not"]
        #[doc = r" *unrecognised*. Shell callers that fire idempotently (e.g.,"]
        #[doc = r" a realtime dispatcher firing `ProductTurnCommitted` on every"]
        #[doc = r" observed `TurnCommitted` event, expecting the DSL to drop"]
        #[doc = r" duplicates) should treat this as a successful no-op rather"]
        #[doc = r" than an error."]
        GuardRejected { phase: String, trigger: String },
    }
    impl std::fmt::Display for CompatMachineTransitionError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                Self::NoMatchingTransition { phase, trigger } => {
                    write!(
                        f,
                        "no matching transition from phase {} for {}",
                        phase, trigger
                    )
                }
                Self::GuardRejected { phase, trigger } => {
                    write!(
                        f,
                        "guard rejected transition from phase {} for {}",
                        phase, trigger
                    )
                }
            }
        }
    }
    impl std::error::Error for CompatMachineTransitionError {}
    mod sealed {
        pub trait Sealed {}
    }
    pub trait CompatMachineMutator: sealed::Sealed {
        fn apply(
            &mut self,
            input: CompatInput,
        ) -> Result<CompatMachineTransition, CompatMachineTransitionError>;
    }
    pub struct CompatMachineAuthority {
        pub state: CompatMachineState,
    }
    impl sealed::Sealed for CompatMachineAuthority {}
    impl CompatMachineAuthority {
        pub fn new() -> Self {
            Self {
                state: CompatMachineState::default(),
            }
        }
        pub fn from_state(state: CompatMachineState) -> Self {
            Self { state }
        }
    }
    impl CompatMachineMutator for CompatMachineAuthority {
        fn apply(
            &mut self,
            input: CompatInput,
        ) -> Result<CompatMachineTransition, CompatMachineTransitionError> {
            let from_phase = self.state.phase();
            #[allow(unused_mut)]
            let mut effects = Vec::new();
            let transition_id;
            match input {
                CompatInput::StartLoop {
                    loop_instance_id,
                    max_iterations,
                    parent_frame_id,
                    parent_node_id,
                    loop_id,
                    depth,
                } => {
                    transition_id = CompatMachineTransitionId::StartLoop;
                    self.state.loop_instance_id = loop_instance_id.clone();
                    self.state.parent_frame_id = parent_frame_id.clone();
                    self.state.parent_node_id = parent_node_id.clone();
                    self.state.loop_id = loop_id.clone();
                    self.state.depth = depth.clone();
                    self.state.stage = LoopIterationStage::AwaitingBodyFrame;
                    self.state.max_iterations = max_iterations.clone();
                    self.state.current_iteration = 0;
                    self.state.last_completed_iteration = 0;
                    self.state.active_body_frame_id = None;
                    self.state.phase = CompatPhase::Running;
                    effects.push(CompatEffect::RequestBodyFrameStart {
                        loop_instance_id: (self.state.loop_instance_id).clone(),
                        depth: (self.state.depth).clone(),
                    });
                }
                CompatInput::BodyFrameStarted {
                    loop_instance_id,
                    frame_id,
                    iteration,
                } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::AwaitingBodyFrame)
                        && (self.state.current_iteration == iteration.clone())
                    {
                        transition_id = CompatMachineTransitionId::BodyFrameStarted;
                        self.state.active_body_frame_id = Some(frame_id.clone());
                        self.state.stage = LoopIterationStage::BodyFrameActive;
                        self.state.phase = CompatPhase::Running;
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "BodyFrameStarted".to_string(),
                        });
                    }
                }
                CompatInput::BodyFrameCompleted {
                    loop_instance_id,
                    iteration,
                } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::BodyFrameActive)
                        && (self.state.current_iteration == iteration.clone())
                    {
                        transition_id = CompatMachineTransitionId::BodyFrameCompleted;
                        self.state.active_body_frame_id = None;
                        self.state.last_completed_iteration = iteration.clone();
                        self.state.current_iteration += 1;
                        self.state.stage = LoopIterationStage::AwaitingUntil;
                        self.state.phase = CompatPhase::Running;
                        effects.push(CompatEffect::EvaluateUntilCondition {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            iteration: (self.state.last_completed_iteration).clone(),
                            parent_frame_id: (self.state.parent_frame_id).clone(),
                            parent_node_id: (self.state.parent_node_id).clone(),
                            loop_id: (self.state.loop_id).clone(),
                        });
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "BodyFrameCompleted".to_string(),
                        });
                    }
                }
                CompatInput::UntilConditionMet {
                    loop_instance_id,
                    iteration,
                } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::AwaitingUntil)
                        && (self.state.last_completed_iteration == iteration.clone())
                    {
                        transition_id = CompatMachineTransitionId::UntilConditionMet;
                        self.state.phase = CompatPhase::Completed;
                        effects.push(CompatEffect::LoopCompleted {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            parent_frame_id: (self.state.parent_frame_id).clone(),
                            parent_node_id: (self.state.parent_node_id).clone(),
                        });
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "UntilConditionMet".to_string(),
                        });
                    }
                }
                CompatInput::UntilConditionFailed {
                    loop_instance_id,
                    iteration,
                } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::AwaitingUntil)
                        && (self.state.last_completed_iteration == iteration.clone())
                        && (self.state.current_iteration < self.state.max_iterations)
                    {
                        transition_id = CompatMachineTransitionId::UntilConditionFailed;
                        self.state.stage = LoopIterationStage::AwaitingBodyFrame;
                        self.state.phase = CompatPhase::Running;
                        effects.push(CompatEffect::RequestBodyFrameStart {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            depth: (self.state.depth).clone(),
                        });
                    } else if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::AwaitingUntil)
                        && (self.state.last_completed_iteration == iteration.clone())
                        && (self.state.current_iteration >= self.state.max_iterations)
                    {
                        transition_id = CompatMachineTransitionId::ExhaustedIterations;
                        self.state.phase = CompatPhase::Exhausted;
                        effects.push(CompatEffect::LoopExhausted {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            parent_frame_id: (self.state.parent_frame_id).clone(),
                            parent_node_id: (self.state.parent_node_id).clone(),
                        });
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "UntilConditionFailed".to_string(),
                        });
                    }
                }
                CompatInput::BodyFrameFailed {
                    loop_instance_id,
                    iteration,
                } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::BodyFrameActive)
                        && (self.state.current_iteration == iteration.clone())
                    {
                        transition_id = CompatMachineTransitionId::BodyFrameFailed;
                        self.state.active_body_frame_id = None;
                        self.state.phase = CompatPhase::Failed;
                        effects.push(CompatEffect::LoopFailed {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            parent_frame_id: (self.state.parent_frame_id).clone(),
                            parent_node_id: (self.state.parent_node_id).clone(),
                        });
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "BodyFrameFailed".to_string(),
                        });
                    }
                }
                CompatInput::BodyFrameCanceled {
                    loop_instance_id,
                    iteration,
                } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone())
                        && (self.state.stage == LoopIterationStage::BodyFrameActive)
                        && (self.state.current_iteration == iteration.clone())
                    {
                        transition_id = CompatMachineTransitionId::BodyFrameCanceled;
                        self.state.active_body_frame_id = None;
                        self.state.phase = CompatPhase::Canceled;
                        effects.push(CompatEffect::LoopCanceled {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            parent_frame_id: (self.state.parent_frame_id).clone(),
                            parent_node_id: (self.state.parent_node_id).clone(),
                        });
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "BodyFrameCanceled".to_string(),
                        });
                    }
                }
                CompatInput::CancelLoop { loop_instance_id } => {
                    if (self.state.loop_instance_id == loop_instance_id.clone()) {
                        transition_id = CompatMachineTransitionId::CancelLoop;
                        self.state.phase = CompatPhase::Canceled;
                        effects.push(CompatEffect::LoopCanceled {
                            loop_instance_id: (self.state.loop_instance_id).clone(),
                            parent_frame_id: (self.state.parent_frame_id).clone(),
                            parent_node_id: (self.state.parent_node_id).clone(),
                        });
                    } else {
                        return Err(CompatMachineTransitionError::GuardRejected {
                            phase: format!("{:?}", from_phase),
                            trigger: "CancelLoop".to_string(),
                        });
                    }
                }
                #[allow(unreachable_patterns)]
                _ => {
                    return Err(CompatMachineTransitionError::NoMatchingTransition {
                        phase: format!("{:?}", from_phase),
                        trigger: format!("{:?}", input),
                    });
                }
            }
            let to_phase = self.state.phase();
            Ok(CompatMachineTransition {
                from_phase,
                to_phase,
                transition_id,
                effects,
            })
        }
    }
}

pub type Phase = substrate::CompatPhase;
pub type TransitionId = substrate::CompatMachineTransitionId;
pub type GuardId = substrate::CompatMachineGuardId;
pub type HelperId = substrate::CompatMachineHelperId;

pub mod inputs {
    use super::compat_types;

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct StartLoop {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub max_iterations: u32,
        pub parent_frame_id: compat_types::FrameId,
        pub parent_node_id: compat_types::FlowNodeId,
        pub loop_id: compat_types::LoopId,
        pub depth: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct BodyFrameStarted {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub frame_id: compat_types::FrameId,
        pub iteration: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct BodyFrameCompleted {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub iteration: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct BodyFrameFailed {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub iteration: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct BodyFrameCanceled {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub iteration: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct UntilConditionMet {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub iteration: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct UntilConditionFailed {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub iteration: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CancelLoop {
        pub loop_instance_id: compat_types::LoopInstanceId,
    }
}

pub mod effects {
    use super::compat_types;

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct RequestBodyFrameStart {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub depth: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct EvaluateUntilCondition {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub iteration: u32,
        pub parent_frame_id: compat_types::FrameId,
        pub parent_node_id: compat_types::FlowNodeId,
        pub loop_id: compat_types::LoopId,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct LoopCompleted {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub parent_frame_id: compat_types::FrameId,
        pub parent_node_id: compat_types::FlowNodeId,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct LoopExhausted {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub parent_frame_id: compat_types::FrameId,
        pub parent_node_id: compat_types::FlowNodeId,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct LoopFailed {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub parent_frame_id: compat_types::FrameId,
        pub parent_node_id: compat_types::FlowNodeId,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct LoopCanceled {
        pub loop_instance_id: compat_types::LoopInstanceId,
        pub parent_frame_id: compat_types::FrameId,
        pub parent_node_id: compat_types::FlowNodeId,
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Input {
    StartLoop(inputs::StartLoop),
    BodyFrameStarted(inputs::BodyFrameStarted),
    BodyFrameCompleted(inputs::BodyFrameCompleted),
    BodyFrameFailed(inputs::BodyFrameFailed),
    BodyFrameCanceled(inputs::BodyFrameCanceled),
    UntilConditionMet(inputs::UntilConditionMet),
    UntilConditionFailed(inputs::UntilConditionFailed),
    CancelLoop(inputs::CancelLoop),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum InputKind {
    StartLoop,
    BodyFrameStarted,
    BodyFrameCompleted,
    BodyFrameFailed,
    BodyFrameCanceled,
    UntilConditionMet,
    UntilConditionFailed,
    CancelLoop,
}

impl Input {
    pub fn kind(&self) -> InputKind {
        match self {
            Self::StartLoop(_) => InputKind::StartLoop,
            Self::BodyFrameStarted(_) => InputKind::BodyFrameStarted,
            Self::BodyFrameCompleted(_) => InputKind::BodyFrameCompleted,
            Self::BodyFrameFailed(_) => InputKind::BodyFrameFailed,
            Self::BodyFrameCanceled(_) => InputKind::BodyFrameCanceled,
            Self::UntilConditionMet(_) => InputKind::UntilConditionMet,
            Self::UntilConditionFailed(_) => InputKind::UntilConditionFailed,
            Self::CancelLoop(_) => InputKind::CancelLoop,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Effect {
    RequestBodyFrameStart(effects::RequestBodyFrameStart),
    EvaluateUntilCondition(effects::EvaluateUntilCondition),
    LoopCompleted(effects::LoopCompleted),
    LoopExhausted(effects::LoopExhausted),
    LoopFailed(effects::LoopFailed),
    LoopCanceled(effects::LoopCanceled),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EffectKind {
    RequestBodyFrameStart,
    EvaluateUntilCondition,
    LoopCompleted,
    LoopExhausted,
    LoopFailed,
    LoopCanceled,
}

impl Effect {
    pub fn kind(&self) -> EffectKind {
        match self {
            Self::RequestBodyFrameStart(_) => EffectKind::RequestBodyFrameStart,
            Self::EvaluateUntilCondition(_) => EffectKind::EvaluateUntilCondition,
            Self::LoopCompleted(_) => EffectKind::LoopCompleted,
            Self::LoopExhausted(_) => EffectKind::LoopExhausted,
            Self::LoopFailed(_) => EffectKind::LoopFailed,
            Self::LoopCanceled(_) => EffectKind::LoopCanceled,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct State {
    pub phase: Phase,
    pub loop_instance_id: compat_types::LoopInstanceId,
    pub parent_frame_id: compat_types::FrameId,
    pub parent_node_id: compat_types::FlowNodeId,
    pub loop_id: compat_types::LoopId,
    pub depth: u32,
    pub stage: compat_types::LoopIterationStage,
    pub current_iteration: u32,
    pub last_completed_iteration: u32,
    pub max_iterations: u32,
    pub active_body_frame_id: Option<compat_types::FrameId>,
}

impl Default for State {
    fn default() -> Self {
        initial_state()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Outcome {
    pub transition_id: TransitionId,
    pub next_state: State,
    pub effects: Vec<Effect>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GuardRejection {
    pub transition_id: TransitionId,
    pub guard_id: GuardId,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TriggerDiscriminant {
    Input(InputKind),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TransitionRefusal {
    NoMatchingTransition {
        phase: Phase,
        trigger: TriggerDiscriminant,
    },
    GuardRejected {
        rejections: Vec<GuardRejection>,
    },
    AmbiguousTransition {
        transitions: Vec<TransitionId>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum KernelError {
    ContextViolation {
        transition_id: TransitionId,
        detail: String,
    },
    HelperEvaluation {
        helper_id: HelperId,
        detail: String,
    },
    CodegenInvariant {
        detail: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TransitionError {
    Refusal(TransitionRefusal),
    Kernel(KernelError),
}

pub trait Context {}

#[derive(Debug, Clone, Default)]
pub struct EmptyContext;

impl Context for EmptyContext {}

pub fn schema() -> meerkat_machine_schema::MachineSchema {
    meerkat_machine_schema::loop_iteration_machine()
}

pub fn initial_state() -> State {
    state_from_substrate(substrate::CompatMachineState::default())
}

pub fn transition(
    state: &State,
    input: Input,
    _context: &impl Context,
) -> Result<Outcome, TransitionError> {
    let trigger = TriggerDiscriminant::Input(input.kind());
    let mut authority = substrate::CompatMachineAuthority::from_state(state_to_substrate(state));
    let transition =
        substrate::CompatMachineMutator::apply(&mut authority, input_to_substrate(input))
            .map_err(|error| map_substrate_error(error, state.phase, trigger.clone()))?;
    Ok(outcome_from_substrate(&authority, transition))
}

pub mod helpers {}

fn input_to_substrate(input: Input) -> substrate::CompatInput {
    match input {
        Input::StartLoop(payload) => substrate::CompatInput::StartLoop {
            loop_instance_id: payload.loop_instance_id,
            max_iterations: payload.max_iterations,
            parent_frame_id: payload.parent_frame_id,
            parent_node_id: payload.parent_node_id,
            loop_id: payload.loop_id,
            depth: payload.depth,
        },
        Input::BodyFrameStarted(payload) => substrate::CompatInput::BodyFrameStarted {
            loop_instance_id: payload.loop_instance_id,
            frame_id: payload.frame_id,
            iteration: payload.iteration,
        },
        Input::BodyFrameCompleted(payload) => substrate::CompatInput::BodyFrameCompleted {
            loop_instance_id: payload.loop_instance_id,
            iteration: payload.iteration,
        },
        Input::BodyFrameFailed(payload) => substrate::CompatInput::BodyFrameFailed {
            loop_instance_id: payload.loop_instance_id,
            iteration: payload.iteration,
        },
        Input::BodyFrameCanceled(payload) => substrate::CompatInput::BodyFrameCanceled {
            loop_instance_id: payload.loop_instance_id,
            iteration: payload.iteration,
        },
        Input::UntilConditionMet(payload) => substrate::CompatInput::UntilConditionMet {
            loop_instance_id: payload.loop_instance_id,
            iteration: payload.iteration,
        },
        Input::UntilConditionFailed(payload) => substrate::CompatInput::UntilConditionFailed {
            loop_instance_id: payload.loop_instance_id,
            iteration: payload.iteration,
        },
        Input::CancelLoop(payload) => substrate::CompatInput::CancelLoop {
            loop_instance_id: payload.loop_instance_id,
        },
    }
}

fn effect_from_substrate(effect: substrate::CompatEffect) -> Effect {
    match effect {
        substrate::CompatEffect::RequestBodyFrameStart {
            loop_instance_id,
            depth,
        } => Effect::RequestBodyFrameStart(effects::RequestBodyFrameStart {
            loop_instance_id,
            depth,
        }),
        substrate::CompatEffect::EvaluateUntilCondition {
            loop_instance_id,
            iteration,
            parent_frame_id,
            parent_node_id,
            loop_id,
        } => Effect::EvaluateUntilCondition(effects::EvaluateUntilCondition {
            loop_instance_id,
            iteration,
            parent_frame_id,
            parent_node_id,
            loop_id,
        }),
        substrate::CompatEffect::LoopCompleted {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        } => Effect::LoopCompleted(effects::LoopCompleted {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        }),
        substrate::CompatEffect::LoopExhausted {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        } => Effect::LoopExhausted(effects::LoopExhausted {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        }),
        substrate::CompatEffect::LoopFailed {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        } => Effect::LoopFailed(effects::LoopFailed {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        }),
        substrate::CompatEffect::LoopCanceled {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        } => Effect::LoopCanceled(effects::LoopCanceled {
            loop_instance_id,
            parent_frame_id,
            parent_node_id,
        }),
    }
}

fn state_to_substrate(state: &State) -> substrate::CompatMachineState {
    substrate::CompatMachineState {
        phase: state.phase,
        loop_instance_id: state.loop_instance_id.clone(),
        parent_frame_id: state.parent_frame_id.clone(),
        parent_node_id: state.parent_node_id.clone(),
        loop_id: state.loop_id.clone(),
        depth: state.depth.clone(),
        stage: state.stage.clone(),
        current_iteration: state.current_iteration.clone(),
        last_completed_iteration: state.last_completed_iteration.clone(),
        max_iterations: state.max_iterations.clone(),
        active_body_frame_id: state.active_body_frame_id.clone(),
    }
}

fn state_from_substrate(state: substrate::CompatMachineState) -> State {
    State {
        phase: state.phase,
        loop_instance_id: state.loop_instance_id,
        parent_frame_id: state.parent_frame_id,
        parent_node_id: state.parent_node_id,
        loop_id: state.loop_id,
        depth: state.depth,
        stage: state.stage,
        current_iteration: state.current_iteration,
        last_completed_iteration: state.last_completed_iteration,
        max_iterations: state.max_iterations,
        active_body_frame_id: state.active_body_frame_id,
    }
}

fn outcome_from_substrate(
    authority: &substrate::CompatMachineAuthority,
    transition: substrate::CompatMachineTransition,
) -> Outcome {
    Outcome {
        transition_id: transition.transition_id,
        next_state: state_from_substrate(authority.state.clone()),
        effects: transition
            .effects
            .into_iter()
            .map(effect_from_substrate)
            .collect(),
    }
}

fn map_substrate_error(
    error: substrate::CompatMachineTransitionError,
    phase: Phase,
    trigger: TriggerDiscriminant,
) -> TransitionError {
    match error {
        substrate::CompatMachineTransitionError::NoMatchingTransition { .. } => {
            let rejections = guard_rejections_for_trigger(&phase, &trigger);
            if rejections.is_empty() {
                TransitionError::Refusal(TransitionRefusal::NoMatchingTransition { phase, trigger })
            } else {
                TransitionError::Refusal(TransitionRefusal::GuardRejected { rejections })
            }
        }
        substrate::CompatMachineTransitionError::GuardRejected { .. } => {
            TransitionError::Refusal(TransitionRefusal::GuardRejected {
                rejections: guard_rejections_for_trigger(&phase, &trigger),
            })
        }
    }
}

fn guard_rejections_for_trigger(
    phase: &Phase,
    trigger: &TriggerDiscriminant,
) -> Vec<GuardRejection> {
    match (phase, trigger) {
        (Phase::Running, TriggerDiscriminant::Input(InputKind::BodyFrameCanceled)) => vec![
            GuardRejection {
                transition_id: TransitionId::BodyFrameCanceled,
                guard_id: GuardId::BodyFrameCanceledGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameCanceled,
                guard_id: GuardId::BodyFrameCanceledGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameCanceled,
                guard_id: GuardId::BodyFrameCanceledGuard3,
            },
        ],
        (Phase::Running, TriggerDiscriminant::Input(InputKind::BodyFrameCompleted)) => vec![
            GuardRejection {
                transition_id: TransitionId::BodyFrameCompleted,
                guard_id: GuardId::BodyFrameCompletedGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameCompleted,
                guard_id: GuardId::BodyFrameCompletedGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameCompleted,
                guard_id: GuardId::BodyFrameCompletedGuard3,
            },
        ],
        (Phase::Running, TriggerDiscriminant::Input(InputKind::BodyFrameFailed)) => vec![
            GuardRejection {
                transition_id: TransitionId::BodyFrameFailed,
                guard_id: GuardId::BodyFrameFailedGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameFailed,
                guard_id: GuardId::BodyFrameFailedGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameFailed,
                guard_id: GuardId::BodyFrameFailedGuard3,
            },
        ],
        (Phase::Running, TriggerDiscriminant::Input(InputKind::BodyFrameStarted)) => vec![
            GuardRejection {
                transition_id: TransitionId::BodyFrameStarted,
                guard_id: GuardId::BodyFrameStartedGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameStarted,
                guard_id: GuardId::BodyFrameStartedGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::BodyFrameStarted,
                guard_id: GuardId::BodyFrameStartedGuard3,
            },
        ],
        (Phase::Running, TriggerDiscriminant::Input(InputKind::CancelLoop)) => {
            vec![GuardRejection {
                transition_id: TransitionId::CancelLoop,
                guard_id: GuardId::CancelLoopGuard1,
            }]
        }
        (Phase::Running, TriggerDiscriminant::Input(InputKind::UntilConditionFailed)) => vec![
            GuardRejection {
                transition_id: TransitionId::UntilConditionFailed,
                guard_id: GuardId::UntilConditionFailedGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::UntilConditionFailed,
                guard_id: GuardId::UntilConditionFailedGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::UntilConditionFailed,
                guard_id: GuardId::UntilConditionFailedGuard3,
            },
            GuardRejection {
                transition_id: TransitionId::UntilConditionFailed,
                guard_id: GuardId::UntilConditionFailedGuard4,
            },
            GuardRejection {
                transition_id: TransitionId::ExhaustedIterations,
                guard_id: GuardId::ExhaustedIterationsGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::ExhaustedIterations,
                guard_id: GuardId::ExhaustedIterationsGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::ExhaustedIterations,
                guard_id: GuardId::ExhaustedIterationsGuard3,
            },
            GuardRejection {
                transition_id: TransitionId::ExhaustedIterations,
                guard_id: GuardId::ExhaustedIterationsGuard4,
            },
        ],
        (Phase::Running, TriggerDiscriminant::Input(InputKind::UntilConditionMet)) => vec![
            GuardRejection {
                transition_id: TransitionId::UntilConditionMet,
                guard_id: GuardId::UntilConditionMetGuard1,
            },
            GuardRejection {
                transition_id: TransitionId::UntilConditionMet,
                guard_id: GuardId::UntilConditionMetGuard2,
            },
            GuardRejection {
                transition_id: TransitionId::UntilConditionMet,
                guard_id: GuardId::UntilConditionMetGuard3,
            },
        ],
        _ => Vec::new(),
    }
}
