#![recursion_limit = "256"]

//! Meerkat contracts — canonical wire types, capability model, and error contracts.
//!
//! This crate is the single source of truth for all wire-facing types.
//! Surface crates (RPC, REST, MCP, CLI) consume these types directly.

pub mod capability;
pub mod error;
pub mod event_catalog;
pub mod protocol;
pub mod rest_catalog;
pub mod rpc_catalog;
pub mod session_locator;
pub mod version;
pub mod wire;

#[cfg(feature = "schema")]
pub mod emit;

// Re-exports for convenience
pub use capability::{
    CapabilitiesResponse, CapabilityEntry, CapabilityId, CapabilityRegistration, CapabilityScope,
    CapabilityStatus, available_capabilities, build_capabilities, resolve_capabilities,
};
pub use error::{CapabilityHint, ErrorCategory, ErrorCode, WireError};
pub use event_catalog::KNOWN_AGENT_EVENT_TYPES;
pub use protocol::Protocol;
pub use rest_catalog::{
    RestOperationDescriptor, RestPathDescriptor, rest_documented_paths, rest_path_catalog,
};
pub use rpc_catalog::{
    RpcMethodCatalogOptions, RpcMethodDescriptor, RpcNotificationDescriptor, rpc_method_catalog,
    rpc_method_names, rpc_notification_catalog, rpc_notification_names,
};
pub use session_locator::{SessionLocator, SessionLocatorError, format_session_ref};
pub use version::ContractVersion;
pub use wire::supervisor_bridge::{
    BridgeAck, BridgeBindPayload, BridgeBindResponse, BridgeCapabilities, BridgeCommand,
    BridgeDeliveryOutcome, BridgeDeliveryPayload, BridgeDeliveryResponse, BridgeDestroyResponse,
    BridgeMemberRuntimeState, BridgeObservationResponse, BridgePeerConnectivity, BridgePeerSpec,
    BridgePeerWiringPayload, BridgeReply, BridgeRetireResponse, BridgeSupervisorPayload,
};
pub use wire::{
    AudioFormatMismatchContext,
    CatalogModelEntry,
    CommsParams,
    CoreCreateParams,
    HookParams,
    ListSchedulesParams,
    McpAddParams,
    McpLiveOpResponse,
    McpLiveOpStatus,
    McpLiveOperation,
    McpReloadParams,
    McpRemoveParams,
    MobCancelAllWorkParams,
    MobCancelWorkParams,
    MobCreateParams,
    MobCreateResult,
    MobDefinitionInput,
    MobEnsureMemberOutcomeWire,
    MobEnsureMemberParams,
    MobEnsureMemberResult,
    MobLifecycleParams,
    MobListMembersMatchingParams,
    MobListMembersMatchingResult,
    MobMemberFilterWire,
    MobMemberListEntryWire,
    MobMemberSendParams,
    MobMemberSendResult,
    MobMemberSpecWire,
    MobPeerTarget,
    MobReconcileFailureWire,
    MobReconcileOptionsWire,
    MobReconcileParams,
    MobReconcileReportWire,
    MobReconcileResult,
    MobSpawnReceiptWire,
    MobSubmitWorkParams,
    MobSubmitWorkResult,
    MobUnwireParams,
    MobUnwireResult,
    MobWireParams,
    MobWireResult,
    ModelsCatalogResponse,
    PeerResponseTerminalStatusWire,
    ProviderCatalog,
    RealtimeActionResult,
    RealtimeAudioChunk,
    RealtimeAudioFormat,
    RealtimeBargeInTruncateFrame,
    RealtimeCapabilities,
    RealtimeCapabilitiesParams,
    RealtimeCapabilitiesResult,
    RealtimeChannelClosedFrame,
    RealtimeChannelConfig,
    RealtimeChannelErrorFrame,
    RealtimeChannelEventFrame,
    RealtimeChannelInputFrame,
    RealtimeChannelOpenFrame,
    RealtimeChannelOpenedFrame,
    RealtimeChannelRole,
    RealtimeChannelState,
    RealtimeChannelStatus,
    RealtimeChannelStatusFrame,
    RealtimeChannelTarget,
    RealtimeClientFrame,
    RealtimeErrorCode,
    RealtimeErrorDetails,
    RealtimeEvent,
    RealtimeInputChunk,
    RealtimeInputKind,
    RealtimeOpenInfo,
    RealtimeOpenRequest,
    RealtimeOutputChunk,
    RealtimeOutputKind,
    RealtimeProtocolVersion,
    RealtimeReconnectPolicy,
    RealtimeServerFrame,
    RealtimeStatusParams,
    RealtimeStatusResult,
    RealtimeTextChunk,
    RealtimeTextDelta,
    RealtimeTurningMode,
    RealtimeVideoChunk,
    RuntimeAcceptOutcomeType,
    RuntimeAcceptResult,
    RuntimeRealtimeAttachmentStatusParams,
    RuntimeRealtimeAttachmentStatusResult,
    ScheduleIdParams,
    ScheduleListResult,
    ScheduleOccurrencesParams,
    ScheduleOccurrencesResult,
    SessionExternalEventEnvelope,
    SessionPeerResponseTerminalParams,
    SkillEntry,
    SkillInspectResponse,
    SkillListResponse,
    SkillsParams,
    StructuredOutputParams,
    ToolCallTimeoutContext,
    UpdateScheduleParams,
    WireAgentRuntimeId,
    WireAssistantBlock,
    // Phase 4c — connection/auth wire types.
    WireAuthError,
    WireAuthProfile,
    WireAuthProfileCleared,
    WireAuthProfileCreated,
    WireAuthProfileDetail,
    WireAuthProfilesList,
    WireAuthStatus,
    WireAuthStatusDetail,
    WireBackendProfile,
    WireBindingIdentity,
    WireConnectionRef,
    WireContentBlock,
    WireContentInput,
    WireDeviceStart,
    WireEvent,
    WireHandlingMode,
    WireInputLifecycleState,
    WireInputState,
    WireInputStateHistoryEntry,
    WireLoginReady,
    WireLoginStart,
    WireMemberRef,
    WireMemberRefError,
    WireMemberState,
    WireMobBackendKind,
    WireMobLifecycleAction,
    WireMobMemberStatus,
    WireMobRuntimeMode,
    WireModelBetaHeader,
    WireModelProfile,
    WireModelTier,
    WireProviderBinding,
    WireProviderMeta,
    WireRealmConnectionSet,
    WireRealmList,
    WireRealmSummary,
    WireRealtimeAttachmentStatus,
    WireRenderClass,
    WireRenderMetadata,
    WireRenderSalience,
    WireRunResult,
    WireRuntimeBinding,
    WireRuntimeState,
    WireSessionHistory,
    WireSessionInfo,
    WireSessionMessage,
    WireSessionSummary,
    WireStopReason,
    WireToolCall,
    WireToolResult,
    WireToolResultContent,
    WireTrustedPeerSpec,
    WireUsage,
    WireWorkOrigin,
};
