#![recursion_limit = "2048"]

//! Meerkat contracts — canonical wire types, surface schemas, and error contracts.
//!
//! This crate is the single source of truth for all wire-facing types.
//! Surface crates (RPC, REST, MCP, CLI) consume these types directly.

pub mod capability;
pub mod error;
pub mod event_catalog;
pub mod protocol;
pub mod request_lifecycle;
pub mod rest_catalog;
pub mod rpc_catalog;
pub mod session_locator;
pub mod version;
pub mod wire;

// Schema emission is a host-side concern (the `emit-schemas` binary); some
// emitted entries reference host-only types (`meerkat_core::ConfigEnvelope`),
// so the module is additionally gated off wasm32.
#[cfg(all(feature = "schema", not(target_arch = "wasm32")))]
pub mod emit;

// Re-exports for convenience
pub use capability::{
    CapabilitiesResponse, CapabilityEntry, CapabilityId, CapabilityRegistration, CapabilityScope,
    CapabilityStatus, available_capabilities, build_capabilities, resolve_capabilities,
};
pub use error::{CapabilityHint, ErrorCategory, ErrorCode, WireError};
pub use event_catalog::KNOWN_AGENT_EVENT_TYPES;
pub use meerkat_core::{
    ExecutionPlacement, ExecutionPlacementIdentity, SessionForkResult,
    TranscriptEditRunningBehavior, TranscriptReplacement,
};
pub use protocol::Protocol;
pub use request_lifecycle::{
    RequestLifecycle, RpcRequestLifecycleRule, WireInitialTurn, rpc_request_lifecycle,
};
pub use rest_catalog::{
    RestOperationDescriptor, RestPathDescriptor, rest_documented_paths, rest_path_catalog,
};
pub use rpc_catalog::{
    RpcMethodCatalogOptions, RpcMethodDescriptor, RpcNotificationDescriptor, rpc_method_catalog,
    rpc_method_names, rpc_notification_catalog, rpc_notification_names,
};
pub use session_locator::{SessionLocator, SessionLocatorError, format_session_ref};
pub use version::ContractVersion;
pub use wire::CallbackToolDefinition;
#[cfg(not(target_arch = "wasm32"))]
pub use wire::ConfigWriteResult;
pub use wire::jobs::*;
pub use wire::supervisor_bridge::{
    BridgeAck, BridgeBindPayload, BridgeBindResponse, BridgeCapabilities, BridgeCommand,
    BridgeCommandDecodeError, BridgeDeliveryOutcome, BridgeDeliveryPayload,
    BridgeDeliveryRejectionCause, BridgeDeliveryResponse, BridgeDestroyResponse,
    BridgeDirectMemberFence, BridgeDirectMemberFenceEvidence, BridgeDirectMemberIncarnation,
    BridgeDirectRuntimeSessionToken, BridgeEventCursor, BridgeHardCancelPayload,
    BridgeHostBindPayload, BridgeHostBindResponse, BridgeHostBootstrapProof,
    BridgeHostMemberRecord, BridgeHostRebindPayload, BridgeHostReboundResponse,
    BridgeHostRuntimeIncarnation, BridgeHostStatusPayload, BridgeHostStatusResponse,
    BridgeInterruptPayload, BridgeLiveChannelPayload, BridgeLiveControlOutcome,
    BridgeLiveControlPayload, BridgeLiveControlVerb, BridgeLiveControlledResponse,
    BridgeLiveOpenPayload, BridgeLiveOpenedResponse, BridgeLiveStatusPayload,
    BridgeMaterializePayload, BridgeMaterializedResponse, BridgeMemberEventsPage,
    BridgeMemberHistoryPage, BridgeMemberIncarnation, BridgeMemberOperatorPayload,
    BridgeMemberReleasedResponse, BridgeMemberRuntimeState, BridgeMobPeerOverlayHandoff,
    BridgeObservationResponse, BridgeOutboundTaintPayload, BridgeOutboundTaintTarget,
    BridgeOutcomeTracking, BridgePeerConnectivity, BridgePeerSpec, BridgePeerTrustPayload,
    BridgePeerWiringPayload, BridgePollEventsPayload, BridgeProtocolVersion,
    BridgeReadHistoryPayload, BridgeReleasePayload, BridgeReply, BridgeRetireOutcome,
    BridgeRetirePayload, BridgeRetireResponse, BridgeSupervisorDelivery, BridgeSupervisorPayload,
    BridgeSupervisorRotationObservation, BridgeSupervisorRotationObserve,
    BridgeSupervisorRotationOperationReceipt, BridgeSupervisorRotationPendingPhase,
    BridgeSupervisorRotationRejectionCause, BridgeSupervisorRotationRejectionReceipt,
    BridgeSupervisorRotationState, BridgeSupervisorRotationSubmit,
    BridgeSupervisorRotationTargetReceipt, BridgeTurnCorrelation, BridgeTurnDirective,
    BridgeTurnOutcomeRecord, ConnectionTargetErrorKind, MaterializeLaunchMode,
    MaterializeLaunchOutcome, MemberBuildRejection, MemberEventCursor, MemberOperatorOp,
    MemberOperatorOutcome, MemberOperatorReply, MemberOperatorSpawnSpec, MemberSessionDisposal,
    RuntimeReleaseCause, SUPERVISOR_BRIDGE_CURRENT_PROTOCOL_VERSION,
    SUPERVISOR_BRIDGE_DEFAULT_PROTOCOL_VERSION, SUPERVISOR_BRIDGE_INTENT,
    SUPERVISOR_BRIDGE_PROTOCOL_VERSION, SUPERVISOR_BRIDGE_SUPPORTED_PROTOCOL_VERSIONS,
    SupervisorRotationOperationId, UnsupportedBridgeProtocolVersion, WireEventRow,
    WireFlowTurnOutcome, WireHostBindingDescriptor, WireHostBindingDescriptorKind, WireOpaqueJson,
    decode_bridge_command, supervisor_bridge_current_protocol_version,
    supervisor_bridge_default_protocol_version, supervisor_bridge_protocol_version_supported,
    supervisor_bridge_supported_protocol_versions,
};
pub use wire::{
    ActivateInstructionParams,
    ApprovalActionKind,
    ApprovalDecideParams,
    ApprovalDecision,
    ApprovalDecisionRecord,
    ApprovalGetParams,
    ApprovalId,
    ApprovalListFilter,
    ApprovalListParams,
    ApprovalListResult,
    ApprovalMemberRef,
    ApprovalMobRef,
    ApprovalOwnerRef,
    ApprovalPrincipalId,
    ApprovalProposedAction,
    ApprovalRecord,
    ApprovalRequest,
    ApprovalRequestParams,
    ApprovalResourceId,
    ApprovalResourceKind,
    ApprovalResourceRef,
    ApprovalRisk,
    ApprovalStatus,
    ArtifactDownloadParams,
    ArtifactDownloadResult,
    ArtifactIdParams,
    ArtifactListParams,
    ArtifactListResult,
    AuthGrant,
    BindingIdParams,
    CatalogModelEntry,
    CommsChecksumTokenParams,
    CommsChecksumTokenResult,
    CommsChecksumTokenResultIntent,
    CommsCommandError,
    CommsCommandProjectionError,
    CommsCommandRequest,
    CommsParams,
    CommsPeerEntry,
    CommsPeerLifecycleParams,
    CommsPeerRequestIntent,
    CommsPeerRequestParams,
    CommsPeerResponseResult,
    CommsPeerUnreachableReason,
    CommsPeersParams,
    CommsPeersResult,
    CommsSendErrorData,
    CommsSendParams,
    CommsSendResult,
    ConfigPatchParams,
    ConfigSetParams,
    CoreCreateParams,
    CreateProfileParams,
    DeviceCompleteParams,
    DeviceStartParams,
    EventReplayCursor,
    EventReplayCursorError,
    EventReplayEnvelope,
    EventReplayEventId,
    EventReplayScope,
    EventsLatestCursorParams,
    EventsLatestCursorResult,
    EventsListSinceParams,
    EventsListSinceResult,
    EventsSnapshotBody,
    EventsSnapshotParams,
    EventsSnapshotResult,
    ExportAtifParams,
    ForkSessionAtParams,
    ForkSessionReplaceParams,
    GrantAction,
    GrantScope,
    HelpExecutionMode,
    HelpRequest,
    HelpResponse,
    HookParams,
    InterruptResult,
    LIVE_CLIENT_CONTEXT_V1_CAPABILITY,
    LIVE_EXECUTION_IDENTITY_V1_CAPABILITY,
    LIVE_FUNCTION_BRIDGE_V1_CAPABILITY,
    ListSchedulesParams,
    ListSessionTranscriptRevisionsParams,
    LiveAssistantOutputAvailableParams,
    LiveChannelParams,
    LiveCloseResult,
    LiveCloseStatus,
    LiveCommitInputParams,
    LiveCommitInputResult,
    LiveCommitInputStatus,
    LiveInputChunkWire,
    LiveInterruptResult,
    LiveInterruptStatus,
    LiveOpenParams,
    LiveOpenResult,
    LiveOpenTransport,
    LivePlaybackCompleteParams,
    LivePlaybackCompleteResult,
    LivePlaybackCompleteStatus,
    LiveRefreshResult,
    LiveRefreshStatus,
    LiveSendInputErrorData,
    LiveSendInputParams,
    LiveSendInputResult,
    LiveSendInputStatus,
    LiveStatusResult,
    LiveTruncateParams,
    LiveTruncateResult,
    LiveTruncateStatus,
    LiveWebrtcAnswerParams,
    LiveWebrtcAnswerResult,
    LoginCompleteParams,
    LoginStartParams,
    McpAddParams,
    McpLiveOpResponse,
    McpLiveOpStatus,
    McpLiveOperation,
    McpReloadParams,
    McpRemoveParams,
    MobAdoptMemberIdentityDeclarationParams,
    MobAdoptMemberIdentityDeclarationResult,
    MobAppendSystemContextParams,
    MobAppendSystemContextResult,
    MobApplyMemberToolDeclarationParams,
    MobApplyMemberToolDeclarationResult,
    MobBindHostParams,
    MobBindHostResult,
    MobBoundedHelperResult,
    MobBoundedHelperResultStatus,
    MobCancelAllWorkParams,
    MobCancelAllWorkResult,
    MobCancelWorkParams,
    MobCancelWorkResult,
    MobConcludeObjectiveParams,
    MobConcludeObjectiveResult,
    MobCreateParams,
    MobCreateResult,
    MobDefinitionInput,
    MobDestroyResult,
    MobEnsureMemberOutcomeWire,
    MobEnsureMemberParams,
    MobEnsureMemberResult,
    MobEventsParams,
    MobEventsResult,
    MobFlowCancelParams,
    MobFlowCancelResult,
    MobFlowRunParams,
    MobFlowRunResult,
    MobFlowStatusParams,
    MobFlowStatusResult,
    MobFlowsResult,
    MobForceCancelResult,
    MobForkHelperParams,
    MobGrantScopesParams,
    MobGrantScopesResult,
    MobGrantsResult,
    MobHardCancelParams,
    MobHardCancelResult,
    MobHelperResult,
    MobHostStatus,
    MobHostsResult,
    MobIdParams,
    MobIngressInteractionParams,
    MobIngressInteractionResult,
    MobLifecycleParams,
    MobLifecycleResult,
    MobListMembersMatchingParams,
    MobListMembersMatchingResult,
    MobListResult,
    MobMemberFilterWire,
    MobMemberHistoryParams,
    MobMemberHistoryResult,
    MobMemberListEntryWire,
    MobMemberLiveChannelParams,
    MobMemberLiveControlParams,
    MobMemberLiveOpenParams,
    MobMemberLiveStatusParams,
    MobMemberParams,
    MobMemberSendParams,
    MobMemberSendResult,
    MobMemberSpecWire,
    MobMemberStatusResult,
    MobMemberToolDeclarationParams,
    MobMemberToolDeclarationResult,
    MobMembersResult,
    MobPeerTarget,
    MobProfileCreateParams,
    MobProfileDeleteParams,
    MobProfileDeleteResult,
    MobProfileInput,
    MobProfileListResult,
    MobProfileLookupResult,
    MobProfileNameParams,
    MobProfileUpdateParams,
    MobReconcileFailureWire,
    MobReconcileOptionsWire,
    MobReconcileParams,
    MobReconcileReportWire,
    MobReconcileResult,
    MobResolveIdentityConvergenceBlockParams,
    MobResolveIdentityConvergenceBlockResult,
    MobRespawnParams,
    MobRespawnReceipt,
    MobRespawnResult,
    MobRetireResult,
    MobRevokeHostParams,
    MobRevokeHostResult,
    MobRevokeScopesParams,
    MobRevokeScopesResult,
    MobRotateSupervisorResult,
    MobRouteInstallsResult,
    MobRunParams,
    MobRunResult,
    MobRunResultParams,
    MobSnapshotResult,
    MobSpawnHelperParams,
    MobSpawnManyFailedResult,
    MobSpawnManyFailureCause,
    MobSpawnManyParams,
    MobSpawnManyResult,
    MobSpawnManyResultEntry,
    MobSpawnManyResultPayload,
    MobSpawnManyResultStatus,
    MobSpawnManySpawnedResult,
    MobSpawnParams,
    MobSpawnReceiptWire,
    MobSpawnResult,
    MobSpawnSpecParams,
    MobStatusResult,
    MobStreamCloseParams,
    MobStreamCloseResult,
    MobStreamOpenParams,
    MobStreamOpenResult,
    MobSubmitWorkParams,
    MobSubmitWorkResult,
    MobTurnStartParams,
    MobUnwireParams,
    MobUnwireResult,
    MobWaitMembersResult,
    MobWaitParams,
    MobWireMembersBatchEdge,
    MobWireMembersBatchParams,
    MobWireMembersBatchResult,
    MobWireParams,
    MobWireResult,
    ModelsCatalogResponse,
    Occurrence,
    PeerAddress,
    PeerCapabilitySet,
    PeerDirectoryEntry,
    PeerDirectoryListing,
    PeerDirectorySource,
    PeerId,
    PeerResponseTerminalStatusWire,
    PeerSendability,
    PeerTransport,
    PrincipalId,
    PrincipalKind,
    PrincipalRef,
    ProviderCatalog,
    ProvisionApiKeyParams,
    ReadInstructionActivationsParams,
    ReadSessionTranscriptRevisionParams,
    RealmIdParams,
    RealtimeAudioChunk,
    RealtimeAudioFormat,
    RealtimeCapabilities,
    RealtimeImageChunk,
    RealtimeInputChunk,
    RealtimeInputKind,
    RealtimeOutputKind,
    RealtimeTextChunk,
    RealtimeTurningMode,
    RealtimeVideoChunk,
    RestoreSessionTranscriptRevisionParams,
    RevisionId,
    RevisionSelector,
    RewriteSessionTranscriptParams,
    RuntimeAcceptOutcomeType,
    RuntimeAcceptResult,
    RuntimeHostCapabilities,
    RuntimeHostEndpointProjection,
    RuntimeHostFeatureFlags,
    RuntimeHostHealth,
    RuntimeHostHealthStatus,
    RuntimeHostIdScope,
    RuntimeHostInfo,
    RuntimeHostRealmProjection,
    RuntimeStateResult,
    Schedule,
    ScheduleIdParams,
    ScheduleListResult,
    ScheduleOccurrencesParams,
    ScheduleOccurrencesResult,
    SendTaintOverride,
    SenderContentTaint,
    ServerCapabilities,
    ServerInfo,
    SessionExternalEventEnvelope,
    SessionExternalEventParams,
    SessionInputStateParams,
    SessionInputStateResult,
    SessionInputStateSelector,
    SessionPeerResponseTerminalParams,
    SessionStreamCloseParams,
    SessionStreamCloseResult,
    SessionStreamOpenParams,
    SessionStreamOpenResult,
    SkillEntry,
    SkillInspectResponse,
    SkillListResponse,
    SkillSourceProvenance,
    SkillsParams,
    StreamReadStatus,
    StructuredOutputParams,
    SupervisorRotationIncompleteDataWire,
    SupervisorRotationIncompleteDetailsWire,
    SupervisorRotationIncompleteKind,
    SupervisorRotationReportWire,
    SupervisorRotationRetryAuthority,
    SupervisorRotationRetryScope,
    TranscriptRewriteMessage,
    UpdateScheduleParams,
    UpdateSystemPromptParams,
    VisibilityClass,
    WireAgentRuntimeId,
    WireAppendSystemContextStatus,
    WireAssistantBlock,
    WireAssistantImageRef,
    WireAuthBindingRef,
    // Phase 4c — auth-binding wire types.
    WireAuthError,
    WireAuthProfile,
    WireAuthProfileCleared,
    WireAuthProfileCreated,
    WireAuthProfileDetail,
    WireAuthProfilesList,
    WireAuthStatus,
    WireAuthStatusDetail,
    WireBackendProfile,
    WireBindingIdentity,
    WireCallbackPending,
    WireCallbackPendingStatus,
    WireCallbackToolSetDeclaration,
    WireContentBlock,
    WireContentInput,
    WireControlScope,
    WireDesiredLocalCallbackTool,
    WireDeviceCompleteResult,
    WireDeviceStart,
    WireEvent,
    WireGenerateImageExecutionPlan,
    WireGenerateImageRequest,
    WireGrantRecord,
    WireHandlingMode,
    WireHistoryRow,
    WireHostBindPhase,
    WireHostCapabilityFlags,
    WireHostRef,
    WireHostUnavailableDetail,
    WireIdentityConvergenceCondition,
    WireIdentityConvergenceMode,
    WireIdentityConvergenceResolutionOutcome,
    WireIdentityConvergenceStatus,
    WireIdentityReconcileDecision,
    WireImageGenerationToolResult,
    WireImageOperationPhase,
    WireInputLifecycleState,
    WireInputState,
    WireInputStateHistoryEntry,
    WireInterruptOutcome,
    WireLiveAdapterErrorCode,
    WireLiveAdapterObservation,
    WireLiveAdapterStatus,
    WireLiveChannelCapabilities,
    WireLiveChannelCloseFailure,
    WireLiveChannelRefreshFailure,
    WireLiveCloseFailure,
    WireLiveConfigPropagationReport,
    WireLiveConfigRejectionReason,
    WireLiveContinuityMode,
    WireLiveDegradationReason,
    WireLiveExecutionIdentityOverrideV1,
    WireLiveExecutionIdentityVersion,
    WireLiveHotSwapSkip,
    WireLiveHotSwapSkipReason,
    WireLiveRefreshFailure,
    WireLiveResponseModality,
    WireLiveSwapFailure,
    WireLiveTransportBootstrap,
    WireLoginReady,
    WireLoginStart,
    WireMemberHealthClass,
    WireMemberHistoryPageBody,
    WireMemberLifecycleCapabilities,
    WireMemberProgressEvent,
    WireMemberProgressSnapshot,
    WireMemberRef,
    WireMemberRefError,
    WireMemberRunState,
    WireMemberToolAccessConstraint,
    WireMemberToolAccessDeclaration,
    WireMemberToolCommitOutcome,
    WireMemberToolDeclaration,
    WireMobBackendKind,
    WireMobError,
    WireMobErrorDetail,
    WireMobLifecycleAction,
    WireMobLifecycleStatus,
    WireMobMemberStatus,
    WireMobProfile,
    WireMobReconcileStage,
    WireMobRespawnOutcome,
    WireMobResumeOverrideField,
    WireMobRun,
    WireMobRunAccounting,
    WireMobRunMemberAccounting,
    WireMobRunResultEnvelope,
    WireMobRunStatus,
    WireMobRunUsageAttribution,
    WireMobRuntimeMode,
    WireMobToolConfig,
    WireMobWireAction,
    WireModelBetaHeader,
    WireModelProfile,
    WireModelReleaseStage,
    WireModelRoutingApprovalPhase,
    WireModelTier,
    WirePeerConnectivity,
    WirePeerConnectivitySnapshot,
    WirePendingToolCall,
    WireProjectionProvenance,
    WirePromptInput,
    WireProviderBinding,
    WireProviderMeta,
    WireProvisionApiKeyResult,
    WireReachability,
    WireRealmConnectionSet,
    WireRealmList,
    WireRealmSummary,
    WireRealtimeTranscriptEvent,
    WireRenderClass,
    WireRenderMetadata,
    WireRenderSalience,
    WireResolvedModelCapabilities,
    WireRouteInstallObligation,
    WireRunResult,
    WireRuntimeBinding,
    WireRuntimeState,
    WireScopeDeniedDetail,
    WireScopedModelOverride,
    WireSessionHistory,
    WireSessionInfo,
    WireSessionMessage,
    WireSessionModelRoutingStatus,
    WireSessionSummary,
    WireSessionTranscriptRevision,
    WireSessionTranscriptRevisionEntry,
    WireSessionTranscriptRevisionList,
    WireStaleCursorDetail,
    WireStaleFenceDetail,
    WireStopReason,
    WireSwitchTurnControlResult,
    WireSwitchTurnIntent,
    WireSwitchTurnPhase,
    WireSystemMessageIdentity,
    WireToolResult,
    WireToolResultContent,
    WireTrustedPeerIdentity,
    WireTrustedPeerSpec,
    WireUnreachablePeer,
    WireUsage,
    WireWorkExecutionLifecyclePhase,
    WireWorkGraphFlowExecutionBinding,
    WireWorkGraphFlowWorkRef,
    WireWorkOrigin,
    WorkEventsResult,
    WorkItemsResult,
};
