//! Durable detached-job domain.
//!
//! Lifecycle semantics are generated by `DetachedJobMachine`. Stores provide
//! uniqueness, atomic compare-and-swap, and outbox atomicity only.

// On wasm32, use tokio_with_wasm as a drop-in replacement for tokio.
#[cfg(target_arch = "wasm32")]
pub mod tokio {
    pub use tokio_with_wasm::alias::*;
}

mod error;
mod predicate;
mod service;
#[cfg(not(target_arch = "wasm32"))]
mod sqlite_store;
mod store;
mod types;

pub mod machines;

pub use error::DetachedJobError;
pub use predicate::{
    PredicateCheckpoint, PredicateComparison, PredicateEvaluation, PredicateObservation,
    PredicatePollingPolicy, PredicateSource, PredicateWatch, PredicateWatchError, PredicateWatchId,
    ScheduleIdRef,
};
pub use service::DetachedJobService;
#[cfg(not(target_arch = "wasm32"))]
pub use sqlite_store::{JOBS_DOMAIN, SqliteDetachedJobStore};
pub use store::{
    DetachedJobStore, InsertJobOutcome, MemoryDetachedJobStore, MemoryDetachedJobStoreSnapshot,
    StoredJob,
};
pub use types::{
    AttemptClaim, AttemptClaimReceipt, AttemptId, AttemptWriteAuthority, CanonicalArgumentsHash,
    CheckpointRef, ExecutionIntentId, FenceToken, InteractionLineageId, JobDeliveryKind,
    JobDescription, JobFailureCode, JobHealthCondition, JobHealthSnapshot, JobId, JobNotification,
    JobNotificationReceipt, JobOutboxEntry, JobOutboxPayload, JobPhase, JobProgress,
    JobProgressKind, JobReceipt, JobReference, JobResultRef, JobSnapshot, JobSpec,
    JobSubmissionKey, JobSubscription, JobSubscriptionId, JobTerminalKind, JobTerminalResult,
    NotificationId, NotificationIdempotencyKey, OriginMemberId, PredicateEvaluationReceipt,
    RestartClass, RunnerHandleRef, RunnerIdentity, RunnerSpecificationRef, ToolIdentity, WorkerId,
};

#[doc(hidden)]
#[cfg(feature = "machine-schema-exports")]
pub mod machine_schema_exports {
    pub fn detached_job_schema() -> meerkat_machine_schema::MachineSchema {
        meerkat_machine_schema::catalog::dsl::detached_job_schema_metadata()
            .attach_to(crate::machines::detached_job::DetachedJobMachineState::schema())
    }
}
