//! Durable detached-job domain.
//!
//! Lifecycle semantics are generated by `DetachedJobMachine`. Stores provide
//! uniqueness, atomic compare-and-swap, and outbox atomicity only.

mod error;
mod service;
#[cfg(not(target_arch = "wasm32"))]
mod sqlite_store;
mod store;
mod types;

pub mod machines;

pub use error::DetachedJobError;
pub use service::DetachedJobService;
#[cfg(not(target_arch = "wasm32"))]
pub use sqlite_store::{JOBS_DOMAIN, SqliteDetachedJobStore};
pub use store::{
    DetachedJobStore, InsertJobOutcome, MemoryDetachedJobStore, MemoryDetachedJobStoreSnapshot,
    StoredJob,
};
pub use types::{
    AttemptClaim, AttemptClaimReceipt, AttemptId, AttemptWriteAuthority, CanonicalArgumentsHash,
    CheckpointRef, ExecutionIntentId, FenceToken, InteractionLineageId, JobFailureCode, JobId,
    JobOutboxEntry, JobPhase, JobProgress, JobReceipt, JobResultRef, JobSnapshot, JobSpec,
    JobSubmissionKey, JobTerminalKind, JobTerminalResult, OriginMemberId, RestartClass,
    RunnerHandleRef, RunnerIdentity, RunnerSpecificationRef, ToolIdentity, WorkerId,
};

#[doc(hidden)]
#[cfg(feature = "machine-schema-exports")]
pub mod machine_schema_exports {
    pub fn detached_job_schema() -> meerkat_machine_schema::MachineSchema {
        meerkat_machine_schema::catalog::dsl::detached_job_schema_metadata()
            .attach_to(crate::machines::detached_job::DetachedJobMachineState::schema())
    }
}
