//! Release-boundary corpus: realms written by published pre-0.8.10 `rkat`
//! binaries must survive the explicit offline storage bridge.
//!
//! The 0.8.23 report was a user who followed the product's own remedy into a
//! dead end. A normal run told them to run
//! `storage migrate --apply --bridge-pre-0-8-10`; the bridge then refused
//! their realm because the oldest catalog it recognized was younger than the
//! realms it was named for. Nothing in the tree exercised the bridge against
//! bytes a released 0.7.x binary actually wrote, so the gap shipped.
//!
//! Everything here runs against `tests/fixtures/v0_7_x_pre_ledger_realm`,
//! minted by `mint_pre_ledger_fixture.py` from the published release assets.
//! It never constructs a legacy schema from current source: a hand-built
//! shape would only prove that this file and `sqlite.rs` agree with each
//! other.
//!
//! Each release contributes one or more *captures*. `bootstrap-only` is a run
//! with no credentials, which dies before admitting anything and leaves schema
//! plus a single `runtime_states` row. `attempted-turn` is a run with a dummy
//! provider key and an explicit model, which admits the operator input,
//! persists it, and dies at the provider call. Only the second kind carries
//! `runtime_input_states` rows, and only the second kind can therefore reach
//! the bridge's row-preparation callback. A corpus made solely of the first
//! kind can pass every assertion below while never executing the code that
//! decides whether a real operator's realm opens.

#![cfg(feature = "sqlite-store")]
#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct PreLedgerFixtureManifest {
    schema_version: u32,
    fixture_id: String,
    data_classification: String,
    realm_id: String,
    releases: Vec<PreLedgerRelease>,
}

#[derive(Debug, Deserialize)]
struct PreLedgerRelease {
    meerkat_version: String,
    source_release: String,
    release_asset: String,
    release_asset_sha256: String,
    binary_version_output: String,
    binary_sha256: String,
    current_source_build: bool,
    captures: Vec<PreLedgerCapture>,
}

#[derive(Debug, Deserialize)]
struct PreLedgerCapture {
    capture_id: String,
    root: String,
    payloads: Vec<PreLedgerPayload>,
    sessions_sqlite_catalog: Vec<PreLedgerCatalogEntry>,
    sessions_sqlite_row_counts: BTreeMap<String, i64>,
    workgraph_sqlite_row_counts: BTreeMap<String, i64>,
    runtime_input_state_rows: Vec<PreLedgerInputRow>,
    carries_runtime_input_rows: bool,
}

#[derive(Debug, Deserialize)]
struct PreLedgerPayload {
    path: String,
    bytes: u64,
    sha256: String,
}

#[derive(Debug, Deserialize, PartialEq, Eq, PartialOrd, Ord, Clone)]
struct PreLedgerCatalogEntry {
    #[serde(rename = "type")]
    kind: String,
    name: String,
    sql: String,
}

/// One durable runtime input row, described by identity rather than by count.
/// A count alone would let a corpus claim to be row-bearing while carrying
/// something the callback never sees.
#[derive(Debug, Deserialize, PartialEq, Eq, Clone)]
struct PreLedgerInputRow {
    runtime_id: String,
    input_id: String,
    stored_input_state_version: u64,
    current_state: String,
    input_type: String,
    state_json_sha256: String,
}

/// Exactly the runtime tables the whole 0.7.x line created. If this list ever
/// needs editing to make a test pass, the fixture changed, not the contract.
const PRE_LEDGER_RUNTIME_TABLES: &[&str] = &[
    "runtime_auth_oauth_flow_state",
    "runtime_boundary_receipts",
    "runtime_input_states",
    "runtime_ops_lifecycle",
    "runtime_projection_quarantine",
    "runtime_session_snapshots",
    "runtime_states",
];

fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/v0_7_x_pre_ledger_realm/corpus")
}

fn sha256_bytes(bytes: &[u8]) -> String {
    use sha2::{Digest as _, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

fn sha256_file(path: &Path) -> String {
    let bytes = std::fs::read(path)
        .unwrap_or_else(|error| panic!("read {} for hashing: {error}", path.display()));
    sha256_bytes(&bytes)
}

fn load_manifest() -> PreLedgerFixtureManifest {
    let path = corpus_root().join("fixture-manifest.json");
    let bytes = std::fs::read(&path).unwrap_or_else(|error| {
        panic!(
            "RELEASE BLOCKER: pre-ledger 0.7.x realm corpus is absent or unreadable at {}: \
             {error}; re-mint it with \
             tests/fixtures/v0_7_x_pre_ledger_realm/mint_pre_ledger_fixture.py using published \
             release assets, never current-source generated bytes",
            path.display()
        )
    });
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|error| panic!("pre-ledger fixture manifest is invalid: {error}"))
}

fn capture_root(capture: &PreLedgerCapture) -> PathBuf {
    corpus_root().join(&capture.root)
}

/// Every file under `root`, as `/`-joined paths relative to it.
fn relative_files(root: &Path) -> BTreeSet<String> {
    fn walk(base: &Path, current: &Path, found: &mut BTreeSet<String>) {
        let entries = std::fs::read_dir(current)
            .unwrap_or_else(|error| panic!("read {}: {error}", current.display()));
        for entry in entries {
            let entry = entry
                .unwrap_or_else(|error| panic!("read entry in {}: {error}", current.display()));
            let path = entry.path();
            if path.is_dir() {
                walk(base, &path, found);
            } else {
                let relative = path.strip_prefix(base).unwrap_or_else(|error| {
                    panic!(
                        "{} is not under {}: {error}",
                        path.display(),
                        base.display()
                    )
                });
                found.insert(
                    relative
                        .components()
                        .map(|component| component.as_os_str().to_string_lossy().into_owned())
                        .collect::<Vec<_>>()
                        .join("/"),
                );
            }
        }
    }
    let mut found = BTreeSet::new();
    walk(root, root, &mut found);
    found
}

/// Copy a committed database out of the corpus before opening it. Opening it
/// in place would let SQLite create sidecars beside bytes that must stay
/// exactly as the published writer left them.
fn with_corpus_database<T>(
    source: &Path,
    profile: meerkat_sqlite::ConnectionProfile,
    body: impl FnOnce(&mut rusqlite::Connection) -> T,
) -> T {
    let scratch = tempfile::tempdir().expect("tempdir");
    let database = scratch.path().join(
        source
            .file_name()
            .unwrap_or_else(|| panic!("{} has no file name", source.display())),
    );
    std::fs::copy(source, &database)
        .unwrap_or_else(|error| panic!("copy {}: {error}", source.display()));
    let mut conn = meerkat_sqlite::open(&database, profile)
        .unwrap_or_else(|error| panic!("open {}: {error}", database.display()));
    body(&mut conn)
}

fn read_row_counts(source: &Path) -> BTreeMap<String, i64> {
    with_corpus_database(
        source,
        meerkat_sqlite::ConnectionProfile::ReadOnly,
        |conn| {
            let tables = {
                let mut statement = conn
                    .prepare(
                        "SELECT name FROM sqlite_master WHERE type = 'table' \
                     AND name NOT LIKE 'sqlite_%' ORDER BY name",
                    )
                    .expect("prepare catalog query");
                statement
                    .query_map([], |row| row.get::<_, String>(0))
                    .expect("query catalog")
                    .collect::<Result<Vec<_>, _>>()
                    .expect("collect catalog")
            };
            let mut counts = BTreeMap::new();
            for table in tables {
                let count: i64 = conn
                    .query_row(&format!("SELECT COUNT(*) FROM \"{table}\""), [], |row| {
                        row.get(0)
                    })
                    .unwrap_or_else(|error| panic!("count {table}: {error}"));
                counts.insert(table, count);
            }
            counts
        },
    )
}

fn read_runtime_input_rows(source: &Path) -> Vec<PreLedgerInputRow> {
    with_corpus_database(
        source,
        meerkat_sqlite::ConnectionProfile::ReadOnly,
        |conn| {
            let mut statement = conn
                .prepare(
                    "SELECT runtime_id, input_id, state_json FROM runtime_input_states \
                 ORDER BY runtime_id, input_id",
                )
                .expect("prepare input-state query");
            statement
                .query_map([], |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, String>(1)?,
                        row.get::<_, Vec<u8>>(2)?,
                    ))
                })
                .expect("query input states")
                .map(|row| {
                    let (runtime_id, input_id, state) = row.expect("read input-state row");
                    let decoded: serde_json::Value =
                        serde_json::from_slice(&state).expect("input state is JSON");
                    PreLedgerInputRow {
                        stored_input_state_version: decoded
                            .get("stored_input_state_version")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or_else(|| panic!("{runtime_id}/{input_id} has no version")),
                        current_state: decoded
                            .get("current_state")
                            .and_then(serde_json::Value::as_str)
                            .unwrap_or_default()
                            .to_string(),
                        input_type: decoded
                            .get("persisted_input")
                            .and_then(|input| input.get("input_type"))
                            .and_then(serde_json::Value::as_str)
                            .unwrap_or_default()
                            .to_string(),
                        state_json_sha256: sha256_bytes(&state),
                        runtime_id,
                        input_id,
                    }
                })
                .collect::<Vec<_>>()
        },
    )
}

/// Every input row's full decoded JSON, keyed by `runtime_id/input_id`.
///
/// The descriptor type above is deliberately narrow because it is also the
/// manifest's schema. Preservation needs the whole record.
fn read_runtime_input_json(source: &Path) -> BTreeMap<String, serde_json::Value> {
    with_corpus_database(
        source,
        meerkat_sqlite::ConnectionProfile::ReadOnly,
        |conn| {
            let mut statement = conn
                .prepare(
                    "SELECT runtime_id, input_id, state_json FROM runtime_input_states \
                 ORDER BY runtime_id, input_id",
                )
                .expect("prepare input-state query");
            statement
                .query_map([], |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, String>(1)?,
                        row.get::<_, Vec<u8>>(2)?,
                    ))
                })
                .expect("query input states")
                .map(|row| {
                    let (runtime_id, input_id, state) = row.expect("read input-state row");
                    (
                        format!("{runtime_id}/{input_id}"),
                        serde_json::from_slice(&state).expect("input state is JSON"),
                    )
                })
                .collect::<BTreeMap<_, _>>()
        },
    )
}

fn captures(manifest: &PreLedgerFixtureManifest) -> Vec<(&PreLedgerRelease, &PreLedgerCapture)> {
    manifest
        .releases
        .iter()
        .flat_map(|release| {
            release
                .captures
                .iter()
                .map(move |capture| (release, capture))
        })
        .collect()
}

/// Resolve one capture by name.
///
/// Tests that examine a single realm name the capture they mean. Taking
/// whichever capture happens to sort first would silently change a test's
/// subject the next time a capture is added, and the two shapes here answer
/// different questions: `bootstrap-only` bridges today, `attempted-turn` does
/// not.
fn capture_named<'a>(
    manifest: &'a PreLedgerFixtureManifest,
    capture_id: &str,
) -> (&'a PreLedgerRelease, &'a PreLedgerCapture) {
    captures(manifest)
        .into_iter()
        .find(|(_, capture)| capture.capture_id == capture_id)
        .unwrap_or_else(|| panic!("the corpus carries no `{capture_id}` capture"))
}

/// The corpus must stay bound to the published artifacts it came from, and
/// must stay non-empty. A corpus that quietly loses its realms would let every
/// assertion below pass over nothing.
#[test]
fn pre_ledger_corpus_is_bound_to_published_release_artifacts() {
    let manifest = load_manifest();
    assert_eq!(manifest.schema_version, 2);
    assert_eq!(manifest.fixture_id, "meerkat-0.7.x-pre-ledger-realms");
    assert_eq!(
        manifest.data_classification, "synthetic_non_production",
        "production-redacted data is forbidden in a release fixture"
    );
    assert_eq!(manifest.realm_id, "legacy-realm");
    assert!(
        manifest.releases.len() >= 2,
        "the corpus must span more than one published 0.7.x release, found {}",
        manifest.releases.len()
    );

    let mut versions = BTreeSet::new();
    for release in &manifest.releases {
        assert!(
            versions.insert(release.meerkat_version.clone()),
            "duplicate release {} in the corpus",
            release.meerkat_version
        );
        assert!(
            release.meerkat_version.starts_with("0.7."),
            "this corpus is the pre-0.8.0 line, found {}",
            release.meerkat_version
        );
        assert!(
            !release.current_source_build,
            "release {} must be a published artifact, not a current-source build",
            release.meerkat_version
        );
        assert_eq!(
            release.binary_version_output,
            format!("rkat {}", release.meerkat_version),
            "corpus was not written by the published CLI it claims"
        );
        assert_eq!(
            release.source_release,
            format!(
                "https://github.com/lukacf/meerkat/releases/tag/v{}",
                release.meerkat_version
            )
        );
        assert!(
            release
                .release_asset
                .starts_with(&format!("rkat-{}-", release.meerkat_version)),
            "release asset {} does not name version {}",
            release.release_asset,
            release.meerkat_version
        );
        for (label, digest) in [
            ("release asset", &release.release_asset_sha256),
            ("producer binary", &release.binary_sha256),
        ] {
            assert_eq!(
                digest.len(),
                64,
                "{label} SHA-256 for {} has the wrong length",
                release.meerkat_version
            );
            assert!(
                digest
                    .bytes()
                    .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase()),
                "{label} SHA-256 for {} is not lowercase hexadecimal",
                release.meerkat_version
            );
        }

        assert!(
            !release.captures.is_empty(),
            "release {} binds no captures",
            release.meerkat_version
        );
        let mut capture_ids = BTreeSet::new();
        for capture in &release.captures {
            assert!(
                capture_ids.insert(capture.capture_id.clone()),
                "duplicate capture {} for release {}",
                capture.capture_id,
                release.meerkat_version
            );
            assert_eq!(
                capture.root,
                format!("realms/{}/{}", release.meerkat_version, capture.capture_id),
                "capture root does not name its own release and capture"
            );

            let realm = capture_root(capture);
            let mut declared = BTreeSet::new();
            for payload in &capture.payloads {
                let path = realm.join(&payload.path);
                assert_eq!(
                    sha256_file(&path),
                    payload.sha256,
                    "committed bytes of {} differ from their manifest digest",
                    path.display()
                );
                assert_eq!(
                    std::fs::metadata(&path)
                        .unwrap_or_else(|error| panic!("stat {}: {error}", path.display()))
                        .len(),
                    payload.bytes,
                    "committed size of {} differs from its manifest entry",
                    path.display()
                );
                declared.insert(payload.path.clone());
            }
            assert_eq!(
                relative_files(&realm),
                declared,
                "capture {} of release {} carries files the manifest does not bind (a WAL/SHM \
                 sidecar means the corpus was opened in place)",
                capture.capture_id,
                release.meerkat_version
            );
        }
    }
}

/// The corpus reproduces the shape the 0.8.23 report hit: seven runtime tables
/// and no ledger at all. This is the fact the bridge got wrong, so it is
/// asserted directly rather than inferred from a passing migration.
#[test]
fn pre_ledger_corpus_carries_the_unledgered_seven_table_runtime_shape() {
    let manifest = load_manifest();
    for (release, capture) in captures(&manifest) {
        let label = format!("{}/{}", release.meerkat_version, capture.capture_id);
        let catalog = &capture.sessions_sqlite_catalog;
        assert!(
            !catalog
                .iter()
                .any(|entry| entry.name.eq_ignore_ascii_case("meerkat_schema")),
            "capture {label} must have no migration ledger; that is what makes it unledgered"
        );
        let runtime_tables = catalog
            .iter()
            .filter(|entry| entry.kind == "table" && entry.name.starts_with("runtime_"))
            .map(|entry| entry.name.as_str())
            .collect::<BTreeSet<_>>();
        assert_eq!(
            runtime_tables,
            PRE_LEDGER_RUNTIME_TABLES.iter().copied().collect(),
            "capture {label} does not carry the 0.7.x runtime catalog"
        );
        // The two tables the bridge's youngest recognized catalog demanded.
        // Their absence is precisely why the released bridge refused.
        for absent in [
            "runtime_retired_ops_epochs",
            "runtime_compaction_projection_outbox",
            "runtime_mob_host_bindings",
            "runtime_mob_host_revocations",
        ] {
            assert!(
                !runtime_tables.contains(absent),
                "capture {label} unexpectedly has {absent}"
            );
        }
    }
}

/// The runtime catalog is byte-stable across the published 0.7.x span and
/// across capture profiles, so one frozen predecessor covers all of them, and
/// so a row-bearing realm cannot be dismissed as "a different schema". Proven
/// by comparison, not asserted in a comment.
#[test]
fn pre_ledger_runtime_catalog_is_identical_across_the_published_span() {
    let manifest = load_manifest();
    let runtime_catalog = |capture: &PreLedgerCapture| {
        let mut rows = capture
            .sessions_sqlite_catalog
            .iter()
            .filter(|entry| entry.name.starts_with("runtime_"))
            .cloned()
            .collect::<Vec<_>>();
        rows.sort();
        rows
    };
    let all = captures(&manifest);
    let ((first_release, first_capture), rest) =
        all.split_first().expect("corpus has at least one capture");
    let baseline = runtime_catalog(first_capture);
    assert!(
        !baseline.is_empty(),
        "baseline runtime catalog for {}/{} is empty",
        first_release.meerkat_version,
        first_capture.capture_id
    );
    for (release, capture) in rest {
        assert_eq!(
            runtime_catalog(capture),
            baseline,
            "runtime catalog drifted between {}/{} and {}/{}",
            first_release.meerkat_version,
            first_capture.capture_id,
            release.meerkat_version,
            capture.capture_id
        );
    }
}

/// Row counts are read out of the committed databases, not believed from the
/// manifest. A manifest that claims rows the file does not have would rebuild
/// the exact failure this corpus exists to prevent: evidence that answers a
/// different question than the one asked.
#[test]
fn pre_ledger_corpus_row_counts_are_read_from_the_committed_bytes() {
    let manifest = load_manifest();
    for (release, capture) in captures(&manifest) {
        let label = format!("{}/{}", release.meerkat_version, capture.capture_id);
        let realm = capture_root(capture);

        let sessions = read_row_counts(&realm.join("sessions.sqlite3"));
        assert_eq!(
            sessions, capture.sessions_sqlite_row_counts,
            "capture {label} sessions.sqlite3 row counts differ from the manifest"
        );
        let workgraph = read_row_counts(&realm.join("workgraph.sqlite3"));
        assert_eq!(
            workgraph, capture.workgraph_sqlite_row_counts,
            "capture {label} workgraph.sqlite3 row counts differ from the manifest"
        );

        let input_rows = read_runtime_input_rows(&realm.join("sessions.sqlite3"));
        assert_eq!(
            input_rows, capture.runtime_input_state_rows,
            "capture {label} runtime input rows differ from the manifest"
        );
        assert_eq!(
            input_rows.len() as i64,
            *sessions.get("runtime_input_states").unwrap_or(&0),
            "capture {label} input-row descriptors disagree with its own row count"
        );
        assert_eq!(
            capture.carries_runtime_input_rows,
            !input_rows.is_empty(),
            "capture {label} misdeclares whether it carries runtime input rows"
        );
    }
}

/// At least one capture must be able to reach
/// `prepare_pre_0_8_10_runtime_input_states`. Round one's corpus could not:
/// every realm in it was written by a run that died before admitting any
/// input, so the callback that decides whether a real operator's realm opens
/// was never executed by any test, and a defect inside it shipped unseen.
#[test]
fn pre_ledger_corpus_can_reach_the_runtime_input_preparation_path() {
    let manifest = load_manifest();
    let row_bearing = captures(&manifest)
        .into_iter()
        .filter(|(_, capture)| capture.carries_runtime_input_rows)
        .collect::<Vec<_>>();
    assert!(
        row_bearing.len() >= 2,
        "the corpus must carry realms with durable runtime input rows from more than one \
         published vintage; found {} such capture(s). Without them the bridge's row-preparation \
         callback is never executed and this file proves only that empty realms migrate.",
        row_bearing.len()
    );
    for (release, capture) in row_bearing {
        let rows = read_runtime_input_rows(&capture_root(capture).join("sessions.sqlite3"));
        assert!(
            !rows.is_empty(),
            "capture {}/{} claims runtime input rows but the committed database has none",
            release.meerkat_version,
            capture.capture_id
        );
        for row in rows {
            assert_eq!(
                row.stored_input_state_version, 3,
                "the 0.7.x line wrote stored_input_state_version 3; {}/{} has {}",
                release.meerkat_version, capture.capture_id, row.stored_input_state_version
            );
        }
    }
}

/// The whole point: every realm in the corpus bridges to the current schema.
///
/// Before the 0.7.x predecessor was registered this failed with
/// `UnledgeredSchemaNoMatch { domain: "runtime-store", target_version: 3 }` -
/// the exact error the 0.8.23 report quoted.
#[test]
fn published_pre_ledger_realms_bridge_to_the_current_schema() {
    let manifest = load_manifest();
    assert!(!manifest.releases.is_empty(), "corpus has no realms to run");

    // Every capture is run before anything is reported. A test that dies on
    // the first refusal hides how far the damage reaches, and the operator
    // question here is exactly "which of my realms open".
    let mut refusals = Vec::new();
    for (release, capture) in captures(&manifest) {
        let label = format!("{}/{}", release.meerkat_version, capture.capture_id);
        if let Err(refusal) = bridge_one_capture(&label, &capture_root(capture)) {
            refusals.push(refusal);
        }
    }
    assert!(
        refusals.is_empty(),
        "the bridge named in the product's own remedy refused {} of the corpus realms:\n\n{}",
        refusals.len(),
        refusals.join("\n\n")
    );
}

/// Bridge one capture's `sessions.sqlite3` through all three domains, exactly
/// as `storage migrate --apply --bridge-pre-0-8-10` does. Returns the refusal
/// text, including what the ledger was left holding, rather than panicking.
fn bridge_one_capture(label: &str, realm: &Path) -> Result<(), String> {
    let source = realm.join("sessions.sqlite3");
    let scratch = tempfile::tempdir().expect("tempdir");
    let database = scratch.path().join("sessions.sqlite3");
    std::fs::copy(&source, &database)
        .unwrap_or_else(|error| panic!("copy {label} corpus: {error}"));

    let mut conn = meerkat_sqlite::open(
        &database,
        meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
    )
    .unwrap_or_else(|error| panic!("open {label} corpus for maintenance: {error}"));

    let session_domain = &meerkat_store::sqlite_store::SESSION_STORE_DOMAIN;
    let runtime_domain = &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN;
    let schedule_domain = &meerkat_store::schedule_sqlite_store::SCHEDULE_STORE_DOMAIN;

    let ledger_state = |conn: &rusqlite::Connection| {
        [session_domain, runtime_domain, schedule_domain]
            .iter()
            .map(|domain| {
                let stamped = meerkat_sqlite::domain_version(conn, domain.name)
                    .unwrap_or_else(|error| panic!("read {} ledger: {error}", domain.name));
                match stamped {
                    Some(version) => format!("{}=v{version}", domain.name),
                    None => format!("{}=unledgered", domain.name),
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    let session = meerkat_sqlite::bridge_unledgered_domain(
        &mut conn,
        session_domain,
        session_domain.supported_version(),
        &[1],
        Some(meerkat_store::sqlite_store::prepare_pre_0_8_10_session_base_schema),
    )
    .map_err(|error| {
        format!(
            "{label}: session-store bridge refused: {error}\n  ledger after: {}",
            ledger_state(&conn)
        )
    })?;
    assert_eq!(session.from_version, 1, "{label} session source version");
    assert_eq!(
        session.to_version,
        session_domain.supported_version(),
        "{label} session target version"
    );

    let runtime = meerkat_sqlite::bridge_unledgered_domain(
        &mut conn,
        runtime_domain,
        runtime_domain.supported_version(),
        &[1],
        Some(meerkat_runtime::store::sqlite::prepare_pre_0_8_10_runtime_input_states),
    )
    .map_err(|error| {
        format!(
            "{label}: runtime-store bridge refused: {error}\n  ledger after: {}\n  \
             This is the 0.8.23 defect: the bridge named in the product's own remedy \
             cannot open the realm its target releases wrote.",
            ledger_state(&conn)
        )
    })?;
    assert_eq!(runtime.from_version, 1, "{label} runtime source version");
    assert_eq!(
        runtime.to_version,
        runtime_domain.supported_version(),
        "{label} runtime target version"
    );

    let schedule = meerkat_sqlite::bridge_unledgered_domain(
        &mut conn,
        schedule_domain,
        schedule_domain.supported_version(),
        &[1],
        None,
    )
    .map_err(|error| {
        format!(
            "{label}: schedule-store bridge refused: {error}\n  ledger after: {}",
            ledger_state(&conn)
        )
    })?;
    assert_eq!(schedule.from_version, 1, "{label} schedule source version");
    assert_eq!(
        schedule.to_version,
        schedule_domain.supported_version(),
        "{label} schedule target version"
    );

    // The ledger is the durable proof, not the in-memory report.
    for domain in [session_domain, runtime_domain, schedule_domain] {
        let stamped = meerkat_sqlite::domain_version(&conn, domain.name)
            .unwrap_or_else(|error| panic!("read {} ledger: {error}", domain.name))
            .unwrap_or_else(|| panic!("{} has no ledger row after bridging", domain.name));
        assert_eq!(
            stamped,
            domain.supported_version(),
            "{label} realm left {} at version {stamped}",
            domain.name
        );
    }

    // Re-running the bridge on a bridged realm is a verified no-op, so an
    // operator who repeats the documented command is not punished.
    for domain in [session_domain, runtime_domain, schedule_domain] {
        let repeat = meerkat_sqlite::bridge_unledgered_domain(
            &mut conn,
            domain,
            domain.supported_version(),
            &[1],
            None,
        )
        .unwrap_or_else(|error| {
            panic!(
                "re-running the {label} bridge for {} refused: {error}",
                domain.name
            )
        });
        assert_eq!(repeat.from_version, domain.supported_version());
        assert_eq!(repeat.to_version, domain.supported_version());
    }
    Ok(())
}

/// A realm the bridge cannot authenticate must still be refused. The fix
/// widens what counts as a proven source; it must not turn the bridge into an
/// "apply DDL and hope" path.
#[test]
fn an_unrecognized_runtime_catalog_is_still_refused() {
    let manifest = load_manifest();
    let (_, capture) = capture_named(&manifest, "bootstrap-only");
    let source = capture_root(capture).join("sessions.sqlite3");
    let scratch = tempfile::tempdir().expect("tempdir");
    let database = scratch.path().join("sessions.sqlite3");
    std::fs::copy(&source, &database).expect("copy corpus");

    {
        let conn = meerkat_sqlite::open(
            &database,
            meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
        )
        .expect("open corpus");
        conn.execute_batch("ALTER TABLE runtime_states ADD COLUMN unreleased_column TEXT")
            .expect("diverge the catalog");
    }

    let mut conn = meerkat_sqlite::open(
        &database,
        meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
    )
    .expect("reopen diverged corpus");
    let runtime_domain = &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN;
    let error = meerkat_sqlite::bridge_unledgered_domain(
        &mut conn,
        runtime_domain,
        runtime_domain.supported_version(),
        &[1],
        Some(meerkat_runtime::store::sqlite::prepare_pre_0_8_10_runtime_input_states),
    )
    .expect_err("a catalog no release wrote must not be bridged");
    assert!(
        matches!(
            error,
            meerkat_sqlite::SqliteStoreError::UnledgeredSchemaNoMatch { ref domain, .. }
                if domain == "runtime-store"
        ),
        "unexpected refusal: {error}"
    );
    assert!(
        meerkat_sqlite::domain_version(&conn, runtime_domain.name)
            .expect("read ledger")
            .is_none(),
        "a refused domain must not be stamped"
    );
}

/// The honest-remedy predicate, evaluated against real released bytes, and
/// evaluated against the realm that actually has rows in it.
///
/// THIS IS THE ANTI-REGRESSION FOR THE FALSE PROMISE. Round one pinned this
/// test to `bootstrap-only` precisely because `attempted-turn` would have
/// exposed the divergence: the predicate said "recoverable" over a file the
/// bridge then refused eighty lines below. A predicate that answers about
/// catalog shape is fine; a predicate whose answer is rendered to an operator
/// as "run the bridge and retry" while the bridge refuses that same file is
/// the defect. So the subject here is every row-bearing capture, and the
/// assertion is agreement between the two oracles: whatever the predicate
/// promises, the bridge must deliver on the identical bytes.
#[test]
fn bridge_eligibility_agrees_with_the_bridge_on_row_bearing_realms() {
    let manifest = load_manifest();
    let row_bearing = captures(&manifest)
        .into_iter()
        .filter(|(_, capture)| capture.carries_runtime_input_rows)
        .collect::<Vec<_>>();
    assert!(
        !row_bearing.is_empty(),
        "this test is meaningless without a row-bearing capture"
    );

    // EVERY domain in the file, not just the runtime store. The predecessor of
    // this test asked only the runtime domain, which had always answered
    // correctly, so it stayed green while an ordinary open told operators that
    // the *session* domain of the very same realm was unrecoverable. A test
    // that samples one of three co-tenants is not an oracle for the sentence
    // the product prints.
    let sessions_file_domains: [&meerkat_sqlite::SchemaDomain; 3] = [
        &meerkat_store::sqlite_store::SESSION_STORE_DOMAIN,
        &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN,
        &meerkat_store::schedule_sqlite_store::SCHEDULE_STORE_DOMAIN,
    ];
    for (release, capture) in row_bearing {
        let label = format!("{}/{}", release.meerkat_version, capture.capture_id);
        let source = capture_root(capture).join("sessions.sqlite3");
        let scratch = tempfile::tempdir().expect("tempdir");
        let database = scratch.path().join("sessions.sqlite3");
        std::fs::copy(&source, &database).expect("copy corpus");

        for domain in sessions_file_domains {
            let promised = {
                let conn =
                    meerkat_sqlite::open(&database, meerkat_sqlite::ConnectionProfile::ReadOnly)
                        .expect("open corpus read-only");
                assert_eq!(
                    domain.bridgeable_source_version(&conn),
                    Some(1),
                    "{label}: the 0.7.x {} catalog authenticates as version 1",
                    domain.name
                );
                domain.bridge_eligibility(&conn)
            };
            assert_eq!(
                promised,
                meerkat_sqlite::BridgeEligibility::CatalogAuthenticated,
                "{label}: a realm written by published rkat must be reported as bridgeable, \
                 including its {} domain",
                domain.name
            );
        }

        // The same bytes, through the oracle the operator's command actually
        // runs. `CatalogAuthenticated` must mean the domain lands.
        let delivered = bridge_one_capture(&label, &capture_root(capture));
        assert!(
            delivered.is_ok(),
            "{label}: eligibility promised every domain was bridgeable and the bridge then \
             refused the same file. That is the false promise this P0 exists to remove.\n{}",
            delivered.unwrap_err()
        );
    }
}

/// The bridge's production callers must authorize exactly the source versions
/// the eligibility oracle answers from.
///
/// The oracle reads [`meerkat_sqlite::SchemaDomain::bridge_recoverable_versions`],
/// and so, now, does the realm bridge. A domain whose declared list drifted
/// from the source version its released files actually carry would put the
/// message and the command back on two different answers, which is the defect
/// that made an ordinary open call a bridgeable realm unrecoverable.
#[test]
fn every_sessions_file_domain_declares_the_source_versions_its_bridge_uses() {
    for domain in [
        &meerkat_store::sqlite_store::SESSION_STORE_DOMAIN,
        &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN,
        &meerkat_store::schedule_sqlite_store::SCHEDULE_STORE_DOMAIN,
    ] {
        assert_eq!(
            domain.bridge_recoverable_versions,
            &[1],
            "{} must declare the source version the realm bridge runs with",
            domain.name
        );
    }
}

/// The row-preparation callback must not be able to buy admission by
/// dropping the operator's state.
///
/// Without this, a "fix" that admitted rows by blanking a field would pass
/// every other test in this file. The subject is the callback alone, run
/// under its own transaction, so the assertion is about the code this P0
/// changed and not about the migration chain that runs after it.
#[test]
fn the_row_preparation_callback_preserves_every_durable_fact() {
    for (label, capture) in row_bearing_captures() {
        let before = read_runtime_input_json(&capture.join("sessions.sqlite3"));
        assert!(
            !before.is_empty(),
            "{label}: capture claims rows but has none"
        );

        let scratch = tempfile::tempdir().expect("tempdir");
        let database = scratch.path().join("sessions.sqlite3");
        std::fs::copy(capture.join("sessions.sqlite3"), &database).expect("copy corpus");
        {
            let mut conn = meerkat_sqlite::open(
                &database,
                meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
            )
            .expect("open corpus for maintenance");
            let tx = conn.transaction().expect("tx");
            let report =
                meerkat_runtime::store::sqlite::prepare_pre_0_8_10_runtime_input_states(&tx)
                    .unwrap_or_else(|error| panic!("{label}: callback refused the realm: {error}"));
            assert_eq!(
                report.changed,
                before.len(),
                "{label}: the callback must carry every row it was given"
            );
            assert!(
                report.refused.is_empty(),
                "{label}: the callback left records behind: {:?}",
                report.refused
            );
            tx.commit().expect("commit");
        }

        let after = read_runtime_input_json(&database);
        assert_eq!(
            after.keys().collect::<Vec<_>>(),
            before.keys().collect::<Vec<_>>(),
            "{label}: the callback changed which input rows exist"
        );
        for (key, before) in &before {
            let after = &after[key];
            assert_eq!(
                after["stored_input_state_version"], 5,
                "{label} {key}: a carried row must be left in the current encoding"
            );
            assert_eq!(
                after["persisted_input"], before["persisted_input"],
                "{label} {key}: THE OPERATOR'S OWN PROMPT did not survive the callback"
            );
            for field in [
                "input_id",
                "current_state",
                "terminal_outcome",
                "durability",
                "attempt_count",
                "recovery_count",
                "policy",
                "runtime_semantics",
                "admission_sequence",
            ] {
                assert_eq!(
                    after[field], before[field],
                    "{label} {key}: `{field}` did not survive the callback unchanged"
                );
            }
            assert_eq!(
                history_signature(after),
                history_signature(before),
                "{label} {key}: history entries were dropped or rewritten"
            );
        }
    }
}

/// After the WHOLE bridge, the row is still the operator's row - payload and
/// all.
///
/// This is the assertion the corpus was missing. Its predecessor asserted the
/// opposite for terminal rows: that the runtime-store v1 -> v2 migration had
/// retired their ingress payload. On the real corpus that meant the operator's
/// own prompt, `"hello"`, was present in `sessions.sqlite3` before the bridge
/// and gone after it, while the bridge reported success and said nothing. A
/// rescue that deletes what it was run to save is worse than the refusal it
/// replaced, so the retirement no longer runs under the bridge and this test
/// pins the payload's survival across the whole chain, not just the callback.
///
/// The non-vacuity guard below matters as much as the equality: a capture
/// whose rows carried no payload would let a blanking regression pass this
/// test silently.
#[test]
fn bridging_a_row_bearing_realm_keeps_the_row_and_every_ingress_payload() {
    for (label, capture) in row_bearing_captures() {
        let before = read_runtime_input_json(&capture.join("sessions.sqlite3"));
        let scratch = tempfile::tempdir().expect("tempdir");
        let database = scratch.path().join("sessions.sqlite3");
        std::fs::copy(capture.join("sessions.sqlite3"), &database).expect("copy corpus");
        {
            let mut conn = meerkat_sqlite::open(
                &database,
                meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
            )
            .expect("open corpus for maintenance");
            for (domain, prepare) in [
                (
                    &meerkat_store::sqlite_store::SESSION_STORE_DOMAIN,
                    meerkat_store::sqlite_store::prepare_pre_0_8_10_session_base_schema
                        as meerkat_sqlite::MaintenancePrepareFn,
                ),
                (
                    &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN,
                    meerkat_runtime::store::sqlite::prepare_pre_0_8_10_runtime_input_states
                        as meerkat_sqlite::MaintenancePrepareFn,
                ),
            ] {
                let report = meerkat_core::with_pre_floor_provider_image_metadata_import(|| {
                    meerkat_sqlite::bridge_unledgered_domain(
                        &mut conn,
                        domain,
                        domain.supported_version(),
                        &[1],
                        Some(prepare),
                    )
                })
                .unwrap_or_else(|error| panic!("{label}: {} bridge refused: {error}", domain.name));
                assert!(
                    report.refused.is_empty(),
                    "{label}: {} left records behind: {:?}",
                    domain.name,
                    report.refused
                );
            }
        }

        let after = read_runtime_input_json(&database);
        assert_eq!(
            after.keys().collect::<Vec<_>>(),
            before.keys().collect::<Vec<_>>(),
            "{label}: the bridge changed which input rows exist"
        );
        for (key, before) in &before {
            let after = &after[key];
            for field in [
                "input_id",
                "current_state",
                "terminal_outcome",
                "durability",
                "attempt_count",
                "recovery_count",
                "policy",
                "runtime_semantics",
                "admission_sequence",
            ] {
                assert_eq!(
                    after[field], before[field],
                    "{label} {key}: `{field}` did not survive the bridge unchanged"
                );
            }
            assert_eq!(
                history_signature(after),
                history_signature(before),
                "{label} {key}: history entries were dropped or rewritten"
            );

            // Non-vacuity first: without this, a bridge that admitted rows by
            // blanking them would pass the equality below on any capture whose
            // payload happened to be absent.
            let carried = before["persisted_input"]["content"]
                .as_str()
                .unwrap_or_else(|| {
                    panic!(
                        "{label} {key}: this capture carries no ingress payload text, so the \
                         preservation assertion below would prove nothing. Mint a capture whose \
                         writer admitted an operator prompt."
                    )
                });
            assert!(
                !carried.is_empty(),
                "{label} {key}: an empty ingress payload cannot witness preservation"
            );
            assert_eq!(
                after["persisted_input"], before["persisted_input"],
                "{label} {key}: THE OPERATOR'S OWN PROMPT ({carried:?}) did not survive the \
                 bridge. It was present in sessions.sqlite3 before and is not present after, \
                 and the bridge reported success."
            );
        }
    }
}

/// Every capture whose committed bytes carry runtime input rows, as
/// `(label, realm root)`. Tests about row admission run over all of them.
fn row_bearing_captures() -> Vec<(String, PathBuf)> {
    let manifest = load_manifest();
    let found = captures(&manifest)
        .into_iter()
        .filter(|(_, capture)| capture.carries_runtime_input_rows)
        .map(|(release, capture)| {
            (
                format!("{}/{}", release.meerkat_version, capture.capture_id),
                capture_root(capture),
            )
        })
        .collect::<Vec<_>>();
    assert!(
        !found.is_empty(),
        "no row-bearing capture: every test about row admission would pass over nothing"
    );
    found
}

fn history_signature(row: &serde_json::Value) -> Vec<String> {
    row["history"]
        .as_array()
        .expect("history array")
        .iter()
        .map(|entry| format!("{}->{}:{}", entry["from"], entry["to"], entry["reason"]))
        .collect()
}

/// The NEGATIVE case of the honest-remedy predicate, against real released
/// bytes: a catalog no release wrote must not be advertised as bridgeable.
///
/// The positive case moved to
/// `bridge_eligibility_agrees_with_the_bridge_on_row_bearing_realms`, which
/// checks it where it matters - against a realm that has rows in it. This
/// test's own comment used to say that pointing it at `attempted-turn` would
/// expose a bridge refusal on the same file. That was true of the defect and
/// is no longer true of the tree: the row-bearing captures bridge.
#[test]
fn an_unrecognized_catalog_is_not_advertised_as_bridgeable() {
    let manifest = load_manifest();
    let (_release, capture) = capture_named(&manifest, "bootstrap-only");
    let source = capture_root(capture).join("sessions.sqlite3");
    let scratch = tempfile::tempdir().expect("tempdir");
    let database = scratch.path().join("sessions.sqlite3");
    std::fs::copy(&source, &database).expect("copy corpus");

    let runtime_domain = &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN;
    let conn = meerkat_sqlite::open(
        &database,
        meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
    )
    .expect("open corpus for maintenance");
    conn.execute_batch("ALTER TABLE runtime_states ADD COLUMN unreleased_column TEXT")
        .expect("diverge the catalog");
    assert_eq!(
        runtime_domain.bridge_eligibility(&conn),
        meerkat_sqlite::BridgeEligibility::Unrecognized,
        "a catalog no release wrote must not be advertised as bridgeable"
    );
    assert_eq!(runtime_domain.bridgeable_source_version(&conn), None);
    drop(conn);

    // Both halves of the honest answer, on the same bytes: the negative
    // message must be matched by an actual refusal. An oracle checked only
    // against itself proves nothing about what the operator's next command
    // does.
    let mut conn = meerkat_sqlite::open(
        &database,
        meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
    )
    .expect("reopen corpus for maintenance");
    let refused = meerkat_sqlite::bridge_unledgered_domain(
        &mut conn,
        runtime_domain,
        runtime_domain.supported_version(),
        runtime_domain.bridge_recoverable_versions,
        Some(meerkat_runtime::store::sqlite::prepare_pre_0_8_10_runtime_input_states),
    );
    assert!(
        refused.is_err(),
        "eligibility said Unrecognized and the bridge then accepted the same file"
    );
}

/// Bridge every domain of one `sessions.sqlite3` in place, as the CLI does,
/// and hand back the runtime-store outcome.
fn bridge_sessions_file_in_place(
    database: &Path,
) -> Result<meerkat_sqlite::MaintenanceBridgeReport, meerkat_sqlite::SqliteStoreError> {
    let mut conn = meerkat_sqlite::open(
        database,
        meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
    )
    .expect("open realm for maintenance");
    let mut runtime_outcome = None;
    for (domain, prepare) in [
        (
            &meerkat_store::sqlite_store::SESSION_STORE_DOMAIN,
            Some(
                meerkat_store::sqlite_store::prepare_pre_0_8_10_session_base_schema
                    as meerkat_sqlite::MaintenancePrepareFn,
            ),
        ),
        (
            &meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN,
            Some(
                meerkat_runtime::store::sqlite::prepare_pre_0_8_10_runtime_input_states
                    as meerkat_sqlite::MaintenancePrepareFn,
            ),
        ),
        (
            &meerkat_store::schedule_sqlite_store::SCHEDULE_STORE_DOMAIN,
            None,
        ),
    ] {
        let outcome = meerkat_core::with_pre_floor_provider_image_metadata_import(|| {
            meerkat_sqlite::bridge_unledgered_domain(
                &mut conn,
                domain,
                domain.supported_version(),
                domain.bridge_recoverable_versions,
                prepare,
            )
        });
        if domain.name == meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN.name {
            runtime_outcome = Some(outcome);
            continue;
        }
        outcome.unwrap_or_else(|error| panic!("{} bridge refused: {error}", domain.name));
    }
    runtime_outcome.expect("the runtime domain was bridged")
}

/// Copy a row-bearing capture into a scratch realm and rewrite its single
/// input row's JSON through `mutate`, keeping the column a BLOB.
fn corpus_realm_with_mutated_input_row(
    scratch: &Path,
    mutate: impl FnOnce(&mut serde_json::Value),
) -> (PathBuf, String, Vec<u8>) {
    let (_label, capture) = row_bearing_captures()
        .into_iter()
        .next()
        .expect("a row-bearing capture");
    let database = scratch.join("sessions.sqlite3");
    std::fs::copy(capture.join("sessions.sqlite3"), &database).expect("copy corpus");

    let conn = meerkat_sqlite::open(
        &database,
        meerkat_sqlite::ConnectionProfile::Maintenance { write: true },
    )
    .expect("open corpus for maintenance");
    let (runtime_id, input_id, source): (String, String, Vec<u8>) = conn
        .query_row(
            "SELECT runtime_id, input_id, state_json FROM runtime_input_states",
            [],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
        )
        .expect("read the sole input row");
    let mut decoded: serde_json::Value =
        serde_json::from_slice(&source).expect("input row is JSON");
    mutate(&mut decoded);
    let replacement = serde_json::to_vec(&decoded).expect("re-encode input row");
    conn.execute(
        "UPDATE runtime_input_states SET state_json = ?1 WHERE runtime_id = ?2 AND input_id = ?3",
        rusqlite::params![replacement, &runtime_id, &input_id],
    )
    .expect("plant the mutated row");
    drop(conn);
    (database, format!("{runtime_id}/{input_id}"), replacement)
}

fn sole_input_row_bytes(database: &Path) -> Vec<u8> {
    let conn = meerkat_sqlite::open(database, meerkat_sqlite::ConnectionProfile::ReadOnly)
        .expect("open realm read-only");
    conn.query_row("SELECT state_json FROM runtime_input_states", [], |row| {
        row.get::<_, Vec<u8>>(0)
    })
    .expect("read the sole input row")
}

/// A record the preparation refused must be byte-identical after the WHOLE
/// bridge, because that is exactly what the operator is told.
///
/// The per-record refusal note promises the bytes are untouched on disk. It
/// was not true: the preparation left the row alone and the v1 -> v2 released
/// importers that run afterwards then decoded it, dropped the field the
/// current types cannot name, and rewrote it. The claim and the behaviour now
/// agree, and this test is the thing that keeps them agreeing.
#[test]
fn a_refused_record_is_byte_identical_after_the_whole_bridge() {
    let scratch = tempfile::tempdir().expect("tempdir");
    let (database, record, planted) = corpus_realm_with_mutated_input_row(scratch.path(), |row| {
        row["unknown_future_field"] = serde_json::json!({"written": "by a later binary"});
    });

    let report = bridge_sessions_file_in_place(&database)
        .expect("one unrepresentable record must not cost the operator the whole runtime domain");
    assert_eq!(
        report.to_version,
        meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN.supported_version(),
        "the domain must still land"
    );
    let refusal = report
        .refused
        .iter()
        .find(|refusal| refusal.record.contains(&record))
        .unwrap_or_else(|| panic!("the refused record was not named: {:?}", report.refused));
    assert!(
        refusal.reason.contains("unknown_future_field"),
        "the operator must learn which fact could not be carried: {}",
        refusal.reason
    );
    assert_eq!(
        sole_input_row_bytes(&database),
        planted,
        "a refused record's bytes were rewritten after the CLI said they were untouched"
    );
}

/// A single undecodable value must not cost the operator the domain they were
/// told to bridge.
///
/// The eligibility message says the schema is recognized and names the bridge.
/// With one row carrying `attempt_count: "three"` the released importers used
/// to fail the whole runtime-store migration, so the session, schedule and
/// workgraph domains committed and the runtime domain did not: the promise the
/// operator acted on was false by the branch's own probe.
#[test]
fn an_undecodable_record_does_not_cost_the_domain() {
    let scratch = tempfile::tempdir().expect("tempdir");
    let (database, record, planted) = corpus_realm_with_mutated_input_row(scratch.path(), |row| {
        row["attempt_count"] = serde_json::json!("three");
    });

    let report = bridge_sessions_file_in_place(&database)
        .expect("an undecodable record must be refused per record, not per domain");
    assert_eq!(
        report.to_version,
        meerkat_runtime::store::sqlite::RUNTIME_STORE_DOMAIN.supported_version(),
        "the domain the operator was told to bridge must land"
    );
    assert!(
        report
            .refused
            .iter()
            .any(|refusal| refusal.record.contains(&record)),
        "the undecodable record was not named: {:?}",
        report.refused
    );
    assert_eq!(
        sole_input_row_bytes(&database),
        planted,
        "an undecodable record's bytes must be left exactly as found"
    );
}
